### ISSUE TITLE
`create-nx-workspace` command not working with `pnpm` v7

### ISSUE THREAD

**Issue by hubertkuoch** [nrwl/nx#10172]
## Current Behavior
When running `pnpx create-nx-workspace@latest` (v14.1.1) with the latest version of `pnpm`(v7.0.0), the dependencies installation fails.

## Expected Behavior

It should install without error as it does with `pnpm` v^6.

## Steps to Reproduce
```zsh
pnpx create-nx-workspace@latest
// or
pnpm dlx create-nx-workspace@latest
```

**Comment by AgentEnder** [comment]
Hey @hubertkuoch! This was fixed in 14.1.3, so I'm going to close this out. Thanks for the report!

**Comment by hubertkuoch** [comment]
Hi @AgentEnder - Just tried the command again and am still facing the same issue unfortunately, just pasting some screenshots below to show exactly what I get as I cannot find out the reason for this, sorry about that.

From terminal:

<img width="1139" alt="Screenshot 2022-05-06 at 10 58 25" src="https://user-images.githubusercontent.com/50402245/167100771-a3488999-6275-4a6b-a19c-bffd2675f2d9.png">
<img width="1131" alt="Screenshot 2022-05-06 at 11 01 00" src="https://user-images.githubusercontent.com/50402245/167101159-16eea31a-cef4-4894-879b-bd19efcc9212.png">

Error log:

<img width="975" alt="Screenshot 2022-05-06 at 11 03 53" src="https://user-images.githubusercontent.com/50402245/167101634-c764d468-06c6-447b-957f-808255954e27.png">

**Comment by hubertkuoch** [comment]
I also tried the following:
- scaffold a new workspace with `cnw` and `pnpm`@^6
- delete `node_modules` and `pnpm-lock.yaml`
- re-install with `pnpm`@7

<img width="1135" alt="Screenshot 2022-05-06 at 11 33 28" src="https://user-images.githubusercontent.com/50402245/167106386-97c32274-ac40-4e55-a670-c0994ba5f79b.png">

**Comment by AndrewTelkamp** [comment]
+1, also seeing this issue

**Comment by AgentEnder** [comment]
Hmmm, interesting. Let me reach out to the people who worked on the fix.

**Comment by meeroslav** [comment]
Thank you for reporting it. We will have a look as soon as possible.

In the meantime, can you try running `npx create-nx-workspace@latest --package-manager=pnpm` and see if that gives the same results?

**Comment by hubertkuoch** [comment]
Hi @meeroslav - yes it fails as well (with empty error log)

<img width="1058" alt="Screenshot 2022-05-06 at 18 13 19" src="https://user-images.githubusercontent.com/50402245/167171773-47aa39c7-b165-4dec-b839-e08b7b36cdc7.png">

**Comment by meeroslav** [comment]
Thanks, I will get to it as soon as possible. Sorry for the inconvenience

**Comment by meeroslav** [comment]
Unfortunately, I'm unable to reproduce it on my machine

<img width="999" alt="Screenshot 2022-05-06 at 23 21 19" src="https://user-images.githubusercontent.com/881612/167218076-c1803750-b348-4c44-b30f-e7942d7de0ed.png">
<img width="994" alt="Screenshot 2022-05-06 at 23 21 42" src="https://user-images.githubusercontent.com/881612/167218116-c5b5614f-f9b4-4436-a685-06aed4a41979.png">

Can you let me know what environment are you using?
- Node version
- Npm
- OS (+CPU architecture)

**Comment by hubertkuoch** [comment]
- Node version: 16.15.0
- Npm: 8.5.5
- OS (+CPU architecture arch): MacOS Monterey Apple M1 Pro ARM64

**Comment by hubertkuoch** [comment]
Hi @meeroslav 

May I ask whether you actually have a next.js app in the `apps` folder when you run the same commands?

Just asking because I realised today that (not sure whether any of the below are related/relevant to this issue though):
- when I uninstall/re-install `pnpm` via the [shell script](https://pnpm.io/installation), the `cnw` command runs without error BUT when opening the workspace, no app is actually generated in the `apps` folder
- In order to fix that, I tried generating an app (via Nx Console), but it errors out that the `pnpx` command is not valid so I re-installed `pnpm` with `homebrew` (this will just re-link `pnpm` to the previously installed version via shell-script), and when finally running the command again I get the same error as shown above in the screenshots:
 
Running the command:
<img width="947" alt="Screenshot 2022-05-07 at 17 16 11" src="https://user-images.githubusercontent.com/50402245/167261705-cc0c632f-20fe-488e-983d-a57ce46ad0c0.png">

Running the command in dry-run mode:
<img width="959" alt="Screenshot 2022-05-07 at 17 36 07" src="https://user-images.githubusercontent.com/50402245/167261710-1478c938-963f-4ca5-ad31-6ded07670116.png">

I must admit I am running out of idea regarding potential causes vis-à-vis `pnpm`/`cnw`.

**Comment by hubertkuoch** [comment]
Closing the issue as uninstalling pnpm, deleting cached dot folders and re-installing it solves the issue.
