### ISSUE TITLE
rxjs 7 incompatible rxjs-for-await dependency

### ISSUE THREAD

**Issue by daniel-zero** [nrwl/nx#10308]
## Current Behavior
After upgrading to `@nrwl/angular@14.1.5` npm shows the following warning

```log
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: rxjs-for-await@0.0.2
```

## Expected Behavior
The `@nrwl/angular@14.1.5` package should be compatible with `rxjs@7`

## Steps to Reproduce
Create a new angular nx-workspace and upgrade to rxjs@7

### Failure Logs
```log
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: rxjs-for-await@0.0.2
npm WARN Found: rxjs@7.5.5
npm WARN node_modules/rxjs
npm WARN   rxjs@"7.5.5" from the root project
npm WARN   19 more (@angular/cdk, @angular/common, @angular/core, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peer rxjs@"^6.0.0" from rxjs-for-await@0.0.2
npm WARN node_modules/rxjs-for-await
npm WARN   rxjs-for-await@"0.0.2" from @nrwl/angular@14.1.5
npm WARN   node_modules/@nrwl/angular
npm WARN   1 more (nx)
npm WARN 
npm WARN Conflicting peer dependency: rxjs@6.6.7
npm WARN node_modules/rxjs
npm WARN   peer rxjs@"^6.0.0" from rxjs-for-await@0.0.2
npm WARN   node_modules/rxjs-for-await
npm WARN     rxjs-for-await@"0.0.2" from @nrwl/angular@14.1.5
npm WARN     node_modules/@nrwl/angular
npm WARN     1 more (nx)
```
```

### Environment
```log
Node : 16.15.0
   OS   : darwin arm64
   npm  : 8.10.0
   
   nx : 14.1.5
   @nrwl/angular : 14.1.5
   @nrwl/cypress : 14.1.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.1.5
   @nrwl/eslint-plugin-nx : 14.1.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.1.5
   @nrwl/js : 14.1.4
   @nrwl/linter : 14.1.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.0.3
   @nrwl/nx-plugin : 14.1.4
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.1.5
   @nrwl/web : Not Found
   @nrwl/workspace : 14.1.5
   typescript : 4.6.4
   rxjs : 7.5.5
   ---------------------------------------
   Community plugins:
         @ionic/angular: 6.1.5
         @ng-bootstrap/ng-bootstrap: 11.0.1
         @jscutlery/semver: 2.23.4
         @ngneat/spectator: 10.0.1
```

**Comment by ShiJuuRoku** [comment]
I think issue come with npm 8.10.0
With npm 8.5.0, there is no issue.

Else you can add  rxjs-for-await@^1.0.0 as dev-dependency

**Comment by vrxj81** [comment]
> I'm on Node `v16.14.2` and npm `8.10.0` and having similar issues with the `fetch` utility exported by `@nrwl/angular`.
> 
> The dependencies of my project contain `"rxjs": "~7.4.0"`, but the version installed within `@nrwl/angular/node_modules` is `rxjs@6.6.7`.
> 
> This mismatch causes problems when returning an `Observable` from `fetch({ run: ... })` because RxJS 6 ─► 7 introduced [breaking changes](https://rxjs.dev/6-to-7-change-summary#observable) affecting `Observable`.
> 
> Now `fetch` expects the function passed to `run` to return an `rxjs@^6` `Observable`, but my code returns an `rxjs@^7` `Observable`, causing the following error:
> 
> ```
> Type 'Observable<...>' is missing the following properties from type 'Observable<...>': _isScalar, 
> _trySubscribe, _subscribe
> ```
> 
> ... which are exactly the properties affected by the breaking changes.
> 
> Inspecting my `package-lock.json`, I saw that `rxjs-for-await@0.0.2` and `jasmine-marbles@0.8.4` have a peer dependency to `rxjs@^6.0.0` and `rxjs@^6.5.3` respectively.
> 
> I assume updating those two packages would solve the issues mentioned above because the newer versions of `rxjs-for-await` and `jasmine-marbles` peer-depend on `rxjs@^7`.
> 
> As @WolfspiritM already pointed out, one "hacky" workaround is to remove `"node_modules/@nrwl/angular/node_modules/rxjs"` manually from your `package-lock.json`, remove all your dependencies with `rm -rf node_modules` and reinstall everthing with `npm install`.

The workaround doesn't seem to work for me :(

**Comment by abrevlan** [comment]
For me, I just ran `npm update` and it just went away.

It added nearly 600 packages, removed 235, and changed 72. I don't really know which packages it affected but it works fine for me.

**Comment by leosvelperez** [comment]
This issue has been addressed in https://github.com/nrwl/nx/pull/11182 and should be released in v14.5.0. Please keep an eye on the releases to get the fix.

**Comment by irowbin** [comment]
@leosvelperez 
It seems the issue is still there. Currently on version `14.7.13` and when I run `npm install`, the issue appears and when I run  `npx nx migrate --run-migrations` afterwards, it disappears.  Looks like this migration cmd is required now.


```powershell

   Node : 16.17.0
   OS   : win32 x64
   npm  : 8.15.0

   nx : 14.7.13
   @nrwl/angular : 14.7.13
   @nrwl/cypress : 14.7.13
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.7.13
   @nrwl/eslint-plugin-nx : 14.7.13
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.7.13
   @nrwl/js : 14.7.13
   @nrwl/linter : 14.7.13
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.6.2
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.7.13
   @nrwl/web : Not Found
   @nrwl/workspace : 14.7.13
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @ngrx/component-store: 14.0.2
         @ngrx/effects: 14.0.2
         @ngrx/entity: 14.0.2
         @ngrx/router-store: 14.0.2
         @ngrx/store: 14.0.2
         @ngrx/schematics: 14.0.2
         @ngrx/store-devtools: 14.0.2

```
