### ISSUE TITLE
ng g app... Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by jwright04** [nrwl/nx#1096]
I don't seem to see this exact issue here, but I create my angular project, then run 

`ng g app dashboard --routing -p=app --style=scss --d` 

I get the following prompts
```
? In which directory should the application be generated? apps
? Which Unit Test Runner would you like to use for the application? Karma [ https://karma-runner.github.io ]
? Which E2E Test Runner would you like to use for the application? Protractor [ https://www.protractortest.org ]
? Which tags would you like to add to the application? (used for linting) test
```

I end up with the error

`Cannot read property 'toString' of null`

I'm obviously doing something wrong, any suggestions?

```
Angular CLI: 7.3.3
Node: 9.9.0
OS: darwin x64
Angular: 7.2.6

@angular-devkit/architect         0.13.3
@angular-devkit/build-angular     0.13.3
@angular-devkit/build-optimizer   0.13.3
@angular-devkit/build-webpack     0.13.3
@angular-devkit/core              7.3.3
@angular-devkit/schematics        7.3.3
@angular/cli                      7.3.3
@ngtools/webpack                  7.3.3
@schematics/angular               7.3.3
@schematics/update                0.13.3
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.29.0

"@nrwl/nx": "7.6.0",
"@nrwl/schematics": "7.6.0",
```

- [ x] I am running the latest version
- [ x] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed (similar issues have but not exact)
- [ x] I'm reporting the issue to the correct repository (not related to Angular, AngularCLI or any dependency) i'm running the ng command using the nrwl schematics

## Expected Behavior

Please describe the behavior you are expecting
`Create a new app called "dashboard" in "apps" directory`

## Current Behavior

What is the current behavior?
`Cannot read property 'toString' of null`

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

**Comment by wsmith-nwfsc** [comment]
I'm seeing this issue as well.

$ ng --version
Angular CLI: 7.3.0
Node: 10.15.1
OS: win32 x64
Angular:
...
typescript                   3.2.2

@nrwl/schematics@7.6.0


$ ng g app example
? In which directory should the application be generated? example
? Would you like to add Angular routing? No
? Which Unit Test Runner would you like to use for the application? Jest   [ https://jestjs.io ]
? Which E2E Test Runner would you like to use for the application? Cypress       [ https://www.cypress.io ]
? Which tags would you like to add to the application? (used for linting)
**Path "/apps/example/example-e2e/tsconfig.e2e.json" does not exist.**

C:\git\boatnet\workspace>ng g app example
? In which directory should the application be generated? example
? Would you like to add Angular routing? No
? Which Unit Test Runner would you like to use for the application? Karma [ https://karma-runner.github.io ]
? Which E2E Test Runner would you like to use for the application? Protractor [ https://www.protractortest.org ]
? Which tags would you like to add to the application? (used for linting) test
**Cannot read property 'toString' of null**

**Comment by stekosto** [comment]
**Exact same issue here.**

Angular CLI: 7.3.3
Node: 10.10.0
OS: win32 x64
Angular: 7.2.6
``
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.3
@angular-devkit/build-angular     0.13.3
@angular-devkit/build-optimizer   0.13.3
@angular-devkit/build-webpack     0.13.3
@angular-devkit/core              7.3.3
@angular-devkit/schematics        7.3.3
@angular/cli                      7.3.3
@ngtools/webpack                  7.3.3
@schematics/angular               7.3.3
@schematics/update                0.13.3
rxjs                              6.4.0
typescript                        3.2.4
webpack                           4.29.0

$ ng g app demo
? In which directory should the application be generated? demo
? Would you like to add Angular routing? Yes
? Which Unit Test Runner would you like to use for the application? Karma [ https://karma-runner.github.io ]
? Which E2E Test Runner would you like to use for the application? Protractor [ https://www.protractortest.org ]
? Which tags would you like to add to the application? (used for linting) lintTag
**Cannot read property 'toString' of null**

**Comment by zmszaman** [comment]
It looks like a bug in newest version of schematic. It works when you downgrade it to previous version:
`npm install -g @angular/cli @nrwl/schematics@~7.5.2`

**Comment by Muromi-Rikka** [comment]
I mean it

**Comment by Muromi-Rikka** [comment]
+1

**Comment by jwright04** [comment]
+1

**Comment by isaacplmann** [comment]
You can also solve this issue by using `@nrwl/schematics@7.6.1` and `@angular/cli@7.3.1`.

Another problem caused by `@nrwl/schematics@7.6.1` and `@angular/cli@7.3.3` is that you can't generate a lib.

```
ng generate @nrwl/schematics:library mylib

Path "/libs/mylib/src/lib/mylib.service.ts" does not exist.
```

**Comment by FrozenPandaz** [comment]
@isaacplmann is right, `@angular/cli@7.3.3` has a breaking change with how applications and libraries are generated.

✅ A fix has been released in `@nrwl/schematics@7.6.1` which fixes the issue for new workspaces.
⌛️ We are working on another patch release which will resolve the issue for updating workspaces.
⌛️ We are also working with the Angular CLI on the breaking change.

Sorry for the inconvenience. 😞

**Comment by FrozenPandaz** [comment]
I'm going to mark this as resolved form our end. We've rolled out `@nrwl/schematics@7.2.2` which should not have this issue anymore. Let us know if you see anymore issues.

**Comment by gund** [comment]
Issue still persists with `@nrwl/schematics@7.6.2`:
`Cannot read property 'toString' of null`

Also I'm getting different error messages if I pick different E2E frameworks:
- When I choose Protractor: `Cannot read property 'toString' of null`
- When I choose Cypress: `Path "/apps/myapp-e2e/tsconfig.e2e.json" does not exist.`

Looks like a regression to me...

```
Angular CLI: 7.3.3
Node: 11.9.0
OS: darwin x64
Angular: 7.2.6
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.13.3
@angular-devkit/build-angular      0.13.3
@angular-devkit/build-ng-packagr   0.13.3
@angular-devkit/build-optimizer    0.13.3
@angular-devkit/build-webpack      0.13.3
@angular-devkit/core               7.3.3
@angular-devkit/schematics         7.3.3
@angular/cdk                       7.3.3
@angular/cli                       7.3.3
@ngtools/json-schema               1.1.0
@ngtools/webpack                   7.3.3
@schematics/angular                7.3.3
@schematics/update                 0.13.3
ng-packagr                         4.7.1
rxjs                               6.4.0
typescript                         3.2.4
webpack                            4.29.0
```

**Comment by kklimczak** [comment]
I noticed the same problem during generating library with config:
```
Angular CLI: 7.2.4
Node: 8.11.3
OS: linux x64
Angular: 7.2.7
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.11.4
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.2.4
@angular-devkit/schematics        7.2.4
@angular/cdk                      7.3.3
@angular/cli                      7.2.4
@angular/material                 7.3.3
@ngtools/webpack                  7.1.4
@schematics/angular               7.3.3
@schematics/update                0.12.4
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.23.1
```

I tried `7.5.1, 7.6.1, 7.6.2` versions of `@nrwl/schematics`.

**Comment by spidermon** [comment]
In our project this issue was reproducible with latest angular cli and nx. Cause of issue was @angular/pwa package or some of 14 derived dependencies. I didn't dig deep enough but workaround is to delete @angular/pwa. Angular CLI with nx working after that as expected.

**Comment by mohyeid** [comment]
I tried all combinations above, and none of them works. Always failing at the e2e step with above errors.

**Comment by agusdutra** [comment]
I was having this issue with `ng generate app` , without any extra config.

After updating schematics and angular cli it worked.

```
@nrwl/schematics@7.6.2
@angular/cli@7.3.5
```

**Comment by gund** [comment]
Can confirm in my project CLI works again after upgrading angular and NX libs.
