### ISSUE TITLE
"nx serve" fails with weird error when project can't be build

### ISSUE THREAD

**Issue by e-oz** [nrwl/nx#11770]
Scope: Angular

## Current Behavior
If project can't be built (`nx build` generates an error), `nx serve` will just stuck with a weird error message (not related to the real issue at all).

## Expected Behavior
Would be nice to see all the stderr output to see the correct error pointing to a real file. Also, would be great if `nx serve` will stop the execution :)

## Steps to Reproduce
1. Create a new Angular workspace;
2. Create a library; 
3. In a library generate a component;
4. Modify path to scss file to make it wrong.
5. Run `nx serve`

### Environment
<details>
<summary>nx report</summary>

   Node : 18.7.0
   OS   : darwin arm64
   yarn : 1.22.17
   
   nx : 14.5.10
   @nrwl/angular : 14.5.10
   @nrwl/cypress : 14.5.10
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.10
   @nrwl/eslint-plugin-nx : 14.5.10
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.10
   @nrwl/js : 14.5.10
   @nrwl/linter : 14.5.10
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.5.4
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.10
   @nrwl/web : 14.5.10
   @nrwl/workspace : 14.5.10
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
         @ngrx/component-store: 14.3.0
         @ngrx/effects: 14.3.0
         @ngrx/store: 14.3.0
         @jefiozie/ngx-aws-deploy: 4.1.0
         @ngrx/eslint-plugin: 14.3.0
         @storybook/angular: 6.5.10
</details>

**Comment by FrozenPandaz** [comment]
Could you provide a repro please? I was not able to reproduce on `14.6.3` or `14.5.10`. 

Here are my logs:

```
jason@pop-os ~/p/t/ng-test (main)> nx serve

> nx run app1:serve:development

✔ Browser application bundle generation complete.

Initial Chunk Files   | Names         |  Raw Size
vendor.js             | vendor        |   1.73 MB | 
polyfills.js          | polyfills     | 317.11 kB | 
styles.css, styles.js | styles        | 209.34 kB | 
main.js               | main          |  46.40 kB | 
runtime.js            | runtime       |   6.51 kB | 

                      | Initial Total |   2.29 MB

Build at: 2022-09-02T18:01:22.844Z - Hash: 633781d6e4bd645d - Time: 1830ms

Error: Module not found: Error: Can't resolve '/home/jason/projects/triage/ng-test/libs/lib1/src/lib/button/button.component.css123123?ngResource' in '/home/jason/projects/triage/ng-test'

Error: The loader "/home/jason/projects/triage/ng-test/libs/lib1/src/lib/button/button.component.css123123" didn't return a string.



** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


✖ Failed to compile.
^C⏎                                                                                                                                                                                 
jason@pop-os ~/p/t/ng-test (main)> nx report

 >  NX   Report complete - copy this into the issue template

   Node : 14.20.0
   OS   : linux x64
   npm  : 6.14.17
   
   nx : 14.5.10
   @nrwl/angular : 14.5.10
   @nrwl/cypress : 14.5.10
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.5.10
   @nrwl/eslint-plugin-nx : 14.5.10
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.10
   @nrwl/js : 14.5.10
   @nrwl/linter : 14.5.10
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : 14.6.1
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.10
   @nrwl/web : 14.5.10
   @nrwl/workspace : 14.5.10
   typescript : 4.7.4
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
 ```

I pushed my repo: https://github.com/FrozenPandaz/nx-bugs/tree/repro-11770
 
 Could you push a repo that we could pull down to reproduce the issue?

**Comment by e-oz** [comment]
In my case it looks different:
```
oz@Avalon npp-ui % nx serve

> nx run npp:serve:development

✔ Browser application bundle generation complete.
<e> [webpack-dev-middleware] Error: ENOENT: no such file or directory, readdir '/Users/oz/repos/scs/npp-ui/dist/apps/npp/'
<e>     at createError (/Users/oz/repos/scs/npp-ui/node_modules/memfs/lib/volume.js:128:17)
<e>     at Volume.readdirBase (/Users/oz/repos/scs/npp-ui/node_modules/memfs/lib/volume.js:1415:19)
<e>     at Immediate.<anonymous> (/Users/oz/repos/scs/npp-ui/node_modules/memfs/lib/volume.js:695:33)
<e>     at process.processImmediate (node:internal/timers:471:21) {
<e>   code: 'ENOENT'
<e> }
```
And then it hangs.

I've tried to reproduce using a newly created workspace - I have the same results as you. It's not cool that it still hangs, but at least the error message is not cryptic.
I'll close it until I can identify the difference between mine and newly created workspace.

**Comment by IbenTesara** [comment]
@e-oz we are running into the exact same issue here, we can upgrade all the way up to 14.5.10, but once we upgrade past it it gives the exact same error. 

If you end up finding what the issue is, we'd love to know so we can use the latest Angular version in our project :)
