### ISSUE TITLE
Angular Cypress Component Testing not applying style correctly

### ISSUE THREAD

**Issue by kanidjar** [nrwl/nx#12113]
## Current Behavior
Mounted component style is not applied correctly

## Expected Behavior
Style should be applied correctly.

**With Angular CLI**

<img width="1076" alt="Capture d’écran 2022-09-20 à 12 08 39" src="https://user-images.githubusercontent.com/12607242/191230794-c67a31db-b7ce-4e7f-9c8a-b5de65aac318.png">

**With NX:**

<img width="400" alt="Capture d’écran 2022-09-20 à 12 07 21" src="https://user-images.githubusercontent.com/12607242/191230517-4c8b7968-a1cd-4b0f-87a2-ab1cf481d0ec.png">

## Steps to Reproduce
https://github.com/kanidjar/nx-cypress-ct-styling-bug

One example with the Angular CLI (working)
Same example with NX (not working)

**With Angular CLI**

````
cypress open
````

<img width="1392" alt="Capture d’écran 2022-09-20 à 12 04 52" src="https://user-images.githubusercontent.com/12607242/191229965-0a4e205a-0e16-4219-90b0-c9035237eccb.png">

***With NX***

````
nx component-test application --watch
````

<img width="1199" alt="Capture d’écran 2022-09-20 à 12 06 10" src="https://user-images.githubusercontent.com/12607242/191230224-81e2a9e3-a018-48b0-8b9e-95816e392c8f.png">

## Env

````bash
 >  NX   Report complete - copy this into the issue template

   Node : 18.7.0
   OS   : darwin arm64
   npm  : 8.15.0
   
   nx : 14.7.6
   @nrwl/angular : 14.7.6
   @nrwl/cypress : 14.7.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.7.6
   @nrwl/eslint-plugin-nx : 14.7.6
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.7.6
   @nrwl/js : 14.7.6
   @nrwl/linter : 14.7.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.7.6
   @nrwl/web : Not Found
   @nrwl/workspace : 14.7.6
   typescript : 4.8.3
   ---------------------------------------
   Local workspace plugins:
   ---------------------------------------
   Community plugins:
````

**Comment by kanidjar** [comment]
hi, we have tried to investigate with no success. This prevents us from using component testing. Do you have any idea?

**Comment by kanidjar** [comment]
hello @barbados-clemens, this bug is completely blocking us from using Cypress CT. Is it possible to take it into account?

**Comment by barbados-clemens** [comment]
I didn't see this issue, but this should have been long and fixed by now. You'll want to retry with the latest nx and cypress versions.

**Comment by kanidjar** [comment]
@barbados-clemens the issue is still there.

````
  Node : 18.12.1
   OS   : darwin arm64
   pnpm : 7.18.1
   
   nx                      : 15.7.2
   @nrwl/jest              : 15.7.2
   @nrwl/linter            : 15.7.2
   @nrwl/workspace         : 15.7.2
   @nrwl/angular           : 15.7.2
   @nrwl/cli               : 15.7.2
   @nrwl/cypress           : 15.7.2
   @nrwl/eslint-plugin-nx  : 15.7.2
   @nrwl/nx-cloud          : 15.1.0
   typescript              : 4.8.4
   ---------------------------------------

**Comment by kanidjar** [comment]
@barbados-clemens i've also updated the example repo to NX 15.7.2

**Comment by barbados-clemens** [comment]
Looks to be something else at play here as styles do load. but the tailwind config is not being processed by angular so there are no tailwind styles.

I'll have to look into what is going on as we explicitly have tailwind being tested in the CT e2e suite 
https://github.com/nrwl/nx/blob/ad26b55672c6877cf87739be0f1618bda96d772f/e2e/angular-extensions/src/cypress-component-tests.test.ts#L274-L295

Even manually forcing the tailwind styles to be added to the project it still doesn't seem to work. my guess is something about being opened in the project root vs workspace root is the issue?

**Comment by barbados-clemens** [comment]
when putting the tailwind config in the project root (i.e. when running the nx g setup-tailwind for the app) it works. but moving the same config to the repo root doesn't work since it seems like the root config is never called by angular executor.
