### ISSUE TITLE
angular pwa install fails

### ISSUE THREAD

**Issue by Kevin-Terblanche** [nrwl/nx#12391]
i have added the pwa with 
`npm install @angular/pwa --save-dev
nx g @angular/pwa:ng-add --project *project-name*`

in my project setup i have a folder structure with a folder apps which has 4 separate applications each having their own index.html and environments etc i want to add pwa support to one of the projects in that structure but i am receiving this error

```
>  NX  Generating @angular/pwa:ng-add

[NX] Angular devkit readJsonWorkspace fell back to Nx workspaces logic
Workspace extension with invalid name (targetDependencies) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
[NX] Angular devkit called `writeWorkspace`, this may have had unintended consequences in angular.json
[NX] Double check angular.json before proceeding
[NX] Angular devkit readJsonWorkspace fell back to Nx workspaces logic
Workspace extension with invalid name (targetDependencies) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
Project extension with invalid name (files) found.
TypeError: this.host.readText is not a function
    at new JSONFile
```

**Comment by Kevin-Terblanche** [comment]
is there any feedback on this issue?

**Comment by Coly010** [comment]
Can you run `nx report` and provide the output of it?

**Comment by Coly010** [comment]
Unfortunately I'm unable to reproduce this issue.

Can you try `nx migrate latest` and `nx migrate --run-migrations` then try this again?

**Comment by Kevin-Terblanche** [comment]
nope still getting the same error. This is my file structure and im trying to add PWA functionality into the project that has the red line next to it

<img width="395" alt="image" src="https://user-images.githubusercontent.com/108672217/194852759-025a966e-5bdf-441e-878e-cf5634c96a0d.png">
<img width="243" alt="image" src="https://user-images.githubusercontent.com/108672217/194852947-43b6079d-c46b-43a8-be4e-f5403cb085ec.png">

**Comment by Coly010** [comment]
Are you able to share the actual repo with me? I'll need it to investigate further as to why this is happening for you.

**Comment by Kevin-Terblanche** [comment]
unfortunately i cant due to security and privacy of the company im not able to give access to the repo itself

**Comment by Coly010** [comment]
Can you create a new minimal repo, that doesn't breach your NDA that replicates the issue?

**Comment by Coly010** [comment]
This should be fixed by https://github.com/nrwl/nx/commit/8c393b5660eba4d8404b8194ff139497aa1636fa 🙂

**Comment by Kevin-Terblanche** [comment]
i pull all the newest changes and was still getting the same error i downgraded my pwa version to @13.3.9 to be compatible with current angular version else the error gets throws where you could try use --legacy-peer-deps to fix so just downgraded the version seems to now go though and not give that same issue any more now sitting with this issue

`>  NX  Generating @angular/pwa:ng-add

[NX] Angular devkit called `writeWorkspace`, this may have had unintended consequences in angular.json
[NX] Double check angular.json before proceeding
SchematicsException [Error]: Could not read file (/apps/spreekuur/src/undefined.ts).

 >  NX   Could not read file (/apps/spreekuur/src/undefined.ts).

   Pass --verbose to see the stacktrace.
`

**Comment by kenatwex** [comment]
Im receiving this today

[NX] Angular devkit called `writeWorkspace`, this may have had unintended consequences in workspace.json
[NX] Double check workspace.json before proceeding
TypeError: this.host.readText is not a function

**Comment by kenatwex** [comment]
unable to generate libraries using NxConsole within webstorm IDE

**Comment by kenatwex** [comment]
My migrations obviously failed prior dont know why but alot has been tripped up with latest migration for me
