### ISSUE TITLE
`nx generate` swallows the -d option for @nrwl/nx-plugin

### ISSUE THREAD

**Issue by adri326** [nrwl/nx#12596]
## Current Behavior

`nx g @nrwl/nx-plugin --help` prints:

```
[--snip--]
    --directory, -d              A directory where the plugin is placed.
[--snip--]
```

However, running `nx g @nrwl/nx-plugin -d my-directory project-name` does **not** put the project in `libs/my-directory/project-name`, and instead does a dry run.

## Expected Behavior

The behavior of `nx g @nrwl/nx-plugin` should match the help message:
- either `-d` shouldn't be listed as an alias of `--directory`, as it is already an alias for `--dry-run`
- or, `nx g @nrwl/nx-plugin -d my-directory` should set the schema parameter to `{directory: "my-directory"}`

## Steps to Reproduce

```
yarn add @nrwl/nx-plugin@latest
nx g @nrwl/nx-plugin -d my-directory project-name
```

### Failure Logs

```
$ nx g @nrwl/nx-plugin:plugin -d my-directory project-name
CREATE libs/my-directory/README.md
CREATE libs/my-directory/package.json
CREATE libs/my-directory/src/index.ts
CREATE libs/my-directory/tsconfig.json
CREATE libs/my-directory/tsconfig.lib.json
CREATE libs/my-directory/.babelrc
CREATE libs/my-directory/project.json
UPDATE workspace.json
UPDATE tsconfig.base.json
CREATE libs/my-directory/.eslintrc.json
UPDATE package.json
CREATE libs/my-directory/jest.config.ts
CREATE libs/my-directory/tsconfig.spec.json
UPDATE jest.config.js
CREATE libs/my-directory/executors.json
CREATE libs/my-directory/generators.json
CREATE libs/my-directory/src/generators/my-directory/files/src/index.ts__template__
CREATE libs/my-directory/src/generators/my-directory/generator.spec.ts
CREATE libs/my-directory/src/generators/my-directory/generator.ts
CREATE libs/my-directory/src/generators/my-directory/schema.d.ts
CREATE libs/my-directory/src/generators/my-directory/schema.json
CREATE libs/my-directory/src/executors/build/executor.spec.ts
CREATE libs/my-directory/src/executors/build/executor.ts
CREATE libs/my-directory/src/executors/build/schema.d.ts
CREATE libs/my-directory/src/executors/build/schema.json
CREATE apps/my-directory-e2e/tests/my-directory.spec.ts
CREATE apps/my-directory-e2e/tsconfig.json
CREATE apps/my-directory-e2e/project.json
CREATE apps/my-directory-e2e/jest.config.ts
CREATE apps/my-directory-e2e/tsconfig.spec.json
UPDATE .eslintrc.json

NOTE: The "dryRun" flag means no changes were made.
```

### Environment

```
   Node : 18.8.0
   OS   : linux x64
   yarn : 1.22.19
   
   nx : 14.0.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.0.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 14.0.5
   @nrwl/eslint-plugin-nx : 14.0.5
   @nrwl/express : Not Found
   @nrwl/jest : 14.0.5
   @nrwl/js : 14.0.5
   @nrwl/linter : 14.0.5
   @nrwl/nest : 14.0.5
   @nrwl/next : 14.0.5
   @nrwl/node : 14.0.5
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 14.8.5
   @nrwl/react : 14.0.5
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.5.4
   @nrwl/web : 14.0.5
   @nrwl/workspace : 14.0.5
   typescript : 4.6.4
   rxjs : 7.5.5
   ---------------------------------------
   Community plugins:
   	@jscutlery/semver: 2.27.1
```

**Comment by FrozenPandaz** [comment]
`-d` should not be an alias for `--directory`. Please use `--directory`. This should be fixed.

**Comment by adri326** [comment]
I still see the [`-d` alias](https://github.com/nrwl/nx/blob/master/packages/nx-plugin/src/generators/plugin/schema.json#L27), so I'm guessing you meant that it should get fixed, not that it should have been fixed already?

This aside, running `rg '"alias": "d"'` yields 30 results, 14 of which are for generators:
- `packages/expo/src/generators/application/schema.json` (alias for `--directory`)
- `packages/expo/src/generators/component/schema.json` (alias for `--directory`)
- `packages/expo/src/generators/library/schema.json` (alias for `--directory`)
- `packages/next/src/generators/application/schema.json` (alias for `--directory`)
- `packages/nx-plugin/src/generators/executor/schema.json` (alias for `--description`)
- `packages/nx-plugin/src/generators/generator/files/generator/__fileName__/schema.json__tmpl__` (seems to be the root of the aliases for `--description`)
- `packages/nx-plugin/src/generators/generator/schema.json` (alias for `--description`)
- `packages/nx-plugin/src/generators/migration/schema.json` (alias for `--description`)
- `packages/nx-plugin/src/generators/plugin/schema.json` (alias for `--directory`)
- `packages/react-native/src/generators/application/schema.json` (alias for `--directory`)
- `packages/react-native/src/generators/component/schema.json` (alias for `--directory`)
- `packages/react-native/src/generators/library/schema.json` (alias for `--directory`)
- `packages/react/src/generators/hook/schema.json` (alias for `--directory`)
