### ISSUE TITLE
running a custom executor results in `invalid type: unit value, expected struct Options`

### ISSUE THREAD

**Issue by cawfeecoder** [nrwl/nx#14239]
### Current Behavior

When running my custom executor within Github actions, I receive the following:
```
Error: invalid type: unit value, expected struct Options
    at module.exports.__wbindgen_error_new (/home/runner/work/services/services/node_modules/@swc/wasm/wasm.js:447:17)
    at null.<anonymous> (wasm://wasm/04d8cac6:1:15049568)
    at null.<anonymous> (wasm://wasm/04d8cac6:1:15246056)
    at null.<anonymous> (wasm://wasm/04d8cac6:1:15422317)
    at null.<anonymous> (wasm://wasm/04d8cac6:1:3787477)
    at null.<anonymous> (wasm://wasm/04d8cac6:1:3535857)
    at null.<anonymous> (wasm://wasm/04d8cac6:1:1[415](https://github.com/Photon-Health/services/actions/runs/3877204930/jobs/6611944782#step:11:416)5640)
    at null.<anonymous> (wasm://wasm/04d8cac6:1:911733)
    at null.<anonymous> (wasm://wasm/04d8cac6:1:2873372)
    at null.<anonymous> (wasm://wasm/04d8cac6:1:2232040)
```

### Expected Behavior

Previously (~5 days ago), this would successfully run. It's important to note, none of my code (including the executor) is using swc as a builder.

### Steps to Reproduce

1. I'm happy to provide the executor and basic code in a separate repository later today.

### Nx Report

```shell
Node : 18.1.0
   OS   : darwin arm64
   npm  : 8.19.2

   nx : 15.4.5
   @nrwl/angular : Not Found
   @nrwl/cypress : Not Found
   @nrwl/detox : Not Found
   @nrwl/devkit : 15.4.5
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 15.4.5
   @nrwl/expo : Not Found
   @nrwl/express : 15.4.5
   @nrwl/jest : 15.4.5
   @nrwl/js : 15.4.5
   @nrwl/linter : 15.4.5
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : 15.4.5
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : 15.4.5
   @nrwl/react : Not Found
   @nrwl/react-native : Not Found
   @nrwl/rollup : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : Not Found
   @nrwl/web : Not Found
   @nrwl/webpack : 15.4.5
   @nrwl/workspace : 15.4.5
   @nrwl/vite : Not Found
   typescript : 4.8.4
   ---------------------------------------
   Local workspace plugins:
   	 @services/executors
   ---------------------------------------
   Community plugins:
   	 @nx-tools/nx-container: 4.0.2
```

### Failure Logs

```shell
Error: invalid type: unit value, expected struct Options
    at module.exports.__wbindgen_error_new (/home/runner/work/services/services/node_modules/@swc/wasm/wasm.js:447:17)
    at null.<anonymous> (wasm://wasm/04d8cac6:1:15049568)
    at null.<anonymous> (wasm://wasm/04d8cac6:1:15246056)
    at null.<anonymous> (wasm://wasm/04d8cac6:1:15422317)
    at null.<anonymous> (wasm://wasm/04d8cac6:1:3787477)
    at null.<anonymous> (wasm://wasm/04d8cac6:1:3535857)
    at null.<anonymous> (wasm://wasm/04d8cac6:1:1[415](https://github.com/Photon-Health/services/actions/runs/3877204930/jobs/6611944782#step:11:416)5640)
    at null.<anonymous> (wasm://wasm/04d8cac6:1:911733)
    at null.<anonymous> (wasm://wasm/04d8cac6:1:2873372)
    at null.<anonymous> (wasm://wasm/04d8cac6:1:2232040)
```

### Additional Information

This was working as of 5 days ago without any changes on my part, so I'm assuming that something changed in Nx dependencies potentially.

**Comment by JoA-MoS** [comment]
I am also experiencing the same issue, I am thinking it has to do with a minor, or patch release of one of the `@swc` packages

**Comment by JoA-MoS** [comment]
Updating the package.json swc dependency to be the same as the nx repos did fix my problem, I may not recommend to everyone this solution but it did fix my issue.

**Comment by jaysoo** [comment]
Can someone setup a minimal repo on GitHub? Or if your repo is public I can check that as well.

Sounds like something specific to the GitHub Actions environment?

**Comment by samwalshnz** [comment]
I have encountered this issue as well now. This is happening in our Azure Pipeline (triggered by Github). Exact same error, and exact same problematic library @swc/wasm.

**Comment by iamhosseindhv** [comment]
> Sounds like something specific to the GitHub Actions environment?


We're experiencing the same issue on AWS CodePipeline. My command fails on CI but works locally. I'll see if I can come up with a minimal reproduction


```
NX   invalid type: unit value, expected struct Options
248 |  
249 |  
250 | Error: invalid type: unit value, expected struct Options
251 | at module.exports.__wbindgen_error_new (/codebuild/output/src072524546/src/git-codecommit.eu-west-1.amazonaws.com/v1/repos/<my_project>/node_modules/@swc/wasm/wasm.js:446:17)
252 | at null.<anonymous> (wasm://wasm/04e11c3a:1:15092237)
253 | at null.<anonymous> (wasm://wasm/04e11c3a:1:15290114)
254 | at null.<anonymous> (wasm://wasm/04e11c3a:1:15471587)
255 | at null.<anonymous> (wasm://wasm/04e11c3a:1:3701202)
256 | at null.<anonymous> (wasm://wasm/04e11c3a:1:3461399)
257 | at null.<anonymous> (wasm://wasm/04e11c3a:1:14197780)
258 | at null.<anonymous> (wasm://wasm/04e11c3a:1:1004605)
259 | at null.<anonymous> (wasm://wasm/04e11c3a:1:2836369)
260 | at null.<anonymous> (wasm://wasm/04e11c3a:1:1596185)
261


```

**Comment by AgentEnder** [comment]
It sounds like this is likely fixed in latest, since we've bumped SWC deps since then. I'm going to close this out.

**Comment by jtw-r** [comment]
I'm only commenting on this in case anyone is still having the same issues I was going through. No need to re-open this thread. I spent a whole 5 hours racking my brain only to get multiple super super super super super cryptic error messages. Maybe that can be improved in the future.

Regardless, even if you don't think you're using SWC, just go ahead and update `@swc/core` and `@swc/wasm` like this thread and [this discussion post](https://github.com/swc-project/swc/discussions/7145) say. I do not depend on them in my monorepo, but installing/updating them, and doing a clean install of npm packages fixed all of my issues. The NX CLI wouldn't even print the version information or output `nx report` for me until I updated these dependencies. Grr I wish this dark magic made sense to me. Really glad I stumbled on this GitHub thread and got it fixed!
