### ISSUE TITLE
enforce-module-boundaries reports some built in NodeJS modules as transitive dependencies

### ISSUE THREAD

**Issue by ilijapuaca** [nrwl/nx#15213]
### Current Behavior

It looks like the rule doesn't handle all of the built-in NodeJS packages correctly:
```
import {basename} from 'path';
```
^ no issues with this import

```
import {Buffer} from 'buffer';
import crypto from 'crypto';
```
^ both of these show the error below
```
Transitive dependencies are not allowed. Only packages defined in the "package.json" can be imported eslint[@nrwl/nx/enforce-module-boundaries]
```

I assume this could be a matter of updating the NodeJS module list somewhere, but I was not able to find the correct place to point to

### Expected Behavior

No error is shown for built in modules

### Steps to Reproduce

1. Enable `@nrwl/nx/enforce-module-boundaries` eslint rule with `banTransitiveDependencies` set to true
2. Lint a file with `import {Buffer} from 'buffer';`

### Nx Report

```shell
Node : 14.21.1
   OS   : darwin x64
   yarn : 3.2.4

   nx                      : 15.8.0-beta.3
   lerna                   : 3.22.1
   @nrwl/linter            : 15.8.0-beta.3
   @nrwl/workspace         : 15.8.0-beta.3
   @nrwl/cli               : 15.8.0-beta.3
   @nrwl/devkit            : 15.8.0-beta.3
   @nrwl/eslint-plugin-nx  : 15.8.0-beta.3
   @nrwl/js                : 15.8.0-beta.3
   @nrwl/tao               : 15.8.0-beta.3
   typescript              : 4.8.4
```

**Comment by ilijapuaca** [comment]
@meeroslav thanks for looking at this. Two notes on the above:
- `crypto` is marked as marked as a transient dependency for me (screenshot down below). `yarn why crypto` does mentioned [this package](https://www.npmjs.com/package/crypto) being a transient dependency of another package, although it is a dependency in a completely different package, but in the same workspace
- When I cmd + click into the `buffer` dependency, it does open [this file](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/node/buffer.d.ts) which suggests that it is in fact importing the built in [buffer module](https://nodejs.org/docs/latest-v14.x/api/buffer.html)

In order to understand how the rule itself works, does it just look up if the package exists in the lock file, but not in the `package.json` for a specific module it is being imported in? Based on the above, there does seem to be a conflict between these dependencies and built in NodeJS packages that are actually what is being imported here, so that logic may not stand correct

<img width="705" alt="Screenshot 2023-03-01 at 02 49 26" src="https://user-images.githubusercontent.com/3406718/222090245-94452aab-bb8f-4fe7-8c8a-4f809b4d07ab.png">

**Comment by meeroslav** [comment]
Hey, @ilijapuaca please try using the latest version 15.8.1, and let me know if `crypto` is still marked as transitive. This issue was fixed recently but I'm not sure which version has that fix.

That buffer link you've shown only shows the type definition, which may not be in sync with the installed package.
Check your `yarn.lock` file if there is an entry for `buffer`. I would expect to see something like this:
```yaml
buffer@npm:^4.3.0:
  version "4.9.2"
  ...

buffer@npm:^5.5.0, buffer@npm:^5.6.0:
  version "5.7.1"
  ...

buffers@npm:~0.1.1:
  version "0.1.1"
  ...
```

When you specify `import { Buffer } from 'buffer'` it will first try to resolve it as an npm package, and only if it's not found then it will check if internal node functionality exists with the given name. That means that installed packages has always priority.

**Comment by ilijapuaca** [comment]
@meeroslav I've updated to `15.8.1` and I'm still seeing `crypto` being marked as transitive. I may need to read up on some of these topics, but to me it seems strange that `import { Buffer } from 'buffer'` (or crypto) would always import a transitive dependency and basically shadow the NodeJS module.

Our intention (and what I do think is going on) is that the NodeJS built in module gets resolved in this case, I'm somewhat able to confirm that for the `crypto` case we are able to import and properly use things documented for the NodeJS `crypto` module, rather than a deprecated placeholder that is this transitive dependency

**Comment by ilijapuaca** [comment]
I think that the solution here is to use prefixed imports (eg. `import { Buffer } from 'node:buffer';`) which are what NodeJS uses in their [official docs](https://nodejs.org/api/buffer.html#buffer)? The best version availability documentation I was able to find was this:
```
In Node.js starting:
v16.0.0, v14.18.0 (ESM import and CommonJS require())
v14.13.1, v12.20.0 (only ESM import)
```

We do run version `14.21.1` and I'm seemingly not able to get that import to work though. I will dig around more and see what comes out of it, but this does seems like a good practice in order to avoid ambiguity around transitive dependencies and built-in module imports
