### ISSUE TITLE
NX 15.9.0 "Unable to load tsconfig-paths workspace libraries may be inaccessible…"

### ISSUE THREAD

**Issue by fbartho** [nrwl/nx#16136]
### Current Behavior

Using NX 15.9.0, in a repo with `tsconfig-paths` installed in `node_modules` running `yarn nx report` gives the following error/warning logs:
```shell
$ yarn nx report | pbcopy
>  NX  Unable to load tsconfig-paths, workspace libraries may be inaccessible.
  - To fix this, install tsconfig-paths with npm/yarn/pnpm
```

We're using `tsconfig-paths` installed in our `package.json`, I don't have `tsconfig-paths` installed globally.
```json
  "tsconfig-paths": "^4.2.0",
```

### Expected Behavior

We expect no warning messages, and we expect NX not to be slower.

### Steps to Reproduce

1. Have a working project on NX <15.9.0 (I can find the exact version if that's important) with no warnings that has `tsconfig-paths` installed in `node_modules`
2. Upgrade to NX 15.9.0
3. run `yarn nx report` notice the unexpected warnings

### Nx Report

```shell
yarn run v1.22.19
$ […snipped…]/node_modules/.bin/nx report

 >  NX   Report complete - copy this into the issue template

   Node : 18.11.0
   OS   : darwin arm64
   yarn : 1.22.19
   
   nx                      : 15.9.0
   @nrwl/js                : 15.9.0
   @nrwl/jest              : 15.9.0
   @nrwl/linter            : 15.9.0
   @nrwl/workspace         : 15.9.0
   @nrwl/cli               : 15.9.0
   @nrwl/devkit            : 15.9.0
   @nrwl/eslint-plugin-nx  : 15.9.0
   @nrwl/express           : 15.9.0
   @nrwl/node              : 15.9.0
   @nrwl/nx-plugin         : 15.9.0
   @nrwl/tao               : 15.9.0
   @nrwl/web               : 15.9.0
   @nrwl/webpack           : 15.9.0
   @nrwl/nx-cloud          : 15.3.3
   typescript              : 4.9.5
   ---------------------------------------
   Local workspace plugins:
   	 @hca/package-generator
```

### Failure Logs

```shell
Already included above
```

### Additional Information

N/A

**Comment by AgentEnder** [comment]
This should be fixed now 🎉

**Comment by benzsuankularb** [comment]
Still happen to me
tsconfig-path@4.2.0 installed

`npx nx report`

```
Node   : 19.6.0
   OS     : darwin arm64
   npm    : 9.4.0
   Hasher : Native
   
   nx                 : 16.0.1
   @nx/js             : 16.0.1
   @nx/jest           : 16.0.1
   @nx/linter         : 16.0.1
   @nx/workspace      : 16.0.1
   @nx/devkit         : 16.0.1
   @nx/eslint-plugin  : 16.0.1
   @nx/express        : 16.0.1
   @nx/node           : 16.0.1
   @nx/plugin         : 16.0.1
   @nrwl/tao          : 16.0.1
   @nx/web            : 16.0.1
   @nx/webpack        : 16.0.1
   nx-cloud           : 16.0.5
   typescript         : 4.9.5
   ---------------------------------------
   Community plugins:
   @nx/eslint-plugin-nx : 16.0.0-beta.1
```
