### ISSUE TITLE
Windows CMD Popup on each save

### ISSUE THREAD

**Issue by jahusa02** [nrwl/nx#16876]
### Current Behavior

Everytime I save a file in VSCode a windows CMD pops up, steals focus and is very annoying.

### Expected Behavior

No CMD Popup on save

### Steps to Reproduce

1. create NX Workspace 
2. open in VSCode
3. Save a file

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.14.0
   OS     : win32 x64
   npm    : 9.3.1
   Hasher : Native

   nx                 : 16.0.1
   @nx/js             : 16.0.1
   @nx/jest           : 16.0.1
   @nx/linter         : 16.0.1
   @nx/workspace      : 16.0.1
   @nx/angular        : 16.0.1
   @nx/cypress        : 16.0.1
   @nx/devkit         : 16.0.1
   @nrwl/devkit       : 15.9.3
   @nx/eslint-plugin  : 16.0.1
   @nx/nest           : 16.0.1
   @nx/node           : 16.0.1
   @nrwl/tao          : 16.0.1
   @nx/webpack        : 16.0.1
   typescript         : 4.9.5
   ---------------------------------------
   Community plugins:
   @nx-tools/nx-container : 4.0.3
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nrwl/devkit@15.9.3

   To fix this, run `nx migrate nx@16.0.1`
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by PointSingularity** [comment]
This has been fixed in the past, but it started happening again.

https://github.com/nrwl/nx/issues/10822#issuecomment-1466003558

The latest version where it doesn't happen for me is 15.8.5.

**Comment by AgentEnder** [comment]
This should be fixed in v16.0.2, or latest.

**Comment by PointSingularity** [comment]
@AgentEnder I still experience the pop-ups even with the latest, but it might only happen if the NC Console is enabled. I will test more tomorrow.

**Comment by PointSingularity** [comment]
Not stale.

**Comment by AgentEnder** [comment]
@PointSingularity are you seeing the behavior that presents on each save, or just when first opening the project?

**Comment by PointSingularity** [comment]
> @PointSingularity are you seeing the behavior that presents on each save, or just when first opening the project?

@AgentEnder So I updated NX to version ```16.2.2```, and now it only happens on start and sometimes when package.json is changed /  when I run ```npm install```, but sadly I can't always reproduce that behavior.

**Comment by AgentEnder** [comment]
Yeah, that sounds like its probably a different issue then. The issue here was fixed, as it was happening on **_every_** save on windows. If you are only seeing the behavior on Nx console, you may need to open an issue on that repo.

**Comment by michaelbromley** [comment]
I don't use Nx console, and after just updating my project to v16.2.2, this issue is back for me. I get popups (often many) on running any command with `yarn nx run ...`

Demo:

https://github.com/nrwl/nx/assets/6275952/92cbf54b-ede2-4f7c-8e61-34b79e466bae

My system info:

- Windows 11 22H2 (build 22621.1702)
- Node v16.19.1 (installed via nvm)
- npm v8.19.3
- yarn v1.22.19

My nx packages:

```
        "@nrwl/eslint-plugin-nx": "16.2.2",
        "@nrwl/tao": "16.2.2",
        "@nx/angular": "16.2.2",
        "@nx/cypress": "16.2.2",
        "@nx/devkit": "16.2.2",
        "@nx/jest": "16.2.2",
        "@nx/js": "16.2.2",
        "@nx/linter": "16.2.2",
        "@nx/node": "^16.2.2",
        "@nx/plugin": "16.2.2",
        "@nx/vite": "16.2.2",
        "@nx/webpack": "^16.2.2",
        "@nx/workspace": "16.2.2",
```
