### ISSUE TITLE
NX16 - can't debug nest applications

### ISSUE THREAD

**Issue by rezoled** [nrwl/nx#17327]
### Current Behavior

When running serve on a NestJS app it doesn't wait to attach to any debug port (previous log messages stating that do not appear).
Even when explicitly setting the configuration:
```
"serve": {
      "executor": "@nx/js:node",
      "defaultConfiguration": "development",
      "inspect": true,
      "port": 9300,
      "options": {
        "buildTarget": "api:build"
      },
      "configurations": {
        "development": {
          "buildTarget": "api:build:development"
        },
        "production": {
          "buildTarget": "api:build:production"
        }
      }
    },
```
And running ```nx serve api``` debug doesn't seem to work:
```
> nx run api:serve:development

[Nest] 4542  - 05/31/2023, 2:26:17 PM     LOG [NestFactory] Starting Nest application...
[Nest] 4542  - 05/31/2023, 2:26:17 PM     LOG [InstanceLoader] AppModule dependencies initialized +28ms
[Nest] 4542  - 05/31/2023, 2:26:17 PM     LOG [RoutesResolver] AppController {/api}: +56ms
[Nest] 4542  - 05/31/2023, 2:26:17 PM     LOG [RouterExplorer] Mapped {/api, GET} route +1ms
[Nest] 4542  - 05/31/2023, 2:26:17 PM     LOG [NestApplication] Nest application successfully started +1ms
[Nest] 4542  - 05/31/2023, 2:26:17 PM     LOG 🚀 Application is running on: http://localhost:3000/api
```

### Expected Behavior

What happened in the previous version:
When running serve a console message stated that the process is waiting for a debugger to attach on a specific URL.

Being able to attach chrome debugger or other to the app.

### GitHub Repo

https://github.com/roypeled/nx16-inspect-bug

### Steps to Reproduce

1. run ```nx serve api```

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.15.0
   OS     : darwin arm64
   npm    : 9.5.0
   Hasher : Native
   
   nx                 : 16.2.2
   @nx/js             : 16.2.2
   @nx/jest           : 16.2.2
   @nx/linter         : 16.2.2
   @nx/workspace      : 16.2.2
   @nx/devkit         : 16.2.2
   @nx/eslint-plugin  : 16.2.2
   @nx/nest           : 16.2.2
   @nx/node           : 16.2.2
   @nrwl/tao          : 16.2.2
   @nx/webpack        : 16.2.2
   typescript         : 5.0.4
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by cwoebker** [comment]
On NX v16.1.4 this still worked for us and when trying to upgrade to Nx v16.2.2 we also encounter this error.

**Comment by richard-thai** [comment]
Looks like this issue has been fixed in version 16.3.0.

**Comment by rezoled** [comment]
Confirmed. Updated to 16.3 and it seems to be working again.

**Comment by DonaldMurillo** [comment]
I am still having this issue. I migrated my project today to Nx 16.3.2 on windows.
