### ISSUE TITLE
expo plugin should use eas cli installed globally

### ISSUE THREAD

**Issue by jer-sen** [nrwl/nx#18005]
### Current Behavior

Plugin uses locally installed `eas-cli` package

### Expected Behavior

Using version installed globally as stated in documentation https://github.com/expo/eas-cli
`expo-doctor` detects types incompatibility if adding `eas-cli` locally.

### Steps to Reproduce

https://github.com/nrwl/nx/blob/601c65241b0f4da45c4946d650359df1582fdd1a/packages/expo/src/executors/update/update.impl.ts#L56

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.16.0
   OS     : win32-x64
   yarn   : 1.22.19

   nx                 : 16.4.0
   @nx/js             : 16.4.0
   @nx/jest           : 16.4.0
   @nx/linter         : 16.4.0
   @nx/workspace      : 16.4.0
   @nx/detox          : 16.4.0
   @nx/devkit         : 16.4.0
   @nx/eslint-plugin  : 16.4.0
   @nx/expo           : 16.4.0
   @nx/node           : 16.4.0
   @nx/react          : 16.4.0
   @nrwl/tao          : 16.4.0
   @nx/web            : 16.4.0
   @nx/webpack        : 16.4.0
   typescript         : 5.1.5
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by xiongemi** [comment]
i think this should be fixed in the pr https://github.com/nrwl/nx/pull/17810. now it is using `require.resolve('eas-cli/bin/run')`. this fix should be included in the next version of nx 16.6.0

**Comment by jer-sen** [comment]
If I'm right `require.resolve('eas-cli/bin/run')` will use local version not the globally installed version...

**Comment by LeoAnt02** [comment]
This is still an issue 

Running command  `npx nx build <expo-project>` 

Give this error 

` >  NX   Cannot find module 'eas-cli/bin/run'` 

Eas convention favor the global install instead of local 

From the official git eas-cli 

> Installing eas-cli to your project dependencies is strongly discouraged because it may cause dependency conflicts that are difficult to debug.

Source : https://github.com/expo/eas-cli

**Comment by LeoAnt02** [comment]
@xiongemi Is there any chance we could re-open https://github.com/nrwl/nx/pull/19290  ?? 
From what I understand it does fix the issue and rely on eas global

**Comment by xiongemi** [comment]
it should be fixed in nx 18.

**Comment by leggomuhgreggo** [comment]
FWIW, I think it's preferable to have it defined within the monorepo's root package.json — so I just reinstalled it after the recent migration removed it. But it's not a big deal either way — can leave it to users' discretion.
