### ISSUE TITLE
`buildLibsFromSource: false` doesn't work with Vite executors when `package.json` has no `exports` field

### ISSUE THREAD

**Issue by ms-tng** [nrwl/nx#18459]
### Current Behavior

Suppose an app `my-app` uses the `@nx/vite:dev-server` executor and depends on a lib `my-lib`. Then when the `buildLibsFromSource` option of the executor is set to `false`, `my-lib` is still built from source within `my-app`.

First of all, this fails because of https://github.com/nrwl/nx/issues/18458, but even after patching that, it still doesn't work.

The reason is that when the new `vite-tsconfig-paths` plugin tries to find the bundled module in the build artifacts of the lib, it first checks for an `exports` field in `package.json`, then for `module` and `main`, see here: https://github.com/nrwl/nx/blob/50a145bb64edcf76985184a9a83d1449dcd4f3d9/packages/vite/plugins/nx-tsconfig-paths.plugin.ts#L36
When there is no `exports` field (which is currently the default for a Rollup build, for example), the check for `exports` throws and the plugin falls back to using the default `tsconfig`, not the `tsconfig.generated.json` pointing at the build artifacts.

### Expected Behavior

`my-lib` is not built from source, but its build artifact is used instead.

### Steps to Reproduce

1. Patch `@nx/vite` to fix https://github.com/nrwl/nx/issues/18458 by replacing `context.targetName` with `'build'` in `executor-utils`
2. Create a Vite app and a lib, where the app depends on the lib
3. Set `"buildLibsFromSource": false` for the `serve` target of the app
4. Build the lib and serve the app
5. Open the app in a browser and observe that the lib is built from its sources

### Nx Report

```shell
Node   : 20.2.0
OS     : win32-x64

@nx/express        : 16.6.0
@nx/node           : 16.6.0
@nx/plugin         : 16.6.0
@nx/react          : 16.6.0
@nx/rollup         : 16.6.0
@nx/storybook      : 16.6.0
@nrwl/tao          : 16.6.0
@nx/vite           : 16.6.0
@nx/web            : 16.6.0
typescript         : 5.1.6
```

### Operating System

- [X] macOS
- [X] Linux
- [X] Windows
- [ ] Other (Please specify)

**Comment by barbados-clemens** [comment]
this _should_ be resolved with https://github.com/nrwl/nx/pull/18477
i still need to do more testing, but basically will allow projects without package.json or export fields to work.

**Comment by ms-tng** [comment]
@barbados-clemens Thanks for the fix!

Unfortunately, the issue persists in Nx 16.8.0. I created another reproducing example at https://github.com/ms-tng/nx-buildlibsfromsource-repro2.

When the lib has an `exports` field, everything works as expected: Setting `"buildLibsFromSource": false` in the app causes the app to use the build artifact of the lib. When there is no `exports` field, however, the lib is built/served from source.

Could you take another look?

**Comment by ms-tng** [comment]
Ok, I figured it out: You can set the `mainFields` option of the `nxViteTsPaths` Vite plugin to something not containing `exports`, e.g.:
```
nxViteTsPaths({
  mainFields: ['module', 'main'],
}),
```
The default setting is `[['exports', '.', 'import'], 'module', 'main']`, which causes the issue when there is no `exports` field.
