### ISSUE TITLE
🐞 bug: prettier 3 error `Invalid host defined options`

### ISSUE THREAD

**Issue by Yberion** [nrwl/nx#18721]
### Current Behavior

When trying to format the code with prettier 3, I'm getting an error (check log below).

I'm not sure if it's related to nx or another package (prettier itselft probably), I found this issue https://github.com/prettier/prettier/issues/15098 & https://github.com/prettier/prettier-vscode/issues/3114 and I'm not able to reproduce on `nx-examples` or another Angular project (using nx as well).

---

### Expected Behavior

Formatting without errors.

---

### GitHub Repo

https://github.com/Yberion/image-utils/tree/feature/prettier3

---

### Steps to Reproduce

1. `pnpm install --no-frozen-lockfile`
2. `pnpm run format`

---

### Nx Report

```shell
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 20.5.0
   OS     : win32-x64
   pnpm   : 8.6.12

   nx                 : 16.8.0-beta.0
   @nx/js             : 16.8.0-beta.0
   @nx/linter         : 16.8.0-beta.0
   @nx/workspace      : 16.8.0-beta.0
   @nx/devkit         : 16.8.0-beta.0
   @nx/esbuild        : 16.8.0-beta.0
   @nx/eslint-plugin  : 16.8.0-beta.0
   @nrwl/tao          : 16.8.0-beta.0
   @nx/vite           : 16.8.0-beta.0
   typescript         : 5.1.6
```

---

### Failure Logs

```shell
E:\Git\myberion\image-utils\node_modules\.pnpm\prettier@3.0.2\node_modules\prettier\index.cjs:600
var prettierPromise = import("./index.mjs");
                      ^

TypeError: Invalid host defined options
    at Object.<anonymous> (E:\Git\myberion\image-utils\node_modules\.pnpm\prettier@3.0.2\node_modules\prettier\index.cjs:600:23)
    at Module._compile (E:\Git\myberion\image-utils\node_modules\.pnpm\v8-compile-cache@2.3.0\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at Mod.require (E:\Git\myberion\image-utils\node_modules\.pnpm\nx@16.8.0-beta.0\node_modules\nx\bin\init-local.js:203:36)
    at require (E:\Git\myberion\image-utils\node_modules\.pnpm\v8-compile-cache@2.3.0\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (E:\Git\myberion\image-utils\node_modules\.pnpm\nx@16.8.0-beta.0\node_modules\nx\src\command-line\format\format.js:10:18)
    at Module._compile (E:\Git\myberion\image-utils\node_modules\.pnpm\v8-compile-cache@2.3.0\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)

Node.js v20.5.0
 ELIFECYCLE  Command failed with exit code 1.
```

---

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

---

**Comment by FaresKi** [comment]
I believe nx is currently not able to work with prettier 3, and thus why it breaks

**Comment by Yberion** [comment]
Hello, it should properly work as of [16.8.0-beta.0](https://github.com/nrwl/nx/releases/tag/16.8.0-beta.0).

**Comment by Suyashtnt** [comment]
> Hello, it should properly work as of [16.8.0-beta.0](https://github.com/nrwl/nx/releases/tag/16.8.0-beta.0).

Upgraded to 16.8.0-beta.2. Still have it
![image](https://github.com/nrwl/nx/assets/45307955/d91b78b2-d0f7-495a-8448-3a77c3947c54)

**Comment by sauldeleon** [comment]
Fails to me as well, latest nrwl and nx and prettier!

**Comment by cereum** [comment]
likewise

**Comment by guysenpai** [comment]
you can set `DISABLE_V8_COMPILE_CACHE` environment variable before execute command

```bash
DISABLE_V8_COMPILE_CACHE=1 nx format:write
```

**Comment by igilham** [comment]
This is not fixed in Nx 16.8.1

```shell
yarn nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 18.12.1
   OS     : darwin-arm64
   yarn   : 3.5.1
   
   nx             : 16.8.1
   @nx/workspace  : 16.8.1
   @nx/devkit     : 16.8.1
   @nrwl/tao      : 16.8.1
   nx-cloud       : 16.4.0
   typescript     : 4.9.5
```

Error

```shell
yarn nx format:check
/Users/ian/code/newsletter/node_modules/prettier/index.cjs:600
var prettierPromise = import("./index.mjs");
                      ^

TypeError: Invalid host defined options
    at Object.<anonymous> (/Users/ian/code/newsletter/node_modules/prettier/index.cjs:600:23)
    at Module._compile (/Users/ian/code/newsletter/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at Mod.require (/Users/ian/code/newsletter/node_modules/nx/bin/init-local.js:203:36)
    at require (/Users/ian/code/newsletter/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/Users/ian/code/newsletter/node_modules/nx/src/command-line/format/format.js:10:18)
    at Module._compile (/Users/ian/code/newsletter/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)

Node.js v18.12.1
```

Prettier and related dependencies:

```json
"prettier": "^3.0.3",
"eslint-plugin-prettier": "^5.0.0",
"eslint-config-prettier": "^9.0.0",
"@trivago/prettier-plugin-sort-imports": "^4.2.0",
"eslint": "^8.44.0",
```

**Comment by khalilou88** [comment]
same error

**Comment by AgentEnder** [comment]
This PR hasn't been released yet, so you'll still get the error. https://github.com/nrwl/nx/pull/19075

**Comment by khalilou88** [comment]
thanks fixed in version 16.9

**Comment by ryanhefner** [comment]
Really? I am still seeing the error in `16.10.0`... Any other potential tricks to fix this one?

**Comment by AgentEnder** [comment]
What command are you running that leads to you hitting the errror?

**Comment by ryanhefner** [comment]
@AgentEnder Just trying to spin up a new `@nx/js` lib.

```
nx g @nx/js:lib types --directory libs/types --bundler rollup
```

**Comment by avalero1985** [comment]
Until it is fixed, I have simply downgraded from prettier to version 2.8.8 and it has worked for me:

```
"devDependencies": {
  ...
  "prettier": "2.8.8",
  ...
},
```
