### ISSUE TITLE
Generating a nestjs app targeting a directory create the e2e project with the wrong name

### ISSUE THREAD

**Issue by carantes** [nrwl/nx#18806]
### Current Behavior

Created a new Nestjs app targeting a directory using the following command

`nx g @nx/nest:app myservice --directory services` 

The new app was bootstrapped correctly inside of the apps/services folder but the e2e app was created with a wrong name: `services-myservice-e2e`.

NX version: v16.7.2``

### Expected Behavior

The e2e app was created in the right folder but with an incorrect name, it should be the same name defined to myservice.

`/apps/services/myservice`

### Steps to Reproduce

1. Create a new NX workspace
`npx create-nx-workspace myworkspace --preset=nest`

2. Create a new NestJS app targeting a directory

`nx g @nx/nest:app myservice --directory services`

### Nx Report

```shell
nx report

 >  NX   Configuration Error

   The following implicitDependencies point to non-existent project(s):
     gateway-e2e
       gateway
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by carantes** [comment]
Also the project name in the `project.json` file was created with the directory appended to it, I had to manually change it.

**Comment by FrozenPandaz** [comment]
I think this was unintentionally fixed by #18701.

Could you check this behavior on `16.8.0-beta.2`?

**Comment by carantes** [comment]
@FrozenPandaz  Tested on`16.8.1` and the issue still happening:

![Screenshot 2023-09-08 at 08 47 59](https://github.com/nrwl/nx/assets/1878740/1c3aa124-620d-46de-a51e-f2965e9d014a)

**Comment by carantes** [comment]
@FrozenPandaz I retested it on `v16.8.1` and it works if you use the full path, including the service name on the --directory flag:

`nx g @nx/nest:app myservice --directory apps/services/myservice`

![Screenshot 2023-09-08 at 09 06 45](https://github.com/nrwl/nx/assets/1878740/8be36bf7-2839-4e20-be26-e609fd3c1927)
