### ISSUE TITLE
ESLint @nrwl/nx/enforce-module-boundaries errors do not show in vscode

### ISSUE THREAD

**Issue by dankurfirst** [nrwl/nx#19878]
### Current Behavior

I have @nrwl/nx/enforce-module-boundaries configured in eslint.json as follows:

`	'@nrwl/nx/enforce-module-boundaries': [
			2,
			{
				allow: [],
				depConstraints: [
					{
						sourceTag: 'new',
						notDependOnLibsWithTags: ['legacy'],
					},
					{
						sourceTag: 'legacy',
						onlyDependOnLibsWithTags: ['*'],
					},
				],
			},
		],`
		
If I violate the rule by importing from 'legacy' into 'new' and run `nx run-many --all --target=lint`, the errors are correctly reported. However, VSCode IDE does not show red squiggly lines as it does for other ESlint errors.

### Expected Behavior

VSCode IDE should show red squiggly lines for imports that violate `@nrwl/nx/enforce-module-boundaries`

### Steps to Reproduce

1. Add the following to `rules` in eslint config file: 

`		'@nrwl/nx/enforce-module-boundaries': [
			2,
			{
				allow: [],
				depConstraints: [
					{
						sourceTag: 'new',
						notDependOnLibsWithTags: ['legacy'],
					},
					{
						sourceTag: 'legacy',
						onlyDependOnLibsWithTags: ['*'],
					},
				],
			},
		],`
		
2. Add `tags: ["legacy"]` to a project.json and `tags: ["new"]` to another project's project.json.
3. Try to import from "legacy" project to "new" project. VSCode does not show red lines, as it does for other eslint errors.

### Nx Report

```shell
nx : 14.8.6
   @nrwl/angular : Not Found
   @nrwl/cypress : 14.8.6
   @nrwl/detox : Not Found
   @nrwl/devkit : 16.9.1
   @nrwl/esbuild : Not Found
   @nrwl/eslint-plugin-nx : 14.8.6
   @nrwl/expo : Not Found
   @nrwl/express : Not Found
   @nrwl/jest : 14.5.4
   @nrwl/js : 14.8.6
   @nrwl/linter : 14.8.6
   @nrwl/nest : Not Found
   @nrwl/next : Not Found
   @nrwl/node : Not Found
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 14.8.6
   @nrwl/react-native : Not Found
   @nrwl/rollup : 14.8.6
   @nrwl/schematics : Not Found
   @nrwl/storybook : 14.8.6
   @nrwl/web : 14.8.6
   @nrwl/webpack : 14.8.6
   @nrwl/workspace : 14.8.6
   typescript : 4.7.4
```

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Using VSCode Microsoft ESLint extension.

**Comment by meeroslav** [comment]
Hi, thank you for reporting this issue.

Based on your `nx report` I can see you are using a very old version of `nx`. Please update to latest version, as the synchronization between VSCode and our `eslint` rule has been fixed in v16 with this PR https://github.com/nrwl/nx/pull/16534

**Comment by dankurfirst** [comment]
@meeroslav thank's for your reply. I succesfully upgraded to 16.0.3 and still having this issue. I don't see red squigglys in vsCode when violating enforce-module-bounadries. Is there a minor version or patch I need to upgrade to still? I have the rule configured as below:

```	rules: {
		'react/jsx-no-useless-fragment': [2, { allowExpressions: true }],
		'@nx/enforce-module-boundaries': [
			2,
			{
				allow: [],
				depConstraints: [
					{
						sourceTag: 'new',
						notDependOnLibsWithTags: ['legacy'],
					},
					{
						sourceTag: 'legacy',
						onlyDependOnLibsWithTags: ['*'],
					},
				],
			},
		],
	},```
