### ISSUE TITLE
nrwl react-native build/archive from xcode fails to start the metro server with 'No Metro config found in "nx workspace root path"

### ISSUE THREAD

**Issue by charithreddyv** [nrwl/nx#21253]
### Current Behavior

When i try to build app to a device/simulator or archive the app using xcode i the build works fine (build succeeds and copied to device and build fails for archive) and also copies and installs the app on device but the metro server does not run throwing an error `"error No Metro config found in /Users/ThisUser/nx-project/" ` but the app is generated at `/Users/ThisUser/nx-project/mobile-app` 

### Expected Behavior

App's build and archive should succeed .

### Steps to Reproduce

1. Generate the app with `npx nx generate @nrwl/react-native:app mobile --directory=apps/mobile`
2. Try to run the app with xcode build or archive 

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 16.14.2
   OS     : darwin-arm64
   npm    : 8.5.0
   
   nx (global)        : 17.2.8
   nx                 : 17.0.1
   @nx/js             : 17.2.8
   @nx/jest           : 17.2.8
   @nx/linter         : 17.0.1
   @nx/eslint         : 17.0.1
   @nx/workspace      : 17.0.1
   @nx/cypress        : 17.0.1
   @nx/detox          : 17.2.8
   @nx/devkit         : 17.0.1
   @nx/eslint-plugin  : 17.0.1
   @nx/expo           : 17.1.3
   @nx/nest           : 17.1.3
   @nx/node           : 17.0.1
   @nx/react          : 17.0.1
   @nx/react-native   : 17.2.8
   @nrwl/tao          : 17.0.1
   @nx/vite           : 17.0.1
   @nx/web            : 17.0.1
   @nx/webpack        : 17.0.1
   typescript         : 5.1.6
   ---------------------------------------
   The following packages should match the installed version of nx
     - @nx/js@17.2.8
     - @nrwl/js@17.2.8
     - @nx/jest@17.2.8
     - @nrwl/jest@17.2.8
     - @nx/detox@17.2.8
     - @nrwl/detox@17.2.8
     - @nx/expo@17.1.3
     - @nrwl/expo@17.1.3
     - @nx/nest@17.1.3
     - @nrwl/nest@17.1.3
     - @nx/react-native@17.2.8
     - @nrwl/react-native@17.2.8
   
   To fix this, run `nx migrate nx@17.2.8`
```

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux
- [ ] Other (Please specify)

**Comment by cosmin5mins** [comment]
The same is happening for us.

**Comment by xiongemi** [comment]
this should be fixed in nx 18. this happens because react native does not support monorepo yet. you have to run `nx start` in the terminal while try to do xcode build.

**Comment by kosiakMD** [comment]
we tried to migrate from 17 -> 18 and still facing this issue by running from Xcode

**Comment by xiongemi** [comment]
@kosiakMD did you upgrade the xcodeproj file?
from the diff: https://react-native-community.github.io/upgrade-helper/?from=0.72.8&to=0.73.4#RnDiffApp-ios-RnDiffApp.xcodeproj-project.pbxproj, there is no longer step "Start Packager", so when running the project from xcode, it should not try to start metro packager.
