### ISSUE TITLE
Module federation dev server static remote copy logic is incorrect.

### ISSUE THREAD

**Issue by statop** [nrwl/nx#21392]
### Current Behavior

If I only have 1 static remote, the federation dev server serves a different directory structure than if I had more than one.

### Expected Behavior

If I only have 1 static remote, the federation dev server serves a the same directory structure than if I had more than one.

### Steps to Reproduce

1. Serve a single static remote that does not have the project name as the name of the output folder.

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 18.17.1
   OS     : darwin-arm64
   pnpm   : 8.14.3

   nx                 : 17.2.8
   @nx/js             : 17.2.8
   @nx/jest           : 17.2.8
   @nx/eslint         : 17.2.8
   @nx/workspace      : 17.2.8
   @nx/angular        : 17.2.8
   @nx/devkit         : 17.2.8
   @nx/eslint-plugin  : 17.2.8
   @nx/node           : 17.2.8
   @nx/plugin         : 17.2.8
   @nx/react          : 17.2.8
   @nx/rollup         : 17.2.8
   @nx/storybook      : 17.2.8
   @nx/vite           : 17.2.8
   @nx/web            : 17.2.8
   @nx/webpack        : 17.2.8
   typescript         : 5.2.2
   ---------------------------------------
   Community plugins:
   @openadp/tools-plugin : 24.5.0
   @storybook/angular    : 7.6.10
   ---------------------------------------
   Local workspace plugins:
   	 @openadp/tools-plugin
```

### Package Manager Version

pnpm  8.14.3

### Operating System

- [X] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

The problematic code is here - https://github.com/nrwl/nx/blob/master/packages/react/src/executors/module-federation-dev-server/module-federation-dev-server.impl.ts#L58

It assumes that all projects output to a folder with the project name. Many projects use a path that matches the path to the project sources.

**Comment by Coly010** [comment]
Hi @statop !

Can you provide an example even just as a comment here of when this occurs and why this is a bug?

We only need to move projects into a common location when there is more than 1 static remote. To allow a single `http-server` to serve all the remotes that are required.

When `module-federation-dev-server` is used, it will point the remotes location to the correct place. 
This only happens during local dev.

Production builds will still use the correct location defined in `module-federation.config` or any overrides provided in `webpack.config.prod`.

**Comment by statop** [comment]
The code here 
https://github.com/nrwl/nx/blob/master/packages/react/src/executors/module-federation-dev-server/module-federation-dev-server.impl.ts#L58
assumes that the parent directory name is the same as the name of the project.

That is not always the case.

**Comment by statop** [comment]
In other words, if the output path for my project, which is named foo-bar, is dist/foo/bar, then the server will serve up the foo directory and try to load resources from a non-existant foo-bar directory

**Comment by Coly010** [comment]
This should be solved by this line, no? 
https://github.com/nrwl/nx/blob/81be1e5419f784b502ced35965b215e10b50d377/packages/react/src/executors/module-federation-dev-server/module-federation-dev-server.impl.ts#L76

I know now how to test this at least

**Comment by statop** [comment]
in the case of more than one static remote, yes.

The problem is when there is only one static remote.

**Comment by statop** [comment]
@Coly010  there is still a problem when the output directory does not contain the whole project name

**Comment by Coly010** [comment]
@statop I cannot reproduce that behaviour on the latest version of Nx. If you can provide a reproduction repo, I'll happily reopen this and take a look.
