### ISSUE TITLE
Inner Error: ReferenceError: structuredClone is not defined

### ISSUE THREAD

**Issue by helloworldcro2050** [nrwl/nx#21477]
### Current Behavior

>>: npx nx run-many -t serve 

>  NX   Unable to create nodes for apps/org/project.json using plugin nx/core/target-defaults.

         Inner Error: ReferenceError: structuredClone is not defined
       at exports.TargetDefaultsPlugin.createNodes (D:\projects\workspace\nx\org\node_modules\nx\src\plugins\target-defaults\target-defaults-plugin.js:54:28)
       at buildProjectsConfigurationsFromProjectPathsAndPlugins (D:\projects\workspace\nx\org\node_modules\nx\src\project-graph\utils\project-configuration-utils.js:146:29)
       at createProjectConfigurations (D:\projects\workspace\nx\org\node_modules\nx\src\project-graph\utils\retrieve-workspace-files.js:89:156)
       at _retrieveProjectConfigurations (D:\projects\workspace\nx\org\node_modules\nx\src\project-graph\utils\retrieve-workspace-files.js:61:12)
       at retrieveProjectConfigurations (D:\projects\workspace\nx\org\node_modules\nx\src\project-graph\utils\retrieve-workspace-files.js:46:12)
       at processTicksAndRejections (node:internal/process/task_queues:96:5)
       at async processFilesAndCreateAndSerializeProjectGraph (D:\projects\workspace\nx\org\node_modules\nx\src\daemon\server\project-graph-incremental-recomputation.js:140:28)
       at async getCachedSerializedProjectGraphPromise (D:\projects\workspace\nx\org\node_modules\nx\src\daemon\server\project-graph-incremental-recomputation.js:43:16)
       at async handleRequestProjectGraph (D:\projects\workspace\nx\org\node_modules\nx\src\daemon\server\handle-request-project-graph.js:12:24)
       at async handleResult (D:\projects\workspace\nx\org\node_modules\nx\src\daemon\server\server.js:110:16)

   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".

### Expected Behavior

run ok.

### Steps to Reproduce

1. command:  npx nx run-many -t serve

### Nx Report

```shell
>  NX   Unable to create nodes for apps/org/project.json using plugin nx/core/target-defaults.


         Inner Error: ReferenceError: structuredClone is not defined
       at exports.TargetDefaultsPlugin.createNodes (D:\projects\workspace\nx\org\node_modules\nx\src\plugins\target-defaults\target-defaults-plugin.js:54:28)
       at buildProjectsConfigurationsFromProjectPathsAndPlugins (D:\projects\workspace\nx\org\node_modules\nx\src\project-graph\utils\project-configuration-utils.js:146:29)
       at createProjectConfigurations (D:\projects\workspace\nx\org\node_modules\nx\src\project-graph\utils\retrieve-workspace-files.js:89:156)
       at _retrieveProjectConfigurations (D:\projects\workspace\nx\org\node_modules\nx\src\project-graph\utils\retrieve-workspace-files.js:61:12)
       at retrieveProjectConfigurations (D:\projects\workspace\nx\org\node_modules\nx\src\project-graph\utils\retrieve-workspace-files.js:46:12)
       at processTicksAndRejections (node:internal/process/task_queues:96:5)
       at async processFilesAndCreateAndSerializeProjectGraph (D:\projects\workspace\nx\org\node_modules\nx\src\daemon\server\project-graph-incremental-recomputation.js:140:28)
       at async getCachedSerializedProjectGraphPromise (D:\projects\workspace\nx\org\node_modules\nx\src\daemon\server\project-graph-incremental-recomputation.js:43:16)
       at async handleRequestProjectGraph (D:\projects\workspace\nx\org\node_modules\nx\src\daemon\server\handle-request-project-graph.js:12:24)
       at async handleResult (D:\projects\workspace\nx\org\node_modules\nx\src\daemon\server\server.js:110:16)

   Because of the error the Nx daemon process has exited. The next Nx command is going to restart the daemon process.
   If the error persists, please run "nx reset".
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

windows10, cmd.

**Comment by Erbenos** [comment]
Same error. Just migrated to NX 17.

```
>  NX   Report complete - copy this into the issue template

   Node   : 20.11.0
   OS     : darwin-arm64
   npm    : 10.2.4
   
   nx                 : 17.3.1
   @nx/js             : 17.3.1
   @nx/jest           : 17.3.1
   @nx/linter         : 17.3.1
   @nx/eslint         : 17.3.1
   @nx/workspace      : 17.3.1
   @nx/angular        : 17.3.1
   @nx/cypress        : 17.3.1
   @nx/devkit         : 17.3.1
   @nx/eslint-plugin  : 17.3.1
   @nx/nest           : 17.3.1
   @nx/node           : 17.3.1
   @nx/plugin         : 17.3.1
   @nx/storybook      : 17.3.1
   @nrwl/tao          : 17.3.1
   @nx/web            : 17.3.1
   @nx/webpack        : 17.3.1
   typescript         : 5.3.3
```

Omitted workplace and community plugins from above.

**Comment by ThoSap** [comment]
Fixed this error by upgrading my NodeJS installation to `v20.11.0`:
```js
$ nx report
>  NX  Falling back to ts-node for local typescript execution. This may be a little slower.
  - To fix this, ensure @swc-node/register and @swc/core have been installed

 >  NX   Report complete - copy this into the issue template

   Node   : 16.19.1
   OS     : win32-x64
   pnpm   : 8.15.1
   
   nx (global)        : 17.3.1
   nx                 : 17.3.1
   @nx/js             : 17.3.1
   @nx/jest           : 17.3.1
   @nx/eslint         : 17.3.1
   @nx/workspace      : 17.3.1
   @nx/angular        : 17.3.1
   @nx/devkit         : 17.3.1
   @nx/esbuild        : 17.3.1
   @nx/eslint-plugin  : 17.3.1
   @nx/playwright     : 17.3.1
   typescript         : 5.3.3
   ---------------------------------------
   Community plugins:
   @ngrx/component       : 17.0.1
   @ngrx/component-store : 17.0.1
   @ngrx/effects         : 17.0.1
   @ngrx/entity          : 17.0.1
   @ngrx/router-store    : 17.0.1
   @ngrx/schematics      : 17.0.1
   @ngrx/store           : 17.0.1
   @ngrx/store-devtools  : 17.0.1
```

**Comment by AgentEnder** [comment]
This is indeed caused by the minimum required node version. Structured clone landed in node 17, so it falls within our supported version range, but its not worth breaking folks for this so I'll update the implementation.

**Comment by Erbenos** [comment]
But that still doesn't explain the behavior I observed - see https://github.com/nrwl/nx/issues/21477#issuecomment-1922251887 and the nvm bit.

**Comment by AgentEnder** [comment]
I can't comment on the nvm setup issue, that comes down to how your environment is configured. If node v20 was running, `structuredClone` would be defined. I'm not sure what would be causing a lower node version to run in your case, but its something we've seen happen when people use different terminals. 

A common case for that would be using nx console to run targets or generators, and then running `nx report` in the integrated terminal

**Comment by Erbenos** [comment]
I see, just wanted to make sure that was taken into consideration, it seems random enough that I ll happily attribute it to something on my end :) Thank you!

**Comment by kpaxton** [comment]
I'm having the same issue and using node 20.11. It's only happening in my CI environment though which is also running Node 20.11.

Mine are only failing on `nx:run-commands` 

this is output from the job:
``` 
node ./tools/scripts/run-many.js docker  1 develop '--registry=host:5001' '--build_date=2024-02-02 18:08:38' '--branch=develop' '--sha=7ace51803be3aea7cbfe057c074b33c08faff2cf' '--tag=develop'
Unable to create nodes for apps/.../project.json using plugin nx/core/target-defaults. 
	 Inner Error: ReferenceError: structuredClone is not defined
    at exports.TargetDefaultsPlugin.createNodes (/builds/uee/uee-ui/node_modules/nx/src/plugins/target-defaults/target-defaults-plugin.js:54:28)
    at buildProjectsConfigurationsFromProjectPathsAndPlugins (/builds/uee/uee-ui/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:146:29)
    at createProjectConfigurations (/builds/uee/uee-ui/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:89:156)
    at _retrieveProjectConfigurations (/builds/uee/uee-ui/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:61:12)
    at retrieveProjectConfigurations (/builds/uee/uee-ui/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:46:12)
    at async buildProjectGraphAndSourceMapsWithoutDaemon (/builds/uee/uee-ui/node_modules/nx/src/project-graph/project-graph.js:71:69)
    at async createProjectGraphAndSourceMapsAsync (/builds/uee/uee-ui/node_modules/nx/src/project-graph/project-graph.js:136:25)
    at async createProjectGraphAsync (/builds/uee/uee-ui/node_modules/nx/src/project-graph/project-graph.js:125:39)
    at async Object.showProjectsHandler (/builds/uee/uee-ui/node_modules/nx/src/command-line/show/show.js:15:17)
```

Here is the custom run-many script that is referenced:
```
// Based off of https://gitlab.com/yannickglt/nx-gitlab-build/-/blob/master/tools/scripts/run-many.js
const execSync = require('child_process').execSync;

const target = process.argv[2];
const jobIndex = Number(process.argv[3]) || 1;
const jobCount = Number(process.argv[4]);
const branchRef = process.argv[5];
const isDevelop = branchRef === 'develop';
const baseSha = isDevelop ? 'origin/develop~1' : 'origin/develop';

const affectedCmd = `npx --yes nx show projects --affected --base=${baseSha} --target=${target} --exclude=*-e2e --exclude=workspace-plugin`;

const affected = execSync(affectedCmd)
  .toString('utf-8')
  .trim()
  .split('\n')
  .filter((val) => !!val);
affected.sort();
const sliceSize = Math.floor(affected.length / jobCount);
const projects =
  jobIndex < jobCount
    ? affected.slice(sliceSize * (jobIndex - 1), sliceSize * jobIndex)
    : affected.slice(sliceSize * (jobIndex - 1));

if (projects.length > 0) {
  execSync(
    `npx nx run-many --target=${target} --projects=${projects.join(
      ','
    )} ${restArgs()}`,
    {
      stdio: [0, 1, 2]
    }
  );
}

function restArgs() {
  return process.argv
    .slice(6)
    .map((a) => `"${a}"`)
    .join(' ');
}
```

Any ideas on how to get around it for now until the new version with the fix is out?

**Comment by AgentEnder** [comment]
The **_only_** way for structuredClone to be undefined here is if Nx is being ran in an older node version. The fix would be to ensure that the `npx` command or similar isn't pulling an older node version in.

**Comment by kpaxton** [comment]
Good call. I'm an idiot, I was using another image for the docker portion. That seems to be installing node 16. Thanks!
