### ISSUE TITLE
Serving a scaffolded Remix project in 18.0.3 is broken

### ISSUE THREAD

**Issue by Nvveen** [nrwl/nx#21714]
### Current Behavior

I have created a newly scaffolded Remix project, using the latest (today) version of 18.0.3, since it added Playwright support. I starteed with an empty Nx project, added the remix plugin and then created a Remix app with the new Playwright commandline flag. When trying to serve or build the project, however, the CLI crashes.

### Expected Behavior

For the new project to serve the hello world Remix application without crashing.

### GitHub Repo

https://github.com/Nvveen/playwright-crash-repro

### Steps to Reproduce

1. `pnpm dlx create-nx-workspace --pm pnpm`                 

```
 >  NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Where would you like to create your workspace? · playwright-crash-repro
✔ Which stack do you want to use? · none
✔ Package-based monorepo, integrated monorepo, or standalone project? · package-based
✔ Set up CI with caching, distribution and test deflaking · skip
✔ Would you like remote caching to make your build faster? · skip
```

2. `pnpm dlx nx add @nx/remix`
3. `pnpm dlx nx g @nx/remix:app --directory=apps/front --e2eTestRunner=playwright`
```
>  NX  Generating @nx/remix:application

✔ What is the name of the application? · front
✔ What unit test runner should be used? · vitest
✔ What should be the project name and where should it be generated? · front @ apps/front
Fetching @nx/vite...
Fetching @nx/playwright...
UPDATE nx.json
... (shortened for brevity)
```
4. `pnpm nx run front:serve`

### Nx Report

```shell
>  NX   Report complete - copy this into the issue template

   Node   : 20.11.0
   OS     : linux-x64
   pnpm   : 8.14.1
   
   nx                 : 18.0.3
   @nx/js             : 18.0.3
   @nx/linter         : 18.0.3
   @nx/eslint         : 18.0.3
   @nx/workspace      : 18.0.3
   @nx/devkit         : 18.0.3
   @nx/eslint-plugin  : 18.0.3
   @nx/playwright     : 18.0.3
   @nx/react          : 18.0.3
   @nx/remix          : 18.0.3
   @nrwl/tao          : 18.0.3
   @nx/vite           : 18.0.3
   @nx/web            : 18.0.3
   typescript         : 5.3.3
```

### Failure Logs

```shell
> nx run front:serve


 💿  remix dev

Unable to create nodes for apps/front-e2e/playwright.config.ts using plugin @nx/playwright/plugin. 

         Inner Error: Error: ENOENT: no such file or directory, scandir 'apps/front-e2e'
    at readdirSync (node:fs:1515:26)
    at exports.createNodes (/workspaces/playwright-crash-repro/node_modules/.pnpm/@nx+playwright@18.0.3_@playwright+test@1.41.2_@swc-node+register@1.6.8_@swc+core@1.3.107_@typ_ux2zmy6kcfpob67qhjynyuo7jq/node_modules/@nx/playwright/src/plugins/plugin.js:33:51)
    at buildProjectsConfigurationsFromProjectPathsAndPlugins (/workspaces/playwright-crash-repro/node_modules/.pnpm/nx@18.0.3_@swc-node+register@1.6.8_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:148:29)
    at createProjectConfigurations (/workspaces/playwright-crash-repro/node_modules/.pnpm/nx@18.0.3_@swc-node+register@1.6.8_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:89:156)
    at _retrieveProjectConfigurations (/workspaces/playwright-crash-repro/node_modules/.pnpm/nx@18.0.3_@swc-node+register@1.6.8_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:61:12)
    at retrieveProjectConfigurations (/workspaces/playwright-crash-repro/node_modules/.pnpm/nx@18.0.3_@swc-node+register@1.6.8_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:46:12)
    at async buildProjectGraphAndSourceMapsWithoutDaemon (/workspaces/playwright-crash-repro/node_modules/.pnpm/nx@18.0.3_@swc-node+register@1.6.8_@swc+core@1.3.107/node_modules/nx/src/project-graph/project-graph.js:71:69)
    at async createProjectGraphAndSourceMapsAsync (/workspaces/playwright-crash-repro/node_modules/.pnpm/nx@18.0.3_@swc-node+register@1.6.8_@swc+core@1.3.107/node_modules/nx/src/project-graph/project-graph.js:136:25)
    at async createProjectGraphAsync (/workspaces/playwright-crash-repro/node_modules/.pnpm/nx@18.0.3_@swc-node+register@1.6.8_@swc+core@1.3.107/node_modules/nx/src/project-graph/project-graph.js:125:39)
    at async createWatchPaths (/workspaces/playwright-crash-repro/node_modules/.pnpm/@nx+remix@18.0.3_@swc-node+register@1.6.8_@swc+core@1.3.107_@types+node@20.11.16_nx@18.0.3_typescript@5.3.3/node_modules/@nx/remix/src/utils/create-watch-paths.js:14:19)
CreateNodesError: Unable to create nodes for apps/front-e2e/playwright.config.ts using plugin @nx/playwright/plugin. 

         Inner Error: Error: ENOENT: no such file or directory, scandir 'apps/front-e2e'
    at readdirSync (node:fs:1515:26)
    at exports.createNodes (/workspaces/playwright-crash-repro/node_modules/.pnpm/@nx+playwright@18.0.3_@playwright+test@1.41.2_@swc-node+register@1.6.8_@swc+core@1.3.107_@typ_ux2zmy6kcfpob67qhjynyuo7jq/node_modules/@nx/playwright/src/plugins/plugin.js:33:51)
    at buildProjectsConfigurationsFromProjectPathsAndPlugins (/workspaces/playwright-crash-repro/node_modules/.pnpm/nx@18.0.3_@swc-node+register@1.6.8_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:148:29)
    at createProjectConfigurations (/workspaces/playwright-crash-repro/node_modules/.pnpm/nx@18.0.3_@swc-node+register@1.6.8_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:89:156)
    at _retrieveProjectConfigurations (/workspaces/playwright-crash-repro/node_modules/.pnpm/nx@18.0.3_@swc-node+register@1.6.8_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:61:12)
    at retrieveProjectConfigurations (/workspaces/playwright-crash-repro/node_modules/.pnpm/nx@18.0.3_@swc-node+register@1.6.8_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:46:12)
    at async buildProjectGraphAndSourceMapsWithoutDaemon (/workspaces/playwright-crash-repro/node_modules/.pnpm/nx@18.0.3_@swc-node+register@1.6.8_@swc+core@1.3.107/node_modules/nx/src/project-graph/project-graph.js:71:69)
    at async createProjectGraphAndSourceMapsAsync (/workspaces/playwright-crash-repro/node_modules/.pnpm/nx@18.0.3_@swc-node+register@1.6.8_@swc+core@1.3.107/node_modules/nx/src/project-graph/project-graph.js:136:25)
    at async createProjectGraphAsync (/workspaces/playwright-crash-repro/node_modules/.pnpm/nx@18.0.3_@swc-node+register@1.6.8_@swc+core@1.3.107/node_modules/nx/src/project-graph/project-graph.js:125:39)
    at async createWatchPaths (/workspaces/playwright-crash-repro/node_modules/.pnpm/@nx+remix@18.0.3_@swc-node+register@1.6.8_@swc+core@1.3.107_@types+node@20.11.16_nx@18.0.3_typescript@5.3.3/node_modules/@nx/remix/src/utils/create-watch-paths.js:14:19)
    at /workspaces/playwright-crash-repro/node_modules/.pnpm/nx@18.0.3_@swc-node+register@1.6.8_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:156:35
    at async Promise.all (index 0)
    at async Promise.all (index 4)
    at async createProjectConfigurations (/workspaces/playwright-crash-repro/node_modules/.pnpm/nx@18.0.3_@swc-node+register@1.6.8_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:89:62) {
  [cause]: Error: ENOENT: no such file or directory, scandir 'apps/front-e2e'
      at readdirSync (node:fs:1515:26)
      at exports.createNodes (/workspaces/playwright-crash-repro/node_modules/.pnpm/@nx+playwright@18.0.3_@playwright+test@1.41.2_@swc-node+register@1.6.8_@swc+core@1.3.107_@typ_ux2zmy6kcfpob67qhjynyuo7jq/node_modules/@nx/playwright/src/plugins/plugin.js:33:51)
      at buildProjectsConfigurationsFromProjectPathsAndPlugins (/workspaces/playwright-crash-repro/node_modules/.pnpm/nx@18.0.3_@swc-node+register@1.6.8_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:148:29)
      at createProjectConfigurations (/workspaces/playwright-crash-repro/node_modules/.pnpm/nx@18.0.3_@swc-node+register@1.6.8_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:89:156)
      at _retrieveProjectConfigurations (/workspaces/playwright-crash-repro/node_modules/.pnpm/nx@18.0.3_@swc-node+register@1.6.8_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:61:12)
      at retrieveProjectConfigurations (/workspaces/playwright-crash-repro/node_modules/.pnpm/nx@18.0.3_@swc-node+register@1.6.8_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:46:12)
      at async buildProjectGraphAndSourceMapsWithoutDaemon (/workspaces/playwright-crash-repro/node_modules/.pnpm/nx@18.0.3_@swc-node+register@1.6.8_@swc+core@1.3.107/node_modules/nx/src/project-graph/project-graph.js:71:69)
      at async createProjectGraphAndSourceMapsAsync (/workspaces/playwright-crash-repro/node_modules/.pnpm/nx@18.0.3_@swc-node+register@1.6.8_@swc+core@1.3.107/node_modules/nx/src/project-graph/project-graph.js:136:25)
      at async createProjectGraphAsync (/workspaces/playwright-crash-repro/node_modules/.pnpm/nx@18.0.3_@swc-node+register@1.6.8_@swc+core@1.3.107/node_modules/nx/src/project-graph/project-graph.js:125:39)
      at async createWatchPaths (/workspaces/playwright-crash-repro/node_modules/.pnpm/@nx+remix@18.0.3_@swc-node+register@1.6.8_@swc+core@1.3.107_@types+node@20.11.16_nx@18.0.3_typescript@5.3.3/node_modules/@nx/remix/src/utils/create-watch-paths.js:14:19) {
    errno: -2,
    code: 'ENOENT',
    syscall: 'scandir',
    path: 'apps/front-e2e'
  }
}

 >  NX   Remix app exited with code 1

   Pass --verbose to see the stacktrace.


 —————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Running target serve for project front failed

   Failed tasks:
   
   - front:serve
   
   Hint: run the command with --verbose for more details.
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [X] Other (Please specify)

### Additional Information

This might be important: I am working inside of a devcontainer and have reproduced it in the repo above using github codespaces.

**Comment by Nvveen** [comment]
Found the issue:
https://github.com/nrwl/nx/blob/a0e4cf747d7aeb9cd7c8d2b681e7c3fb353abb19/packages/playwright/src/plugins/plugin.ts#L68

Changing this line as a test to `process.cwd()` and it works. I'm not sure about the rest of the code, but it seems the `projectRoot` doesn't actually get set to the root of the project, but rather to the path to the directory containing `playwright.config.ts`.

**Comment by Coly010** [comment]
Thanks for taking a look already, I'll investigate deeper based on what you've provided! :)

**Comment by Nvveen** [comment]
You can actually edit the line above in `node_modules` as a temporary fix. Replace `projectRoot` with `process.cwd()`.

**Comment by SebasG22** [comment]
@Nvveen it works fine for me locally without any adjustments, but it fails to work on Cloudflare Pages or GitHub Actions (CI), where I lack control over the `node_modules`.

**Comment by Coly010** [comment]
Hey :) 
Can you retry this with the latest version of Nx?

I couldn't reproduce this with `nx@18.0.4`.

Here's a copy of my Nx Report just so you can see :)

```
nx report

 >  NX   Report complete - copy this into the issue template

   Node   : 20.11.0
   OS     : darwin-arm64
   pnpm   : 8.15.2

   nx (global)        : 18.0.4
   nx                 : 18.0.4
   @nx/js             : 18.0.4
   @nx/eslint         : 18.0.4
   @nx/devkit         : 18.0.4
   @nx/eslint-plugin  : 18.0.4
   @nx/playwright     : 18.0.4
   @nx/remix          : 18.0.4
   @nx/vite           : 18.0.4
   @nx/web            : 18.0.4
   typescript         : 5.3.3
```

**Comment by supernaut** [comment]
@Coly010 I get the same error with `nx@18.0.4`.

**Comment by supernaut** [comment]
Anonymized due to client work, but will try to reproduce in a repo:

Postinstall scripts fail in Github Actions, but work locally. Node and pnpm used with exact matching versions locally and in ci.

```
.../node_modules/nx postinstall: Unable to create nodes for pnpm-lock.yaml using plugin nx/js/dependencies-and-lockfile. 
.../node_modules/nx postinstall: 	 Inner Error: Error: Could not find ".modules.yaml" at "/home/runner/work/project/project/node_modules/.modules.yaml"
.../node_modules/nx postinstall:     at loadPnpmHoistedDepsDefinition (/home/runner/work/project/project/node_modules/.pnpm/nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/plugins/js/lock-file/utils/pnpm-normalizer.js:23:15)
.../node_modules/nx postinstall:     at getNodes (/home/runner/work/project/project/node_modules/.pnpm/nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/plugins/js/lock-file/pnpm-parser.js:69:77)
.../node_modules/nx postinstall:     at getPnpmLockfileNodes (/home/runner/work/project/project/node_modules/.pnpm/nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/plugins/js/lock-file/pnpm-parser.js:27:12)
.../node_modules/nx postinstall:     at getLockFileNodes (/home/runner/work/project/project/node_modules/.pnpm/nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/plugins/js/lock-file/lock-file.js:36:59)
.../node_modules/nx postinstall:     at exports.createNodes (/home/runner/work/project/project/node_modules/.pnpm/nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/plugins/js/index.js:42:64)
.../node_modules/nx postinstall:     at buildProjectsConfigurationsFromProjectPathsAndPlugins (/home/runner/work/project/project/node_modules/.pnpm/nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:148:29)
.../node_modules/nx postinstall:     at createProjectConfigurations (/home/runner/work/project/project/node_modules/.pnpm/nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:89:156)
.../node_modules/nx postinstall:     at _retrieveProjectConfigurations (/home/runner/work/project/project/node_modules/.pnpm/nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:61:12)
.../node_modules/nx postinstall:     at retrieveProjectConfigurations (/home/runner/work/project/project/node_modules/.pnpm/nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:46:12)
.../node_modules/nx postinstall:     at async buildProjectGraphAndSourceMapsWithoutDaemon (/home/runner/work/project/project/node_modules/.pnpm/nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/project-graph/project-graph.js:71:69)
.../node_modules/nx postinstall: Unable to create nodes for apps/next-app/playwright.config.ts using plugin @nx/playwright/plugin. 
.../node_modules/nx postinstall: 	 Inner Error: Error: ENOENT: no such file or directory, scandir 'apps/next-app'
.../node_modules/nx postinstall:     at readdirSync (node:fs:1515:26)
.../node_modules/nx postinstall:     at exports.createNodes (/home/runner/work/project/project/node_modules/.pnpm/@nx+playwright@18.0.4_@playwright+test@1.41.2_@swc-node+register@1.8.0_@swc+core@1.3.107_@typ_3om4g7g466ngcx6j4dyl6hei2y/node_modules/@nx/playwright/src/plugins/plugin.js:33:51)
.../node_modules/nx postinstall:     at buildProjectsConfigurationsFromProjectPathsAndPlugins (/home/runner/work/project/project/node_modules/.pnpm/nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:148:29)
.../node_modules/nx postinstall:     at createProjectConfigurations (/home/runner/work/project/project/node_modules/.pnpm/nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:89:156)
.../node_modules/nx postinstall:     at _retrieveProjectConfigurations (/home/runner/work/project/project/node_modules/.pnpm/nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:61:12)
.../node_modules/nx postinstall:     at retrieveProjectConfigurations (/home/runner/work/project/project/node_modules/.pnpm/nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:46:12)
.../node_modules/nx postinstall:     at async buildProjectGraphAndSourceMapsWithoutDaemon (/home/runner/work/project/project/node_modules/.pnpm/nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/project-graph/project-graph.js:71:69)
.../node_modules/nx postinstall: /home/runner/work/project/project/node_modules/.pnpm/nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:156
.../node_modules/nx postinstall:                             throw new CreateNodesError(`Unable to create nodes for ${file} using plugin ${plugin.name}.`, e);
.../node_modules/nx postinstall:                                   ^
.../node_modules/nx postinstall: CreateNodesError: Unable to create nodes for apps/next-app/playwright.config.ts using plugin @nx/playwright/plugin. 
.../node_modules/nx postinstall: 	 Inner Error: Error: ENOENT: no such file or directory, scandir 'apps/next-app'
.../node_modules/nx postinstall:     at readdirSync (node:fs:1515:26)
.../node_modules/nx postinstall:     at exports.createNodes (/home/runner/work/project/project/node_modules/.pnpm/@nx+playwright@18.0.4_@playwright+test@1.41.2_@swc-node+register@1.8.0_@swc+core@1.3.107_@typ_3om4g7g466ngcx6j4dyl6hei2y/node_modules/@nx/playwright/src/plugins/plugin.js:33:51)
.../node_modules/nx postinstall:     at buildProjectsConfigurationsFromProjectPathsAndPlugins (/home/runner/work/project/project/node_modules/.pnpm/nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:148:29)
.../node_modules/nx postinstall:     at createProjectConfigurations (/home/runner/work/project/project/node_modules/.pnpm/nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:89:156)
.../node_modules/nx postinstall:     at _retrieveProjectConfigurations (/home/runner/work/project/project/node_modules/.pnpm/nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:61:12)
.../node_modules/nx postinstall:     at retrieveProjectConfigurations (/home/runner/work/project/project/node_modules/.pnpm/nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:46:12)
.../node_modules/nx postinstall:     at async buildProjectGraphAndSourceMapsWithoutDaemon (/home/runner/work/project/project/node_modules/.pnpm/nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/project-graph/project-graph.js:71:69)
.../node_modules/nx postinstall:     at /home/runner/work/project/project/node_modules/.pnpm/nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:156:35
.../node_modules/nx postinstall:     at async Promise.all (index 0) {
.../node_modules/nx postinstall:   [cause]: Error: ENOENT: no such file or directory, scandir 'apps/next-app'
.../node_modules/nx postinstall:       at readdirSync (node:fs:1515:26)
.../node_modules/nx postinstall:       at exports.createNodes (/home/runner/work/project/project/node_modules/.pnpm/@nx+playwright@18.0.4_@playwright+test@1.41.2_@swc-node+register@1.8.0_@swc+core@1.3.107_@typ_3om4g7g466ngcx6j4dyl6hei2y/node_modules/@nx/playwright/src/plugins/plugin.js:33:51)
.../node_modules/nx postinstall:       at buildProjectsConfigurationsFromProjectPathsAndPlugins (/home/runner/work/project/project/node_modules/.pnpm/nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/project-configuration-utils.js:148:29)
.../node_modules/nx postinstall:       at createProjectConfigurations (/home/runner/work/project/project/node_modules/.pnpm/nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:89:156)
.../node_modules/nx postinstall:       at _retrieveProjectConfigurations (/home/runner/work/project/project/node_modules/.pnpm/nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:61:12)
.../node_modules/nx postinstall:       at retrieveProjectConfigurations (/home/runner/work/project/project/node_modules/.pnpm/nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/project-graph/utils/retrieve-workspace-files.js:46:12)
.../node_modules/nx postinstall:       at async buildProjectGraphAndSourceMapsWithoutDaemon (/home/runner/work/project/project/node_modules/.pnpm/nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107/node_modules/nx/src/project-graph/project-graph.js:71:69) {
.../node_modules/nx postinstall:     errno: -2,
.../node_modules/nx postinstall:     code: 'ENOENT',
.../node_modules/nx postinstall:     syscall: 'scandir',
.../node_modules/nx postinstall:     path: 'apps/next-app'
.../node_modules/nx postinstall:   }
.../node_modules/nx postinstall: }
.../node_modules/nx postinstall: Node.js v20.11.0
.../node_modules/nx postinstall: Failed
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```

**Comment by supernaut** [comment]
Reproduced here: https://github.com/supernaut/nx18-next-playwright/actions/runs/7917010202/job/21612157572

**Comment by Coly010** [comment]
@supernaut That is a separate issue and a separate error, please keep this issue focused on Remix.

I see you have already created an issue regarding your problem here:  https://github.com/nrwl/nx/issues/21823

Let's keep your conversation there.

**Comment by Coly010** [comment]
@Nvveen If you delete your `pnpm-lock.yaml` and `node_modules` and do a fresh `pnpm i`. This should work.
I tried it out on your reproduction repo and can confirm it.

@martialanouman Can you provide try the above? Otherwise, could you provide me with a reproduction repo?

**Comment by martialanouman** [comment]
Hi @Coly010 ,
It works now. Thanks.

But there are some typing errors related to vitest#test fn (though vitest/globals are setup) and missing React import

**Comment by Coly010** [comment]
@martialanouman 

I see the issue, if you open the `tsconfig.spec.json` at the root of your remix project, you may see an `include` and `includes`.

You need to remove the first `include` and rename the `includes` to `include`.

This should fix the issue.

I'll also create a PR to fix this in the generation.

**Comment by martialanouman** [comment]
It works @Coly010.

Thanks

**Comment by binaryartifex** [comment]
The nx-console extension for vscode is still crashing with the following error when trying to initialize when i have a squeaky clean fresh install of a remix app. I also already made the quick change that @Coly010 recommended

```bash
[Nxls] - 2024-02-22T09:29:03.532Z - Error: Unable to create nodes for apps/remix-app/remix.config.js using plugin @nx/remix/plugin. 

	 Inner Error: Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only URLs with a scheme in: file, data, and node are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'f:'
    at new NodeError (node:internal/errors:405:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/load:131:11)
    at defaultLoad (node:internal/modules/esm/load:82:3)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:603:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:64:26)
    at #createModuleJob (node:internal/modules/esm/loader:480:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at F:\projects\issues\test-suite\node_modules\.pnpm\nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107\node_modules\nx\src\project-graph\utils\project-configuration-utils.js:156:35
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async Promise.all (index 3)
    at async createProjectConfigurations (F:\projects\issues\test-suite\node_modules\.pnpm\nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107\node_modules\nx\src\project-graph\utils\retrieve-workspace-files.js:89:62)
    at async processFilesAndCreateAndSerializeProjectGraph (F:\projects\issues\test-suite\node_modules\.pnpm\nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107\node_modules\nx\src\daemon\server\project-graph-incremental-recomputation.js:140:28)
    at async getCachedSerializedProjectGraphPromise (F:\projects\issues\test-suite\node_modules\.pnpm\nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107\node_modules\nx\src\daemon\server\project-graph-incremental-recomputation.js:43:16)
    at async handleRequestProjectGraph (F:\projects\issues\test-suite\node_modules\.pnpm\nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107\node_modules\nx\src\daemon\server\handle-request-project-graph.js:12:24)
    at async handleResult (F:\projects\issues\test-suite\node_modules\.pnpm\nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107\node_modules\nx\src\daemon\server\server.js:110:16)
    at async handleMessage (F:\projects\issues\test-suite\node_modules\.pnpm\nx@18.0.4_@swc-node+register@1.8.0_@swc+core@1.3.107\node_modules\nx\src\daemon\server\server.js:81:9)
```
