### ISSUE TITLE
arrow keys doesn't work when using enquirer to prompt user for selection in a nx executor

### ISSUE THREAD

**Issue by vorlonbuster** [nrwl/nx#22506]
### Current Behavior

Not possible to go up and down in choice list using arrow keys

### Expected Behavior

To navigate up and down in choice list using arrow keys

### GitHub Repo

https://github.com/vorlonbuster/nx-examples

### Steps to Reproduce

Either
1. Clone `https://github.com/vorlonbuster/nx-examples`
2. Execute  `nx run cart:echo` to see navigation key **not working**
3. Execute `nx g my-generator` to see navigation key working (it works in generators, not in executors)

Or
1. Generate a simple executor as described [here](https://nx.dev/extending-nx/recipes/local-executors)
2. install enquirer: `npm install enquirer --save-dev`
4. Copy this code into the generated executor.ts file

```
import { EchoExecutorSchema } from './schema';
import * as enquirer from 'enquirer';

export default async function runExecutor(options: EchoExecutorSchema) {

  const r = await enquirer.prompt<{
    workspaceType: 'standalone' | 'integrated';
  }>([
    {
      type: 'autocomplete',
      name: 'workspaceType',
      message: `Integrated monorepo, or standalone project?`,
      initial: 1,
      choices: [
        {
          name: 'integrated',
          message:
            'Integrated Monorepo:  Nx creates a monorepo that contains multiple projects.',
        },
        {
          name: 'standalone',
          message:
            'Standalone:           Nx creates a single project and makes it fast.',
        },
      ],
    },
  ])

  console.log('Result', r);

  return {
    success: true,
  };
}
```
5. run executor
![image](https://github.com/nrwl/nx/assets/18207132/1478419b-161f-45fe-a766-07ad97c6806f)
Not possible to move cursor up using arrow-up

### Nx Report

```shell
NX   Report complete - copy this into the issue template
                                                         
Node   : 18.16.0                                         
OS     : win32-x64                                       
pnpm   : 8.15.4                                          
                                                         
nx (global)        : 18.1.3                              
nx                 : 18.1.3                              
@nx/js             : 18.1.3                              
@nx/jest           : 18.1.3                              
@nx/eslint         : 18.1.3                              
@nx/workspace      : 18.1.3                              
@nx/angular        : 18.1.3                              
@nx/devkit         : 18.1.3                              
@nx/eslint-plugin  : 18.1.3                              
@nx/plugin         : 18.1.3                              
typescript         : 5.3.2                               
---------------------------------------                  
Local workspace plugins:                                 
         @apics-web/plugins/test                         
         @apics-web/my-plugin
```

### Operating System

- [ ] macOS
- [ ] Linux
- [X] Windows
- [ ] Other (Please specify)

### Additional Information

Using enquirer in nx generators works just fine.

**Comment by FrozenPandaz** [comment]
This should work now. I could not reproduce on Linux.

It's possible this is only on Windows. :thinking:

**Comment by vorlonbuster** [comment]
Ok. We only use Windows at our workplace. Any chance you can test on Windows? We rely on excecutors so we’re stuck on nx version 17 until I find a solution/workaround for this issue.

**Comment by vorlonbuster** [comment]
Hi.
Just tested with nx version 18.3.3. Still doesn't work on windows. Any chance you'r looking into this soon @AgentEnder?

**Comment by theonetheycallneo** [comment]
I notice the same but on Mac
