### ISSUE TITLE
nx lint does not accept --files option

### ISSUE THREAD

**Issue by zaverden** [nrwl/nx#2301]
## Expected Behavior

[According documentation](https://github.com/nrwl/nx/blob/master/docs/web/api-linter/builders/lint.md#files) `nx lint` should accept `--files` array like
```
nx lint --files=apps/main-app/src/main.tsx
```

## Current Behavior

Command fails to parse `--files=apps/main-app/src/main.tsx`

## Failure Information (for bugs)

```
Schema validation failed with the following errors:
  Data path ".files" should be array.
```

### Steps to Reproduce

No special preparations required. Just run command in nx workspace.
```
yarn nx lint --files=apps/main-app/src/main.tsx
```

### Context

```
$ nx report

>  NX  Report complete - copy this into the issue template

  @nrwl/angular : Not Found
  @nrwl/cli : 8.11.0
  @nrwl/cypress : 8.11.0
  @nrwl/eslint-plugin-nx : 8.11.0
  @nrwl/express : Not Found
  @nrwl/jest : 8.11.0
  @nrwl/linter : 8.11.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : 8.11.0
  @nrwl/schematics : Not Found
  @nrwl/tao : 8.11.0
  @nrwl/web : 8.11.0
  @nrwl/workspace : 8.11.0
  typescript : 3.7.3
```

## Other

`packages/tao/src/shared/params.ts#coerceTypes` does not check for arrays

**Comment by fwoelffel** [comment]
Same issue here
```
>  NX  Report complete - copy this into the issue template

  @nrwl/angular : Not Found
  @nrwl/cli : 9.1.1
  @nrwl/cypress : 9.1.1
  @nrwl/eslint-plugin-nx : 9.1.1
  @nrwl/express : Not Found
  @nrwl/jest : 9.1.1
  @nrwl/linter : 9.2.3
  @nrwl/nest : 9.1.1
  @nrwl/next : 9.1.1
  @nrwl/node : 9.1.1
  @nrwl/react : 9.1.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.1.1
  @nrwl/web : 9.1.1  
  @nrwl/workspace : 9.1.1
  typescript : 3.8.3
```

**Comment by laaksomavrick** [comment]
Also seeing this.

**Comment by benmonro** [comment]
yeah same here

**Comment by benmonro** [comment]
@jeffbcross any chance we can get this fixed for the big W? :)

**Comment by jeffbcross** [comment]
@FrozenPandaz is the decision-maker :)

**Comment by benmonro** [comment]
@FrozenPandaz help me help you help Walmart. 🙂

**Comment by vsavkin** [comment]
Fixed it here: https://github.com/nrwl/nx/commit/a6220f7b0a677dbceb72bc2434cfeac6e4f86061

Should be out in 9.4.

**Comment by protoEvangelion** [comment]
@vsavkin I downloaded the latest release `9.4.0-rc.6` and still not seeing this resolved when running as @zaverden showed: `nx lint --files=apps/main-app/src/main.tsx`. Is there another way we should be running this?

**Comment by benmonro** [comment]
@vsavkin same here, we are on 9.4.0 and it still reports the same error

**Comment by benmonro** [comment]
![image](https://user-images.githubusercontent.com/399236/84699816-0f077400-af07-11ea-8740-0b00e349f85d.png)

**Comment by protoEvangelion** [comment]
@vsavkin it's because we are remapping the args back to the cmd line here: https://github.com/nrwl/nx/blob/7b27ba4daa5185dac63e52f726f75f8b5bf5ec7a/packages/workspace/src/tasks-runner/task-orchestrator.ts#L316

Any suggestions?

**Comment by junekpavel** [comment]
Same issue even with 9.5.0. Any news?

**Comment by benmonro** [comment]
@vsavkin any updates on this?  really need this for lint-staged.

**Comment by Hotell** [comment]
Hi folks, so to shed some light on this issue, ... it's actually not an issue :)

- `nx lint` needs project name. Without project name it won't work
-  you can narrow down files within your project `nx lint my-project --files=**/some-folder/**` which will run lint on libs/my-project/src/lib/some-folder/**`
- `--files` accepts a glob

**Comment by benmonro** [comment]
in that case, @Hotell can you give a recommendation for how to use lint staged with nx?  ultimately that's the goal here for me at least.

**Comment by Hotell** [comment]
> in that case, @Hotell can you give a recommendation for how to use lint staged with nx? ultimately that's the goal here for me at least.

use raw binary :)

`eslint --fix`

**Comment by junekpavel** [comment]
> @vsavkin any updates on this? really need this for lint-staged.

I am unable to use raw library as @Hotell mentioned, since all libraries don't have the same tslint configuration.

So I've came up with following solution:

As mentioned in documentation, you can use [custom lint function](https://www.npmjs.com/package/lint-staged#using-js-functions-to-customize-tasks). So I created a script that works like this:

First, load `angular.json` file, parse it (it's super easy since it's just a json) and store all projects with configured lint tasks (path to lint task in json structure is `/projects/*your-project*/architect/lint`) in a variable.

Then I try to assign staged files to their projects. It's also easy, because each project has root path (is `/projects/*your-project*/root` path in json). So I go through all staged files and check that file path starts with any project root path.

After this part, I have array of projects with (staged) files that belongs to these projects.

For each project, I create command `./node_modules/@angular/cli/bin/ng run *your-project*:lint --files libs/*your-project*/src/lib/a.ts --files libs/*your-project*/src/lib/b.ts --files libs/*your-project*/src/lib/c.ts`

And finally, I use [concurrently](https://www.npmjs.com/package/concurrently) to run all these lint commands together.

---

I know, that isn't ideal nor easy solution, but it's the only way I've found, how to get lint-staged work with multiple projects without linting all files.

**Comment by benmonro** [comment]
@junekpavel  interesting.  Can you share the script or an example?  Many thanks in advance

**Comment by Lonli-Lokli** [comment]
I believe usual case here is nx lint with eg jest with -affected flag

**Comment by zaverden** [comment]
@Lonli-Lokli If I change a single file then `affected:lint` is going to lint whole lib and it's dependencies. It may be great if it works this way in CI, but for pre-commit hook I don't want to relint whole project, only changed files to make it fast. that's why I want to use `--files` flag

**Comment by Lonli-Lokli** [comment]
@zaverden lint-staged pass array of staged files to the underlined command so I don't know why --files required.

**Comment by taitruong** [comment]
Working on Nx 11.1.5 and no change here. Option "--files" still does not work. Also suggestion from @Hotell doesn't work: `nx lint my-project --files=**/some-folder/**`

**Comment by brandontulsi** [comment]
@vsavkin this issue still exists, any way we can re-open?
