### ISSUE TITLE
nx-enforce-module-boundaries should use path mappings

### ISSUE THREAD

**Issue by pa-ru** [nrwl/nx#2757]
# Prerequisites
see #1520 

## Expected Behavior
nx-enforce-module-boundaries should work with path mappings

## Current Behavior

nx-enforce-module-boundaries is not working

### Steps to Reproduce

1. see #1520,
2. define some boundaries
3. break a boundary 
4. run linter

## Other

Any other relevant information that will help us help you.

**Comment by FrozenPandaz** [comment]
What version of Nx is being used? This issue should be fixed now as of v9. We are able to detect dependencies that resolved via path mappings. Please try with the latest version. Also, if possible, please share a repo that exhibits the issue.

**Comment by pa-ru** [comment]
Upgraded from 8.12.9 to 9.2.2 and the rules are still not working with path-mappings. 
Due to company restrictions i cannot share my repo. 
But i will create a repo demonstrating the issue later today or tomorrow.

**Comment by pa-ru** [comment]
here we go: https://github.com/pa-ru/webshop

The app **webshop** consits of the app and two libs **order-ui** and **product-ui**. 
The app is tagged with "app" and the libs are tagged with "ui".  
Although the following boundaries definition should prevent **order-ui** from using **product-ui** the linter does not throw any error.

``` json
 "nx-enforce-module-boundaries": [
      true,
      {
        "allow": [],
        "depConstraints": [
          {
            "sourceTag": "app",
            "onlyDependOnLibsWithTags": [
              "ui"
            ]
          },
          {
            "sourceTag": "ui",
            "onlyDependOnLibsWithTags": [
              "app"
            ]
          }
        ]
      }
    ]
```

**Comment by pa-ru** [comment]
@FrozenPandaz any news on this?
