### ISSUE TITLE
Unable to set journal_mode: SqliteFailure(Error { code: CannotOpen, extended_code: 14 }, Some("unable to open database file"))

### ISSUE THREAD

**Issue by wereHamster** [nrwl/nx#28640]
### Current Behavior

nx fails to run on my self-hosted github runners when trying to upgrade from 20.0.3 to 20.0.5 with the error in $SUBJECT. No additional information is printed into the console. Any nx command seems to trigger that, such as `nx run-many --target build`.

### Expected Behavior

Nx works, or at least prints a more useful message (eg. path to the database it's trying to access).

### Steps to Reproduce

It's a private repository, but I can try to reproduce if you think it'd help. I very much suspect it only affects certain type of self-hosted github runners, as the new version works on my local machine (macOS).

### Nx Report

```
Node           : 20.15.1
OS             : linux-x64
Native Target  : x86_64-linux
pnpm           : 9.6.0

nx                 : 20.0.5
@nx/js             : 20.0.5
@nx/eslint         : 20.0.5
@nx/workspace      : 20.0.5
@nx/devkit         : 20.0.5
@nx/esbuild        : 20.0.5
@nx/eslint-plugin  : 20.0.5
@nx/next           : 20.0.5
@nx/react          : 20.0.5
@nx/web            : 20.0.5
@nx/webpack        : 20.0.5
typescript         : 5.6.3
---------------------------------------
Registered Plugins:
@nx/eslint/plugin
@nx/next/plugin
```

### Failure Logs

Run npx nx run-many --target build

 NX   Unable to set journal_mode: SqliteFailure(Error { code: CannotOpen, extended_code: 14 }, Some("unable to open database file"))

Pass --verbose to see the stacktrace.

Error: Process completed with exit code 1.

### Operating System

- [ ] macOS
- [x] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by njsokol** [comment]
Getting the same thing on Linux

**Comment by wereHamster** [comment]
In my case, each github runner has its own workspace and even running under its own user account, so there should not be any cross-workspace conflicts.

**Comment by wereHamster** [comment]
The regression was introduced either in 20.0.4 or 20.0.5. I can try to narrow down which one it was. Looking at the changelog, nothing stands out (but there may have been changes not reflected in the changelog…).

![Image](https://github.com/user-attachments/assets/34aa83a2-4d33-4f5f-a4a4-4b200572ba66)

**Comment by wereHamster** [comment]
Alright, regression was introduced in 20.0.4.

**Comment by bjornharvold** [comment]
Seeing this too

**Comment by enchorb** [comment]
Was getting this on an M2 Mac `Unable to set journal_mode: SqliteFailure(Error { code: SystemIoFailure, extended_code: 522 }, Some("disk I/O error"))` after upgrading to `20.0.6` from `20.0.0`. After deleting the `.nx` folder the error went away as per the last comment here https://github.com/nrwl/nx/issues/28424

**Comment by Cammisuli** [comment]
@wereHamster if you run nx with the env `NX_NATIVE_LOGGING=nx::native:db` set, you should see where we're trying to open the database from. 

Also, if you don't mind pasting the logs with `NX_NATIVE_LOGGING` here so that I can see the flow. Thank you.

**Comment by cpierceworld** [comment]
I have the same (or related) issue....  started failing after upgrading rom Nx 18 to 20.0.6
* Nx 20.0.6, 
* linux-x64

I have a docker instance with Jenkins, runs runs 3 tasks in a row... the last task `npx nx run-many -t build` gives the Sqlite error

```
npx nx show projects --type lib --affected --base=6541ce36aee67873fcf457302a367368aed8678e --head=HEAD
npx nx release patch --skip-publish --projects=project-one,project-two,project-three,project-four,project-five,project-six
npx nx run-many -t build --configuration=production --projects=project-one,project-two,project-three,project-four,project-five,project-six
```
The first 2 commands works, the last gives:
```
Error: Unable to set journal_mode: SqliteFailure(Error { code: DatabaseBusy, extended_code: 5 }, Some("database is locked"))
10:12:36      at /jenkinshome/workspace/project-monorepo/node_modules/nx/src/utils/db-connection.js:11:93
10:12:36      at getEntryOrSet (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/utils/db-connection.js:19:17)
10:12:36      at getDbConnection (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/utils/db-connection.js:11:24)
10:12:36      at getTaskDetails (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/hasher/hash-task.js:19:84)
10:12:36      at invokeTasksRunner (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/tasks-runner/run-command.js:367:56)
10:12:36      at runCommandForTasks (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/tasks-runner/run-command.js:117:31)
10:12:36      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
10:12:36      at async /jenkinshome/workspace/project-monorepo/node_modules/nx/src/tasks-runner/run-command.js:105:29
10:12:36      at async handleErrors (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/utils/handle-errors.js:9:24)
10:12:36      at async runCommand (/jenkinshome/workspace/project-monorepo/node_modules/nx/src/tasks-runner/run-command.js:104:20)
```

**Comment by gausss** [comment]
Same issue for our project.

**Comment by minijus** [comment]
> [@wereHamster](https://github.com/wereHamster) if you run nx with the env `NX_NATIVE_LOGGING=nx::native:db` set, you should see where we're trying to open the database from.
> 
> Also, if you don't mind pasting the logs with `NX_NATIVE_LOGGING` here so that I can see the flow. Thank you.

Setting `NX_NATIVE_LOGGING=nx::native:db` did not produce any additional logs (running on self hosted Nx Cloud).

We are getting the same error:
```
NX   Unable to set journal_mode: SqliteFailure(Error { code: DatabaseBusy, extended_code: 5 }, Some("database is locked"))
```

`"useLegacyCache": true` is set in `nx.json`.

**Comment by Cammisuli** [comment]
@minijus make sure to set `NX_NATIVE_LOGGING` before doing `start-ci-run` for Nx Cloud. The start command will be the step that collects the env vars to send to agents, not specific `nx runs`

**Comment by minijus** [comment]
It seems the issue was addressed with `v20.0.7` release.

**Comment by wereHamster** [comment]
@Cammisuli setting that env. variable does not show any logs. I set it via `env:` top-level option in the github workflow so it's set when any job runs. And issue is still present in 20.0.7.

**Comment by Cammisuli** [comment]
@wereHamster are you using Nx Agents?

**Comment by raulgaf** [comment]
Not sure if this is a fix, but for us the issue was on the `yarnrc.yml` file.

We recently migrated to yarn berry (3.6.4) for one of our projects to use yarn workspaces & Lerna. But sometimes we need to go back to yarn classic since other projects do not support that version yet.

Anyways, we noticed that switching between versions will add the `yarnPath` config to the`.yarnrc.tml` file.
After we removed that config lerna was working as expected. 🤷‍♂ 

Not sure if this is related with lerna or nx but hopefully this helps someone with the same issue 😅

**Comment by djohnson-aperture** [comment]
Chiming in. I was using a clean clone of a repo. I'd ask if anyone here is using the VS Code `Nx Console (nrwl.angular-console)` extension? I think it does something to mess up the cache during that initial loading of the workspace in VS Code.

Doing the clone and initial setup in a basic terminal seemed to get me past the point where things could get mangled.

**Comment by wereHamster** [comment]
> [@wereHamster](https://github.com/wereHamster) are you using Nx Agents?

No. I'm running Nx on self-hosted github action runners.

**Comment by Erbenos** [comment]
Deleting the .nx folder does help, but its merely a temporarily solution, it happens again eventually, and then you need to delete .nx folder again.

**Comment by LeLunZ** [comment]
Same issue here (on a Mac) after migrating from angular 17 to 18. and nx is on version `20.0.11`.
Deleting .nx folder or calling `nx reset` or `nx repair` isn't helping

**Comment by Cammisuli** [comment]
Folks here, can we try the latest version of Nx (20.0.12) to see if this is still reproducible?

**Comment by kaylesworth** [comment]
> Folks here, can we try the latest version of Nx (20.0.12) to see if this is still reproducible?

Upgraded to 20.0.12 today and using github actions with namespace runners I am still getting the error

**Comment by kaylesworth** [comment]
> [@kaylesworth](https://github.com/kaylesworth) lets try 20.0.13 now 🙂 thanks for your help!

Can confirm that it works in 20.0.13!

**Comment by tFaster** [comment]
We updated to the latest Nx v20.1.0 and still get an SqliteFailureError in our build:
`NX   DB transaction operation error: SqliteFailure(Error { code: DatabaseBusy, extended_code: 5 }, Some("database is locked"))`
These errors started to occurr for us since Nx v20.0.4

**Comment by Cammisuli** [comment]
@tFaster where is this happening for you? Local dev machine? (macOS, Linux, Windows?). If locally do you have Nx Console installed? Or was this happening CI? Can you give me more details on what was happening before?

**Comment by mruknowme** [comment]
For me it works on v20.1.0

**Comment by jrista** [comment]
Getting the same. Intel Mac ATM. NMX 19 and 20. Quite a persistent error. Usually have to run commands exactly three times to resolve the issue. Not sure why exactly three. The first two fail, third succeeds.

**Comment by novascreen** [comment]
I am using `nx-remotecache-gcs` and noticed that via peer dependencies it installed a different version of nx. So I had multiple versions of nx. I ended up installing the right version of the peer dependency explicitly to get the versions in line.

Maybe have a look at your dependency lock files and see if you have multiple nx versions installed for some reason.

**Comment by jrista** [comment]
> > Getting the same. Intel Mac ATM. NMX 19 and 20. Quite a persistent error. Usually have to run commands exactly three times to resolve the issue. Not sure why exactly three. The first two fail, third succeeds. Does not seem to matter how much time passes between runs. I can run three times in a row as fast as I can, or wait minutes between each. Always fails the first two, succeeds the third.
> 
> On Linux and yes I get this exact behavior where I have to run the command three times. It seems to happen consistently on first launch after turning on my PC then for the rest of the day it will (mostly) work on the first try.

Interesting. In my case, I always have to run three times, every time. It never seems to resolve itself such that I can run just once.

I also have a tail going on the log. I've never seen any errors in the log that would indicate the issue...the daemon just dies, and running three times works, but there are never any log entries indicating what the problem might be.

**Comment by kohsine** [comment]
On `v20.0.12` and it seems to be fixed for me at least on my local linux machine.

**Comment by Cammisuli** [comment]
Yea, this is an elusive issue that doesnt happen to everyone. 

@jrista does this happen locally for you or on CI as well? 
- Can you give me everything you can think of that would make your system unique/different from a base ubuntu lts image (if running on Linux)? 
- Versions of OS's, repos, versions of nx with `nx report`. 
- Does this usually happen if you run without the daemon with `NX_DAEMON=false`? 
- Do you have Nx Console installed (vscode, intellij)
  - Is it updated to the latest version?
  - Does the issue go away if you disable nx console?
- Also can you run the commands with `NX_NATIVE_LOGGIN=nx::native::nx` and share those outputs? (The outputs will be in the daemon.log file found with `nx daemon`, or in terminal output while running with `NX_DAEMON=false`)

**Comment by WSINTRA** [comment]
Had same, issue. When running 
```
$nx run-many --target=typecheck

Error: Unable to set journal_mode: DB pragma update error: SqliteFailure(Error { code: SystemIoFailure, extended_code: 522 }, Some("disk I/O error"))

// Fixed with
$nx reset

**Comment by jrista** [comment]
> Yea, this is an elusive issue that doesnt happen to everyone.
> 
> [@jrista](https://github.com/jrista) does this happen locally for you or on CI as well?
> 
> * Can you give me everything you can think of that would make your system unique/different from a base ubuntu lts image (if running on Linux)?
> * Versions of OS's, repos, versions of nx with `nx report`.
> * Does this usually happen if you run without the daemon with `NX_DAEMON=false`?
> * Do you have Nx Console installed (vscode, intellij)
>   
>   * Is it updated to the latest version?
>   * Does the issue go away if you disable nx console?
> * Also can you run the commands with `NX_NATIVE_LOGGIN=nx::native::nx` and share those outputs? (The outputs will be in the daemon.log file found with `nx daemon`, or in terminal output while running with `NX_DAEMON=false`)

I don't have CI set up on these. I'm currently doing a series of POCs to prepare for an upcoming contract. So its just local. 

Here is the Nx report (macos x):

```
➜ nx report

 NX   Report complete - copy this into the issue template

Node           : 20.18.0
OS             : darwin-x64
Native Target  : x86_64-macos
npm            : 10.8.2

nx                 : 19.8.10
@nx/js             : 19.8.10
@nx/jest           : 19.8.10
@nx/linter         : 19.8.10
@nx/eslint         : 19.8.10
@nx/workspace      : 19.8.10
@nx/angular        : 19.8.10
@nx/devkit         : 19.8.10
@nx/eslint-plugin  : 19.8.10
@nx/playwright     : 19.8.10
@nrwl/tao          : 19.8.10
@nx/vite           : 19.8.10
@nx/web            : 19.8.10
@nx/webpack        : 19.8.10
typescript         : 5.5.4
---------------------------------------
Registered Plugins:
@nx/playwright/plugin
@nx/eslint/plugin
---------------------------------------
Community plugins:
@auth0/auth0-angular : 2.2.3
@ionic/angular       : 8.4.0
@ngrx/effects        : 18.1.1
@ngrx/router-store   : 18.1.1
@ngrx/store          : 18.1.1
@ngrx/store-devtools : 18.1.1
@nxext/ionic-angular : 19.1.2
```

I have been having some other issues with 20, so I'm currently using 19.8. 

FWIW, I AM actually using Nx Console in Webstorm. I hadn't considered that that might be part of the problem. So, I uninstalled it, closed webstorm, and restarted. ATM, I am not having issues. I reinstalled Nx Console, and am still not having issues...

SO, that makes me wonder if somehow that WAS interfereing with it. Thing is, that's how it originally was as well. When I first set up these projects, everything was fine. Then one day, they weren't, and it was persistently a problem from that day on. So I don't know if the issue will reoccur. If it does, then I'll uninstall Nx Console and leave it uninstalled, and see if the issue still reoccurs.

**Comment by jrista** [comment]
I think that Nx Console is a part of the problem. I don't think it is the entire problem, but removing Nx Console did eliminate the need for me to run every command three times all the time. I still run into the issue, usually first thing in the day, first time I run an Nx command. Sometimes it will occur at other times during the day, but it is not as persistent as it used to be. Adding Nx Console back, does not immediately result in the issue, however over time, the issue gets worse until I am once again having to run every command three times in a row. 

Not sure what it is, but there does seem to be an issue with Nx Console and however it is interacting with Nx. Will try to contact the author and let them know about this issue.

**Comment by raknjarasoa** [comment]
I’m experiencing the same issue in GitHub Actions with version 20.1.4, as well as the latest version, 20.3.0

> [1]  NX   DB transaction operation error: SqliteFailure(Error { code: DatabaseBusy, extended_code: 5 }, Some("database is locked"))
> [1] 
> [1] Pass --verbose to see the stacktrace.
> [1] 
> [0] > nx run web:serve:ci
> [0] 
> [0]  NX   Running target serve for project web failed
> [0] 
> [0] Failed tasks:
> [0] 
> [0] - web:serve:ci
> [0] 
> [0] Hint: run the command with --verbose for more details.
> [0] 
> [0]  NX   No database connection available
> [0] 
> [0] Pass --verbose to see the stacktrace.
> [0] 
> [0] npm run start:web:ci exited with code SIGTERM
> Error: Process completed with exit code 1.

**Comment by Cammisuli** [comment]
We did some fixes in both Nx Console, and the daemon to make sure that it uses the same connection consistently. Is the problem still occurring for anyone with the latest versions of Nx Console and Nx?

**Comment by jrista** [comment]
I paused my project a little while back, so I haven't updated it yet. I'll see if I can get back to that one soon here and see if the updates solve the issue.

**Comment by Sefibrah** [comment]
It happened again at nx's v20.4.5, i downgraded to v20.4.2 to fix it...

**Comment by raknjarasoa** [comment]
@Sefibrah are you trying to set [NX_DISABLE_DB](https://github.com/nrwl/nx/issues/28772#issuecomment-2604710534), it’s fix my issues

**Comment by dmithamo** [comment]
I ran into this error when I tried to run `nx serve <app_name_here>` after upgrading to the latest version as described [here](https://nx.dev/features/automate-updating-dependencies). 

I deleted the `.nx` and `node_modules` directories, reinstalled dependencies, and was then able to run `nx serve <app_name_here>` without issue.

I am using `v20.5.0` of Nx and `v19.2.1` of Angular.

**Comment by yhaiovyi-tripactions** [comment]
It fails for me occasionally in Jenkins. Clean runs, no cache.

**Comment by juliusp-simplex** [comment]
happens for us too, for random calls event with --parallelism=1

**Comment by daryakalenik** [comment]
I'm running into this too. Every time I update the Nx packages and then try to push, I get the `Unable to set journal_mode: SqliteFailure(...)` error. What's weird is that deleting the `.nx` folder *does* eventually work, but I usually have to delete it a few times in a row. Just deleting it once doesn't seem to cut it.

Running `nx` version `21.0.3` here.

**Comment by TrejGun** [comment]
same for me

**Comment by codeninja** [comment]
I ran across the same issue after an update. Running a `yarn nx reset` resolves the issue for me.

**Comment by TrejGun** [comment]
> I ran across the same issue after an update. Running a `yarn nx reset` resolves the issue for me.

yup, looks like you just need to clear .nx folder

**Comment by badreerauniyar** [comment]
> It fails for me occasionally in Jenkins. Clean runs, no cache.

it fails for me too nx 19 , in jenkins, how did you fix?
