### ISSUE TITLE
Clarify dependency management options for buildable Node libraries

### ISSUE THREAD

**Issue by DarylLyonsLF** [nrwl/nx#28799]
### Documentation issue

- [ ] Reporting a typo
- [ ] Reporting a documentation bug
- [ ] Documentation improvement
- [x] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/concepts/decisions/dependency-management
https://nx.dev/ci/recipes/other/ci-deployment

### Additional context or description

https://github.com/nrwl/nx/pull/19543 dropped support for generating `package.json` files during execution of `@nx/js:tsc`. The recommendation is to use `@nx/dependency-checks` instead.

This change results in `package.json` files existing on buildable Node libs where they weren't required before.

Nx docs relating to dep management seem to overlook this change. E.g.
1. https://nx.dev/concepts/decisions/dependency-management#single-version-policy
    Doesn't account for buildable lib's and is misleading in this context:
    > Individual projects may still have package.json files, but **they are used only for the metadata defined there, not as a way of defining the dependencies of that project.**

2. https://nx.dev/ci/recipes/other/ci-deployment
    This page is linked from the single version policy page (above). It only accounts for application deployment.

**Where can we find information on publishing lib's through CI, or options for managing their dependencies?**

**Comment by Coly010** [comment]
Hi, these problems have been addressed in our latest setup. Note that these changes are not turned on by default. You can see how it operates now with `npx create-nx-workspace@latest acme --workspaces` to get a Package Manager-supported setup.

The point about the Single Version Policy is a good one. It's actually incorrect information and will get updated as we are actually able to have multiple package.json files and still have a strict single version policy.

**Comment by lppedd** [comment]
@Coly010 is the new setup you mentioned the one discussed in an RFC recently? If yes, the problem is it's an alternative to what exists now, not something mandatory, and not something that everyone can use (especially for historical reasons).

**Comment by DarylLyonsLF** [comment]
@Coly010 @FrozenPandaz appreciate the response and information.

> It's actually incorrect information **and will get updated** as we are actually able to have multiple package.json files and still have a strict single version policy.

Shouldn't this particular issue remain open until the docs have been addressed? Is there an existing PR that should be linked?
