### ISSUE TITLE
"@nx/js" cannot infer build target

### ISSUE THREAD

**Issue by jorgefranciscogil** [nrwl/nx#29578]
### Current Behavior

Through ‘@nx/js’ infer only typecheck task. Build task is missing.

### Expected Behavior

Through ‘@nx/js’ infer automatically build and typecheck tasks.

### Steps to Reproduce

I follow the [official npm tutorial](https://nx.dev/getting-started/tutorials/npm-workspaces-tutorial) up to @nx/js addition.

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 20.16.0
OS             : linux-x64
Native Target  : x86_64-linux
npm            : 10.8.1

nx (global)    : 20.3.1
nx             : 20.3.1
@nx/js         : 20.3.1
@nx/workspace  : 20.3.1
@nx/devkit     : 20.3.1
typescript     : 5.5.4
---------------------------------------
Registered Plugins:
@nx/js/typescript
```

### Failure Logs

```shell
➜  tuskydesign-2 git:(main) ✗ npx nx build @tuskdesign/zoo --verbose

 NX   Cannot find configuration for task @tuskdesign/zoo:build

Error: Cannot find configuration for task @tuskdesign/zoo:build
    at ProcessTasks.createTask (/home/jcgl/repos/github/tuskydesign-2/node_modules/nx/src/tasks-runner/create-task-graph.js:163:19)
    at ProcessTasks.processTasks (/home/jcgl/repos/github/tuskydesign-2/node_modules/nx/src/tasks-runner/create-task-graph.js:36:39)
    at createTaskGraph (/home/jcgl/repos/github/tuskydesign-2/node_modules/nx/src/tasks-runner/create-task-graph.js:202:21)
    at createTaskGraphAndRunValidations (/home/jcgl/repos/github/tuskydesign-2/node_modules/nx/src/tasks-runner/run-command.js:78:63)
    at ensureWorkspaceIsInSyncAndGetGraphs (/home/jcgl/repos/github/tuskydesign-2/node_modules/nx/src/tasks-runner/run-command.js:132:21)
    at runCommandForTasks (/home/jcgl/repos/github/tuskydesign-2/node_modules/nx/src/tasks-runner/run-command.js:114:47)
    at /home/jcgl/repos/github/tuskydesign-2/node_modules/nx/src/tasks-runner/run-command.js:105:35
    at handleErrors (/home/jcgl/repos/github/tuskydesign-2/node_modules/nx/src/utils/handle-errors.js:8:30)
    at runCommand (/home/jcgl/repos/github/tuskydesign-2/node_modules/nx/src/tasks-runner/run-command.js:104:59)
    at Object.runOne (/home/jcgl/repos/github/tuskydesign-2/node_modules/nx/src/command-line/run/run-one.js:48:59)
```

### Operating System

- [ ] macOS
- [ ] Linux
- [ ] Windows
- [x] Other (Please specify)

### Additional Information

I use WSL under windows.

> wsl -l -v

NAME              STATE           VERSION
* Ubuntu            Running         2

**Comment by shohei-ot** [comment]
I have a same problem.

```
NX   Report complete - copy this into the issue template

Node           : 22.11.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.9.0

nx             : 20.3.1
@nx/js         : 20.3.1
@nx/workspace  : 20.3.1
@nx/devkit     : 20.3.1
typescript     : 5.5.4
---------------------------------------
Registered Plugins:
@nx/js/typescript
```

**Comment by leosvelperez** [comment]
Thanks for reporting this!

Unfortunately, I can't reproduce the issue by following the exact steps of the NPM Workspaces Tutorial. Please provide a repo where the issue can be reproduced.

**Comment by leosvelperez** [comment]
This has been fixed by https://github.com/nrwl/nx/pull/29431 and it will be released soon.

**Comment by jorgefranciscogil** [comment]
The problem persists even though I have updated all dependencies.

**Comment by jorgefranciscogil** [comment]
Ok. We'll be waiting for that, thank you!
