### ISSUE TITLE
Cannot properly Find All References in VSCode even when using nx --workspaces with project references

### ISSUE THREAD

**Issue by GautierBlandin** [nrwl/nx#30378]
### Current Behavior

Despite setting up project references using the --workspaces option, Find All References still does not work under the default tsconfig setup.

### Expected Behavior

When properly setting up project references, the problems encountered in https://github.com/nrwl/nx/issues/3106 should be fixed and Find All References should properly work when using VS Code as an IDE.

### GitHub Repo

https://github.com/GautierBlandin/nx-vscode-issue

### Steps to Reproduce

1. Create an nx workspace using the latest CLI version and using the --workspace to setup project references: `npx create-nx-workspace@latest tsmono --workspaces`. To make the reproduction as simple as possible, I chose:
- Stack: node
- Framework: none
- Application name: server
- Generate a dockerfile: no
- Test runner: none
- ESLint: no
- Prettier: no
- CI: skip
- Remote caching: skip

2. Create a simple, non-buildable library: `nx g lib libs/mytslib`.  Options:
- Generator: @nx/js:library
- Linter: none
- Test runner: none

3. Update `main.ts` in the server app to import from mytslib:
```ts
// main.ts
import { mytslib } from "@tsmono/mytslib";

console.log(mytslib());
```

4. Run `nx sync` so that the server's tsconfig references the library's tsconfig.

5. Close all files in the IDE, and open **only** libs/mytslib/src/lib/mytslib.ts
6. Restart the typescript server, or restart the IDE
7. Right-click on mytslib, and use the Find All References action. Only one reference will be found (the current file), where two should be (the current file **and** main.ts).

### Nx Report

```shell
Node           : 23.9.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.9.2

nx (global)    : 20.0.4
nx             : 20.5.0
@nx/js         : 20.5.0
@nx/jest       : 20.5.0
@nx/eslint     : 20.5.0
@nx/workspace  : 20.5.0
@nx/devkit     : 20.5.0
@nx/esbuild    : 20.5.0
@nx/node       : 20.5.0
typescript     : 5.7.3
---------------------------------------
Registered Plugins:
@nx/js/typescript
@nx/js/typescript
```

### Failure Logs

```shell

```

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

### Additional Information

Removing the multi tsconfig setup (e.g, instead of having mytslib/tsconfig.json **and** mytslib/tsconfig.lib.json, only having mytslib/tsconfig.json) seems to fix the issue. However, that fix is less than ideal when also setting up a testing framework, as it is good to separately handle types and ts compilation for implementation files and test files.
I haven't managed yet to make the Find All References action properly work using a multi tsconfig setup. Finding a way to do that would probably be the ideal fix to this issue.

**Comment by blackakula** [comment]
My problem was solved after installation of Nx Console extension: https://github.com/nrwl/nx-console. Now my Cursor finds all references well.

**Comment by Tantol** [comment]
I have same issue. Installing extension doesn't resolve it for me.

Adding "include": ["src/**/*.ts"], to the library's tsconfig.json helped. Can someone with expertise explain why and if this is desirable?
