### ISSUE TITLE
npm ci hangs on NX 21.2.0 during GitHub Actions run

### ISSUE THREAD

**Issue by mprendki-relativity** [nrwl/nx#31649]
### Current Behavior

We're experiencing a hang during the npm ci step in our GitHub Actions workflow after upgrading to NX version 21.2.0. This issue does not occur with NX version 21.1.3.

The problematic step is:

```yaml
- name: Install dependencies
  run: npm ci --verbose
```
After a long wait, the workflow ends with: Operation was canceled.

We verified that the correct NX version is installed via npm ls nx, and it shows version 21.2.0.

The process consistently hangs at the following output:

```bash
npm info run nx@21.2.0 postinstall node_modules/nx node ./bin/post-install
```

### Expected Behavior

Post install should not break pipeline.

### Steps to Reproduce

Hard to describe precisely, but the issue occurs consistently in a fresh repository with a newly written pipeline.

Workflow runs on:

```runs-on: ubuntu-latest```

```NODE_VERSION: '22'```

The pipeline hangs during this step:

```yaml
- name: Install dependencies
  run: npm ci --verbose
```

### Nx Report

```shell
this nx report is runed localy so the OS is different then on the pipeline:

NX   Report complete - copy this into the issue template

Node           : 22.15.0
OS             : win32-x64
Native Target  : x86_64-windows
npm            : 10.9.2

nx                     : 21.2.0
@nx/js                 : 21.2.0
@nx/eslint             : 21.2.0
@nx/workspace          : 21.2.0
@nx/cypress            : 21.2.0
@nx/devkit             : 21.2.0
@nx/eslint-plugin      : 21.2.0
@nx/module-federation  : 21.2.0
@nx/playwright         : 21.2.0
@nx/react              : 21.2.0
@nx/storybook          : 21.2.0
@nx/vite               : 21.2.0
@nx/web                : 21.2.0
typescript             : 5.8.3
---------------------------------------
Registered Plugins:
@nx/js/typescript
@nx/react/router-plugin
@nx/eslint/plugin
@nx/vite/plugin
@nx/playwright/plugin
@nx/storybook/plugin
---------------------------------------
Cache Usage: 0.00 B / 190.51 GB
```

### Failure Logs

```shell
npm info run @parcel/watcher@2.5.1 install node_modules/@parcel/watcher node scripts/build-from-source.js
npm info run @parcel/watcher@2.5.1 install { code: 0, signal: null }
npm info run @nestjs/core@11.1.1 postinstall node_modules/@nestjs/core opencollective || exit 0
npm info run @nestjs/core@11.1.1 postinstall { code: 0, signal: null }
npm info run @openapitools/openapi-generator-cli@2.20.2 postinstall node_modules/@openapitools/openapi-generator-cli opencollective || exit 0
npm info run @openapitools/openapi-generator-cli@2.20.2 postinstall { code: 0, signal: null }
npm info run @swc/core@1.5.29 postinstall node_modules/@swc/core node postinstall.js
npm info run @swc/core@1.5.29 postinstall { code: 0, signal: null }
npm info run @tailwindcss/oxide@4.1.10 postinstall node_modules/@tailwindcss/oxide node ./scripts/install.js
npm info run @tailwindcss/oxide@4.1.10 postinstall { code: 0, signal: null }
npm info run esbuild@0.25.5 postinstall node_modules/esbuild node install.js
npm info run esbuild@0.25.5 postinstall { code: 0, signal: null }
npm info run nx@21.2.0 postinstall node_modules/nx node ./bin/post-install
Error: The operation was canceled.
```

### Operating System

- [ ] macOS
- [x] Linux
- [x] Windows
- [ ] Other (Please specify)

**Comment by Grechist** [comment]
I'm experiencing the same issue in my project.

**Comment by josegers** [comment]
Same problem in our Azure pipeline.

**Comment by teads-pierre-sabouret** [comment]
Same on my side
NX 21.2.1
NPM 10.8.2
node 20

```
npm info run nx@21.2.1 postinstall { code: null, signal: 'SIGINT' }
npm verbose stack Error: command failed
npm verbose stack     at promiseSpawn (/home/runner/_work/_tool/node/20.19.3/x64/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:22:22)
npm verbose stack     at spawnWithShell (/home/runner/_work/_tool/node/20.19.3/x64/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:124:10)
npm verbose stack     at promiseSpawn (/home/runner/_work/_tool/node/20.19.3/x64/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:12:12)
npm verbose stack     at runScriptPkg (/home/runner/_work/_tool/node/20.19.3/x64/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:77:13)
npm verbose stack     at runScript (/home/runner/_work/_tool/node/20.19.3/x64/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script.js:9:12)
npm verbose stack     at /home/runner/_work/_tool/node/20.19.3/x64/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/rebuild.js:329:17
npm verbose stack     at run (/home/runner/_work/_tool/node/20.19.3/x64/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:67:22)
npm verbose stack     at /home/runner/_work/_tool/node/20.19.3/x64/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:84:9
npm verbose stack     at new Promise (<anonymous>)
npm verbose stack     at callLimit (/home/runner/_work/_tool/node/20.19.3/x64/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:35:69)
npm verbose pkgid nx@21.2.1
```

It looks like it's related to many other issues posted recently... 
Could we have an update on resolution?

**Comment by teads-pierre-sabouret** [comment]
Up ⬆️
For those who have the issue, I confirm that downgrading to 21.0.4 fixes the issue

**Comment by BaneTopcon** [comment]
We're trying to upgrade to 21.2.1 and we're getting the same issue with npm ci in our Azure Pipeline.

**Comment by lorenzodejong** [comment]
Same happening here in Azure Pipelines with `21.2.2`

**Comment by josegers** [comment]
Update: We switched from npm to pnpm, and that solved the issue for us.

**Comment by wladyslawczyzewski** [comment]
same issue for me when installing inside docker container. on host machine (macOS) works fine

UPD: downgrading to 21.1.3 solved this issue for now

**Comment by dleonard8764** [comment]
We are trying to upgrade to 21.2.x and are having the same issue with npm ci in our Azure Pipelines. This is preventing us from upgrading to Angular 20 since NX 21.2 is minimally required.

**Comment by alexfreska** [comment]
Same issue on GitHub actions

**Comment by tweltner** [comment]
Same in our project when we are running on Jenkins.

**Comment by wladyslawczyzewski** [comment]
> UPD: downgrading to 21.1.3 solved this issue for now

btw be careful with pinning versions of nx – if you pin it with `^` it will install the latest `21.2.2` which hangs on forever in GitHub Actions and as result you will have endlessly running job and huge bill at the end of the month.

default timeout for GitHub Actions according to documentation is 6 hours, but looks like GitHub retries timeouted workflows automatically

**Comment by estinsunnyk** [comment]
🐞 CI Hangs During Node Install / Postinstall – Likely Around @swc/core

I’m facing a persistent issue where the GitHub Actions pipeline hangs during npm install or subsequent build steps without throwing any clear error. This only occurs in CI, while the same process works perfectly on my local machine.

🛠️ Environment

Nx version: 21.2.2

Node version (CI): 22.15.0

NPM version: 10.9.2

CI: GitHub Actions

Package observed in logs: `@swc/core@1.5.29`


📌 The last log before the hang:

`npm info run @swc/core@1.5.29 postinstall { code: 0, signal: null }`

After this line, the pipeline stalls indefinitely. No errors, no timeout, just a silent stop. This is affecting all subsequent build or test steps.

✅ Confirmations

No issues on local (same Node and NPM versions).

No permission or network issues in CI.

**Comment by jaskarnmankoo** [comment]
Bump! We're also experiencing this hang on `v21+` in our GitHub Actions Runner and have temporarily resolved it by pinning our projects to `nx@20.8.2`.

**Comment by jlengstorf** [comment]
I just hit this on Netlify as well. pinned to 20.8.2 as well and Netlify builds as expected

**Comment by benjamin-chang** [comment]
It was working, but after moving some libraries around via `nx g @nx/workspace:move` we are now seeing this as well. 

### `npm ci --timing`
```
npm info run esbuild@0.25.5 postinstall node_modules/esbuild node install.js
npm info run esbuild@0.25.5 postinstall { code: 0, signal: null }
npm timing build:run:postinstall:node_modules/esbuild Completed in 807ms
npm info run nx@21.2.2 postinstall node_modules/nx node ./bin/post-install
Error: The operation was canceled.
```

### `nx report`
```

NX   Report complete - copy this into the issue template

Node           : 22.12.0
OS             : darwin-arm64
Native Target  : aarch64-macos
npm            : 10.9.0

nx (global)            : 21.2.2
nx                     : 21.2.2
@nx/js                 : 21.2.2
@nx/jest               : 21.2.2
@nx/eslint             : 21.2.2
@nx/workspace          : 21.2.2
@nx/devkit             : 21.2.2
@nx/eslint-plugin      : 21.2.2
@nx/module-federation  : 21.2.2
@nx/plugin             : 21.2.2
@nx/react              : 21.2.2
@nx/vite               : 21.2.2
@nx/web                : 21.2.2
typescript             : 5.8.3
---------------------------------------
Registered Plugins:
@nx/js/typescript
@nx/react/router-plugin
@nx/eslint/plugin
@nx/vite/plugin
---------------------------------------
Cache Usage: 89.54 MB / 92.64 GB
```

**Comment by benjamin-chang** [comment]
Like  @josegers - We also switched from npm to pnpm. We also blacklisted Nx’s postinstall script, which appears to only handle analytics and telemetry.

**Comment by robertmazzo** [comment]
We are also experiencing this hanging issue in the Azure Piplines, and trying to upgrade our project to **Angular 20**.

**Comment by bcerquiare** [comment]
Same here using v21.3.5

**Comment by tweltner** [comment]
Should be fixed with Nx 21.3.8 - see release notes: https://github.com/nrwl/nx/releases/tag/21.3.8

**Comment by nealoke** [comment]
When reading this I think I still have this issue with version Nx `21.3.10` even. Npm install script hangs, when cancelling the command I can see that Nx postinstall is still running (I let it run for more then 10 minutes). This is inside a docker container, outside it is just fine on my machine. But quite annoying that I can't build my container anymore :)

```
npm info run @nestjs/core@10.4.7 postinstall node_modules/@nestjs/core opencollective || exit 0
npm info run @prisma/client@5.22.0 postinstall node_modules/@prisma/client node scripts/postinstall.js
npm info run @prisma/engines@5.22.0 postinstall node_modules/@prisma/engines node scripts/postinstall.js
npm info run @sentry/cli@2.41.1 postinstall node_modules/@sentry/cli node ./scripts/install.js
npm info run esbuild@0.25.8 postinstall node_modules/esbuild node install.js   
npm info run nx@21.3.10 postinstall node_modules/nx node ./bin/post-install    
npm info run unrs-resolver@1.11.1 postinstall node_modules/unrs-resolver napi-postinstall unrs-resolver 1.11.1 check
npm info run @sentry/cli@2.41.1 postinstall { code: 0, signal: null }
npm timing build:run:postinstall:node_modules/@sentry/cli Completed in 49ms    
npm info run unrs-resolver@1.11.1 postinstall { code: 0, signal: null }        
npm timing build:run:postinstall:node_modules/unrs-resolver Completed in 26ms  
npm info run @prisma/engines@5.22.0 postinstall { code: 0, signal: null }      
npm timing build:run:postinstall:node_modules/@prisma/engines Completed in 129ms
npm info run @prisma/client@5.22.0 postinstall { code: 0, signal: null }       
npm timing build:run:postinstall:node_modules/@prisma/client Completed in 249ms
npm info run @nestjs/core@10.4.7 postinstall { code: 0, signal: null }
npm timing build:run:postinstall:node_modules/@nestjs/core Completed in 266ms  
npm info run esbuild@0.25.8 postinstall { code: 0, signal: null }
npm timing build:run:postinstall:node_modules/esbuild Completed in 263ms       
npm info run nx@21.3.10 postinstall { code: null, signal: 'SIGINT' } <--- Manually aborted, shows this was still going on
```

Just confirmed that with version `21.3.8` it does work as mentioned by @tweltner, but the latest it doesn't as it seems :)

**Comment by bigcakes** [comment]
@nealoke We are seeing the same thing for one of our users that only 21.3.8 works and 21.3.9 doesn't

**Comment by trinitiwowka** [comment]
Same...

```
npm info run nx@21.3.8 postinstall { code: null, signal: 'SIGTERM' }
npm verbose stack Error: command failed
npm verbose stack     at promiseSpawn (/opt/lib/nvm/versions/node/v22.15.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:22:22)
npm verbose stack     at spawnWithShell (/opt/lib/nvm/versions/node/v22.15.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:124:10)
npm verbose stack     at promiseSpawn (/opt/lib/nvm/versions/node/v22.15.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:12:12)
npm verbose stack     at runScriptPkg (/opt/lib/nvm/versions/node/v22.15.0/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script-pkg.js:77:13)
npm verbose stack     at runScript (/opt/lib/nvm/versions/node/v22.15.0/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/run-script.js:9:12)
npm verbose stack     at /opt/lib/nvm/versions/node/v22.15.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/rebuild.js:329:17
npm verbose stack     at run (/opt/lib/nvm/versions/node/v22.15.0/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:67:22)
npm verbose stack     at /opt/lib/nvm/versions/node/v22.15.0/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:84:9
npm verbose stack     at new Promise (<anonymous>)
npm verbose stack     at callLimit (/opt/lib/nvm/versions/node/v22.15.0/lib/node_modules/npm/node_modules/promise-call-limit/dist/commonjs/index.js:35:69)
npm verbose pkgid nx@21.3.8
```

**Comment by nealoke** [comment]
@bigcakes it seems that this issue happened only for me when using node v20, after switching to node v22 (LTS) this error is no more (windows).

On my Github Actions though it still hangs (even with v22 node).

**Comment by jlengstorf** [comment]
confirming that as of `v21.3.11` Netlify builds are working again

**Comment by lorenzodejong** [comment]
Still seems to occur in Azure Pipelines, i tried with both `21.3.11` and `21.3.8` which yields the same results, hanging after the following stdout:
```
.../node_modules/nx postinstall$ node ./bin/post-install
.../node_modules/nx postinstall$ node ./bin/post-install
.../node_modules/nx postinstall: Done
```

**Comment by bameyrick** [comment]
Also seeing this issue in bitbucket pipelines via a docker image.

- nx: 21.4.0
- node: 24.6.0
- npm: 11.5.1

**Comment by lorenzodejong** [comment]
Yeah important addition is that i'm also running through Docker, using a [custom Azure Pipelines agent](https://learn.microsoft.com/en-us/azure/devops/pipelines/agents/docker?view=azure-devops).

When setting the following in the package.json to skip the postinstall, the `pnpm install` step actually works however the pipeline hangs again on the first next step where the nx CLI gets invoked:
```json
"pnpm": {
    "ignoredBuiltDependencies": ["nx"]
  }
```

**Comment by pmaieref** [comment]
I encountered the same issue in NX 21.4.1 and was able to reproduce/fix it by including the correct binary in the package-lock.json file. 

Setup: 
- NPM, NX 21.4.1
- Windows locally, Linux in the CI

Turned out, npm removes from time to time optional dependencies from its package-lock.json file on certain npm operations and this includes also the removal of the nx linux binary. 

Adding this manually to the lock file fixed it for me:
```
"node_modules/@nx/nx-linux-x64-gnu": {
    "version": "21.4.1",
    "cpu": [
        "x64"
    ],
    "dev": true,
    "license": "MIT",
    "optional": true,
    "os": [
        "linux"
    ]
},
```
I just added it manually in the lockfile next to the "node_modules/@nx/nx-win32-x64-msvc", where it was removed from. Depending on your system it might be a different binary that is missing.

I would expect the postinstall script to fail or time out. I can see that both cases are covered in the code (https://github.com/nrwl/nx/blob/master/packages/nx/bin/post-install.ts#L16 and https://github.com/nrwl/nx/blob/master/packages/nx/src/native/assert-supported-platform.ts#L15) but it does not seem to work.

Maybe this helps somebody.

**Comment by FrozenPandaz** [comment]
Yes this should be fixed by https://github.com/nrwl/nx/pull/32027

**Comment by josegers** [comment]
> Yes this should be fixed by [#32027](https://github.com/nrwl/nx/pull/32027)

Why would you close this issue as it is clearly not fixed yet? The previous post contains the steps to reproduce.

**Comment by lorenzodejong** [comment]
> Yes this should be fixed by [#32027](https://github.com/nrwl/nx/pull/32027)

The issue is not fixed indeed, i also tried upgrading to `21.4.1` in which the postinstall still hangs. I'll see if i can create a reproduction scenario on Github, however the issue currently occurs in Azure Pipelines in a private org so can't share my specific setup directly.

**Comment by pmaieref** [comment]
> Yes this should be fixed by [#32027](https://github.com/nrwl/nx/pull/32027)

As others mentioned, I explicitly mentioned the new (not working) code parts and the version I am using in my reply. I am curious how you come to your conclusion and looking forward to an update, thanks.

**Comment by bcerquiare** [comment]
Hi guys, I'm using version 21.5.3 and it keeps freezing on GitHub Actions.

<img width="315" height="230" alt="Image" src="https://github.com/user-attachments/assets/b0225ed2-09ac-4048-9b04-807b3510df15" />

**Comment by Ethan-Kavanagh** [comment]
Any word in this being resolved? Still getting the error on 21.3.11

**Comment by daiscog** [comment]
Still hanging in Github Actions for us in nx `21.6.3`.

**Comment by boywijnmaalen** [comment]
today we ran into this issue as well.

Together with @basvandorst we found a/the solution, wanted to share it here. 

For us the issue occurred when updating some packages (unsure which one was the actual culprit). 

The NX version with which we (started to) experience issue: 21.6.4.

The issue was that NX binaries for all (except the current) architectures had disappeared from the lock file. we manually added the NX binaries for the (for us) required architectures. 

As we run our code directly on Mac as well as Docker containers on various platforms we needed to add more than one architecture. 

possible linked issue; https://github.com/nrwl/nx/issues/32750

We ended up adding these lines to our package.json, after running an initial `npm i` the issue disappeared and our package-lock file looked again the way it should.

```
"optionalDependencies": {
    "@nx/nx-linux-arm64-gnu": "21.6.4", // Docker that runs on MAC
    "@nx/nx-linux-x64-gnu": "21.6.4",     // Docker that runs in our CI/CD
  }
```

Hope it helps anyone

**Comment by pmaieref** [comment]
> today we ran into this issue as well.
> 
> Together with [@basvandorst](https://github.com/basvandorst) we found a/the solution, wanted to share it here.
> 
> For us the issue occurred when updating some packages (unsure which one was the actual culprit).
> 
> The NX version with which we (started to) experience issue: 21.6.4.
> 
> The issue was that NX binaries for all (except the current) architectures had disappeared from the lock file. we manually added the NX binaries for the (for us) required architectures.
> 
> As we run our code directly on Mac as well as Docker containers on various platforms we needed to add more than one architecture.
> 
> possible linked issue; [#32750](https://github.com/nrwl/nx/issues/32750)
> 
> We ended up adding these lines to our package.json, after running an initial `npm i` the issue disappeared and our package-lock file looked again the way it should.
> 
> ```
> "optionalDependencies": {
>     "@nx/nx-linux-arm64-gnu": "21.6.4", // Docker that runs on MAC
>     "@nx/nx-linux-x64-gnu": "21.6.4",     // Docker that runs in our CI/CD
>   }
> ```
> 
> Hope it helps anyone

So it still appears to be the same issue / cause as I already mentioned 7~ weeks ago (https://github.com/nrwl/nx/issues/31649#issuecomment-3258081347). Thanks for verifying!

And up to now, no reaction from @FrozenPandaz or @AgentEnder. I guess the only solution here is to open new ticket(s) until the issue is acknowledged. A bit sad to be honest that tickets are just closed with a "SHOULD be fixed by" comment without actually verifying them.

**Comment by snaits** [comment]
Thanks @boywijnmaalen this got me close enough to getting our CI/CD started again (GitHub actions on Ubuntu). 

In addition to the optional dependencies I had to start the action with deleting node_modules and the lock file.

I'm on 21.6.6 by the way.

**Comment by rryter** [comment]
Please reopen this, still happening  on `21.6.5`.

**Comment by astewartviatech** [comment]
Failed on 21.2 which is how I found this thread. I upgraded to the newest 22.0.2 and am still having the issue

Hangs on this line
`npm info run nx@22.0.2 postinstall node_modules/nx node ./bin/post-install || exit 0`

**Comment by rocketsciencenerd** [comment]
[> these lines to our package.json](https://github.com/nrwl/nx/issues/31649#issuecomment-3426958743)

This worked for me. Thank you @boywijnmaalen!

**Comment by edwardyu-whakaata** [comment]
I am still seeing this issue with 22.1.0.

**Comment by kevindice** [comment]
I am still seeing this with 22.1.3.

**Comment by mohasarc** [comment]
I had a similar issue when installing dependencies within a docker container. switching to `pnpm` fixed the issue.

**Comment by umar-muneer** [comment]
> In addition to the optional dependencies I had to start the action with deleting node_modules and the lock file.

@boywijnmaalen @snaits this worked.. thank you so much !!!
