### ISSUE TITLE
Nx Rollup Executor Windows Build Issue: Invalid tmp Path with Absolute outputPath

### ISSUE THREAD

**Issue by estinsunnyk** [nrwl/nx#31804]
### Current Behavior

When building libraries using Nx with custom Rollup configs (rollup.config.cjs) and the official withNx() helper, the build works fine on macOS/Linux but fails on Windows with an error related to invalid temporary directories.

``Error: ENOENT: no such file or directory, mkdir 'Ç:\Users\myuser\Projects\nx-project\tmp\C:\Users\myuser\Projects\nx-project\libs\ui-comp\button\build'``

**Workaround**
Setting buildLibsFromSource: true in the options passed to withNx() avoids the issue:

``withNx({
  ...,
  buildLibsFromSource: true,
});``

However, this disables Nx's library build cache, resulting in slower builds and losing incremental build benefits.

### Expected Behavior

- Nx should either:
  - Normalize or reject absolute outputPath values for Windows, or
  - Sanitize paths internally to avoid joining tmp with an absolute Windows path.
- Users should be able to use absolute outputPath safely without disabling caching.

### Steps to Reproduce

1. Use Nx workspace with a library containing rollup.config.cjs using withNx().
2. Set outputPath to './dist', main to './src/index.ts' and tsConfig to './tsconfig/lib.json'
3. Run ``npx nx run-many -t build`` on Windows.
4. Observe the mkdir error related to the invalid tmp\C:\... path

### Nx Report

```shell
Node: 22.15.0
OS: win32-x64
Native Target: x86_64-windows
npm: 10.9.2

nx: 21.2.0
@nx/js: 21.2.0
@nx/jest: 21.2.0
@nx/eslint: 21.2.0
@nx/workspace: 21.2.0
@nx/cypress: 21.2.0
@nx/devkit: 21.2.0
@nx/eslint-plugin: 21.2.0
@nx/module-federation: 21.2.0
@nx/next: 21.2.0
@nx/react: 21.2.0
@nx/rollup: 21.2.0
@nx/storybook: 21.2.0
@nx/vite: 21.2.0
@nx/web: 21.2.0
@nx/webpack: 21.2.0
typescript: 5.8.3
-----------------------------
Registered Plugins:
@nx/js/typescript
@nx/next/plugin
@nx/jest/plugin
@nx/eslint/plugin
@nx/react/router-plugin
@nx/rollup/plugin
@nx/storybook/plugin
------------------------------
Cache Usage: 4.60 MB/22.36 GB
```

### Failure Logs

```shell

```

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

### Additional Information

OS: Windows 11 (tested)

**Comment by formatlos** [comment]
it's not just a windows issue. It seems to use an absolute path prepended by the `tmp` folder, which does work on OSX but lead to a tmp directories like `/Users/username/path/to/project/tmp/Users/username/path/to/project/packages/package-name`

**Comment by Coly010** [comment]
this issue was fixed in Nx 21.2.2: https://github.com/nrwl/nx/releases/tag/21.2.2

**Comment by formatlos** [comment]
@Coly010 just upgraded to `21.2.3` and still having the issue

**Comment by Coly010** [comment]
@formatlos please provide a repo with a minimal reproduction

**Comment by formatlos** [comment]
@Coly010 there you go 
https://github.com/formatlos/nx-tmp-path-bug

It's a simple repo boostrapped with the following commands (no manual changes):
```
npx create-nx-workspace@latest
npm install --save-dev @nx/react
npx nx g @nx/react:lib ui --publishable --importPath=@sample/ui --directory=packages/ui --linter=eslint --unitTestRunner=vitest --bundler=rollup --style=none
```

when I'm running `npx nx run-many -t build` (on OSX) the following tmp folders are created:
`/Users/username/path/to/project/tmp/Users/username/path/to/project/packages/ui/build`

This is not really breaking anything at the moment, but still not expected either.
