### ISSUE TITLE
Peer dependency issue with @nx/rspackv21.2.3

### ISSUE THREAD

**Issue by GraceG7** [nrwl/nx#31952]
### Current Behavior

There is a peer dependency issue of the following
├─┬ @nx/angular 21.2.3
│ └─┬ @nx/rspack 21.2.3
│   └── ✕ unmet peer @module-federation/enhanced@^0.15.0: found 0.16.0

However after inspecting the pnpm-lock.yaml file as follows, i think the peerDependencies just need to updated to the correct version that is being installed?
```  
'@nx/rspack@21.2.3':
    resolution: {integrity: sha512-4BZYaGfdVpak8DXGlUEmDfu04vZ45oaeXptyCh9mx8F6WjJozns7jPXSymexrdLp38XoNClVQCXDU/b/Ugt0uw==}
    peerDependencies:
      '@module-federation/enhanced': ^0.15.0
      '@module-federation/node': ^2.6.26

  '@nx/rspack@21.2.3(@babel/traverse@7.28.0)(@module-federation/enhanced@0.16.0(@rspack/core@1.4.6(@swc/helpers@0.5.17))(react-dom@19.1.0(react@19.1.0))(react@19.1.0)(typescript@5.8.3)(webpack@5.100.1(@swc/core@1.12.11(@swc/helpers@0.5.17))(esbuild@0.25.6)))(@module-federation/node@2.7.8(@rspack/core@1.4.6(@swc/helpers@0.5.17))(react-dom@19.1.0(react@19.1.0))(react@19.1.0)(typescript@5.8.3)(webpack@5.100.1(@swc/core@1.12.11(@swc/helpers@0.5.17))(esbuild@0.25.6)))(@swc-node/register@1.10.10(@swc/core@1.12.11(@swc/helpers@0.5.17))(@swc/types@0.1.23)(typescript@5.8.3))(@swc/core@1.12.11(@swc/helpers@0.5.17))(@swc/helpers@0.5.17)(@types/express@4.17.23)(esbuild@0.25.6)(less@4.1.3)(nx@21.2.3(@swc-node/register@1.10.10(@swc/core@1.12.11(@swc/helpers@0.5.17))(@swc/types@0.1.23)(typescript@5.8.3))(@swc/core@1.12.11(@swc/helpers@0.5.17)))(react-dom@19.1.0(react@19.1.0))(react-refresh@0.17.0)(react@19.1.0)(typescript@5.8.3)(webpack-hot-middleware@2.26.1)':
    dependencies:
      '@module-federation/enhanced': 0.16.0(@rspack/core@1.4.6(@swc/helpers@0.5.17))(react-dom@19.1.0(react@19.1.0))(react@19.1.0)(typescript@5.8.3)(webpack@5.100.1(@swc/core@1.12.11(@swc/helpers@0.5.17))(esbuild@0.25.6))
      '@module-federation/node': 2.7.8(@rspack/core@1.4.6(@swc/helpers@0.5.17))(react-dom@19.1.0(react@19.1.0))(react@19.1.0)(typescript@5.8.3)(webpack@5.100.1(@swc/core@1.12.11(@swc/helpers@0.5.17))(esbuild@0.25.6))
      '@nx/devkit': 21.2.3(nx@21.2.3(@swc-node/register@1.10.10(@swc/core@1.12.11(@swc/helpers@0.5.17))(@swc/types@0.1.23)(typescript@5.8.3))(@swc/core@1.12.11(@swc/helpers@0.5.17)))
      '@nx/js': 21.2.3(@babel/traverse@7.28.0)(@swc-node/register@1.10.10(@swc/core@1.12.11(@swc/helpers@0.5.17))(@swc/types@0.1.23)(typescript@5.8.3))(@swc/core@1.12.11(@swc/helpers@0.5.17))(nx@21.2.3(@swc-node/register@1.10.10(@swc/core@1.12.11(@swc/helpers@0.5.17))(@swc/types@0.1.23)(typescript@5.8.3))(@swc/core@1.12.11(@swc/helpers@0.5.17)))
      '@nx/module-federation': 21.2.3(@babel/traverse@7.28.0)(@swc-node/register@1.10.10(@swc/core@1.12.11(@swc/helpers@0.5.17))(@swc/types@0.1.23)(typescript@5.8.3))(@swc/core@1.12.11(@swc/helpers@0.5.17))(@swc/helpers@0.5.17)(esbuild@0.25.6)(nx@21.2.3(@swc-node/register@1.10.10(@swc/core@1.12.11(@swc/helpers@0.5.17))(@swc/types@0.1.23)(typescript@5.8.3))(@swc/core@1.12.11(@swc/helpers@0.5.17)))(react-dom@19.1.0(react@19.1.0))(react@19.1.0)(typescript@5.8.3)
      '@nx/web': 21.2.3(@babel/traverse@7.28.0)(@swc-node/register@1.10.10(@swc/core@1.12.11(@swc/helpers@0.5.17))(@swc/types@0.1.23)(typescript@5.8.3))(@swc/core@1.12.11(@swc/helpers@0.5.17))(nx@21.2.3(@swc-node/register@1.10.10(@swc/core@1.12.11(@swc/helpers@0.5.17))(@swc/types@0.1.23)(typescript@5.8.3))(@swc/core@1.12.11(@swc/helpers@0.5.17)))
      '@phenomnomnominal/tsquery': 5.0.1(typescript@5.8.3)
      '@rspack/core': 1.4.6(@swc/helpers@0.5.17)
      '@rspack/dev-server': 1.1.3(@rspack/core@1.4.6(@swc/helpers@0.5.17))(@types/express@4.17.23)(webpack@5.100.1(@swc/core@1.12.11(@swc/helpers@0.5.17))(esbuild@0.25.6))
      '@rspack/plugin-react-refresh': 1.4.3(react-refresh@0.17.0)(webpack-hot-middleware@2.26.1)
     
```

### Expected Behavior

No peer dependency issues

### Steps to Reproduce

Upgrade @nx/angular to version 21.2.3

### Nx Report

```shell
NX   Report complete - copy this into the issue template

Node           : 22.17.0
OS             : win32-x64
Native Target  : x86_64-windows
pnpm           : 10.11.0

nx (global)        : 20.8.1
nx                 : 21.2.3
@nx/js             : 21.2.3
@nx/jest           : 21.2.3
@nx/eslint         : 21.2.3
@nx/workspace      : 21.2.3
@nx/angular        : 21.2.3
@nx/devkit         : 21.2.3
@nx/eslint-plugin  : 21.2.3
@nx/nest           : 21.2.3
@nx/node           : 21.2.3
@nx/playwright     : 21.2.3
@nx/plugin         : 21.2.3
@nx/storybook      : 21.2.3
@nx/web            : 21.2.3
@nx/webpack        : 21.2.3
typescript         : 5.8.3
---------------------------------------
Community plugins:
@auth0/auth0-angular                : 2.2.3
@nx-extend/firebase-hosting         : 8.2.0
@nx-tools/nx-prisma                 : 6.8.0
@progress/kendo-angular-buttons     : 19.2.0
@progress/kendo-angular-dateinputs  : 19.2.0
@progress/kendo-angular-dropdowns   : 19.2.0
@progress/kendo-angular-gauges      : 19.2.0
@progress/kendo-angular-grid        : 19.2.0
@progress/kendo-angular-icons       : 19.2.0
@progress/kendo-angular-indicators  : 19.2.0
@progress/kendo-angular-inputs      : 19.2.0
@progress/kendo-angular-intl        : 19.2.0
@progress/kendo-angular-l10n        : 19.2.0
@progress/kendo-angular-label       : 19.2.0
@progress/kendo-angular-navigation  : 19.2.0
@progress/kendo-angular-pager       : 19.2.0
@progress/kendo-angular-pdf-export  : 19.2.0
@progress/kendo-angular-popup       : 19.2.0
@progress/kendo-angular-progressbar : 19.2.0
@progress/kendo-angular-scheduler   : 19.2.0
@progress/kendo-angular-scrollview  : 19.2.0
@progress/kendo-angular-toolbar     : 19.2.0
@progress/kendo-angular-tooltip     : 19.2.0
@progress/kendo-angular-utils       : 19.2.0
@rx-angular/cdk                     : 20.0.0
@rx-angular/state                   : 20.0.0
@rx-angular/template                : 20.0.0
@storybook/angular                  : 9.0.17
angular-eslint                      : 20.1.1
ng2-charts                          : 8.0.0
---------------------------------------
Local workspace plugins:
@thred/plugin
---------------------------------------
Cache Usage: 0.00 B / 92.92 GB
```

### Failure Logs

```shell

```

### Operating System

- [ ] macOS
- [ ] Linux
- [x] Windows
- [ ] Other (Please specify)

**Comment by Coly010** [comment]
Fixed as part of: https://github.com/nrwl/nx/pull/31924

**Comment by GraceG7** [comment]
I still get peer dependency issue upgrading to v21.2.4

@nx/angular 21.2.4
├─┬ @nx/module-federation 21.2.4
│ ├── @module-federation/enhanced 0.15.0
│ └─┬ @module-federation/node 2.7.9
│ └── @module-federation/enhanced 0.17.0
└─┬ @nx/rspack 21.2.4
├── @module-federation/enhanced 0.17.0 peer
├─┬ @module-federation/node 2.7.9 peer
│ └── @module-federation/enhanced 0.17.0
└─┬ @nx/module-federation 21.2.4
├── @module-federation/enhanced 0.15.0
└─┬ @module-federation/node 2.7.9
└── @module-federation/enhanced 0.17.0

├─┬ @nx/angular 21.2.4
│ └─┬ @nx/rspack 21.2.4
│ └── ✕ unmet peer @module-federation/enhanced@^0.15.0: found 0.17.0


Should @nx/rxpack update its peer dependency range for @module-federation/enhanced?

Following is found in m pnpm-lock file
  '@nx/rspack@21.2.4':
    resolution: {integrity: sha512-mSRi2ZUW+uhpA9Fm52f4R23X2KOV/BlWFm+6C5em8AYK871fZM1V0RTP4TTFiCIMjFs4o2rzremnjcIfMXIDKg==}
    peerDependencies:
      '@module-federation/enhanced': ^0.15.0
      '@module-federation/node': ^2.6.26

@Coly010
