### ISSUE TITLE
Getting 'Collection "@nrwl/angular" cannot be resolved' when running workspace-schematic

### ISSUE THREAD

**Issue by decline** [nrwl/nx#3233]
## Current Behavior
When running `npm run workspace-schematic -- {{ my-schematic-name }}` the following error is appearing:

```
Error: Collection "@nrwl/angular" cannot be resolved.
```

## Expected Behavior
The schematic should run through successfully.

## Steps to Reproduce
I created a simple [GitHub repository](https://github.com/decline/nrwl-schematics-demo) so you can reproduce this:

```
git clone git@github.com:decline/nrwl-schematics-demo.git
```

```
cd nrwl-schematics-demo && npm install
```

```
npm run workspace-schematic -- test
```

Then in the interactive dialog just select "ui" for example and use "foobar" as the directory name

### Failure Logs
```
Error: Collection "@nrwl/angular" cannot be resolved.
    at NodeModulesEngineHost.resolve (/Users/dom/Desktop/nrwl-schematics-demo/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:74:19)
    at NodeModulesEngineHost._resolveCollectionPath (/Users/dom/Desktop/nrwl-schematics-demo/node_modules/@angular-devkit/schematics/tools/node-module-engine-host.js:79:37)
    at NodeModulesEngineHost.createCollectionDescription (/Users/dom/Desktop/nrwl-schematics-demo/node_modules/@angular-devkit/schematics/tools/file-system-engine-host-base.js:109:27)
    at SchematicEngine._createCollectionDescription (/Users/dom/Desktop/nrwl-schematics-demo/node_modules/@angular-devkit/schematics/src/engine/engine.js:147:40)
    at SchematicEngine.createCollection (/Users/dom/Desktop/nrwl-schematics-demo/node_modules/@angular-devkit/schematics/src/engine/engine.js:140:43)
    at /Users/dom/Desktop/nrwl-schematics-demo/node_modules/@angular-devkit/schematics/src/rules/schematic.js:23:43
    at MergeMapSubscriber.project (/Users/dom/Desktop/nrwl-schematics-demo/node_modules/@angular-devkit/schematics/src/rules/call.js:74:24)
    at MergeMapSubscriber._tryNext (/Users/dom/Desktop/nrwl-schematics-demo/node_modules/rxjs/internal/operators/mergeMap.js:69:27)
    at MergeMapSubscriber._next (/Users/dom/Desktop/nrwl-schematics-demo/node_modules/rxjs/internal/operators/mergeMap.js:59:18)
    at MergeMapSubscriber.Subscriber.next (/Users/dom/Desktop/nrwl-schematics-demo/node_modules/rxjs/internal/Subscriber.js:66:18)
```

### Environment
  @nrwl/angular : 9.4.5
  @nrwl/cli : 9.4.5
  @nrwl/cypress : 9.4.5
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 9.4.5
  @nrwl/linter : Not Found
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 9.4.5
  @nrwl/web : Not Found
  @nrwl/workspace : 9.4.5
  typescript : 3.8.3

**Comment by borisd** [comment]
Had the same issue, resolved by upgrading node to latest (14.4.0)

**Comment by rarmatei** [comment]
reopening this as the issue is still there - can replicate when invoking a workspace schematic on windows

**Comment by jonparker** [comment]
I am getting the same issue on MacOS after running `nx generate @nrwl/angular:application my-app`
and selecting the empty option. Then running `nx generate @nrwl/angular:application my-app` inside the folder.

Node version: v12.18.2
NPM version: 6.14.6
NX version: 10.0.7

**Comment by nyds** [comment]
Confirmed. Calling external schematics from a workspace schematic results in unresolved collection errors.

**Comment by filipgorny** [comment]
I have the same issue, what helped me was:
`npm i @nrwl/angular`

**Comment by VaultDeveloper** [comment]
@filipgorny Good to know. It was indeed the "good solution".
