### ISSUE TITLE
Custom commands arguments is not working well

### ISSUE THREAD

**Issue by nestorvanz** [nrwl/nx#3245]
I trying to create a custom script following the next documentation: https://nx.dev/angular/plugins/workspace/builders/run-commands#examples.

The option `nx run frontend:create-script --name=example` is not working.

### Workspace configuration
```json
"create-script": {
  "builder": "@nrwl/workspace:run-commands",
  "options": {
    "commands": [
      "mkdir -p scripts",
      "touch scripts/{args.name}.sh",
      "chmod +x scripts/{args.name}.sh"
    ],
    "cwd": "apps/issue",
    "parallel": false
  }
}
```

### Result
![image](https://user-images.githubusercontent.com/12944703/85906633-1dd60c80-b7cc-11ea-8b16-525d9ef5a9b1.png)

**Comment by Hotell** [comment]
I guess this was fixed ( works with 9.5.1)

**architect**
```
"echo": {
          "builder": "@nrwl/workspace:run-commands",
          "options": {
            "command": "echo '{args.what}'"
          }
        }
```

![2020-07-13 at 10 58 AM](https://user-images.githubusercontent.com/1223799/87285539-e8356100-c4f7-11ea-8d6a-9c08639fb8dc.png)

**Comment by mathpaquette** [comment]
@Hotell are you sure??, I'm on 9.5.1 and still doesn't work....

**Comment by Hotell** [comment]
> @Hotell are you sure??, I'm on 9.5.1 and still doesn't work....

What doesn't work? Can you be please more specific? I provided real life example that works 😁🙏

**Comment by mathpaquette** [comment]
Haha, tried your examples without any luck.

Basically with —args no issues with the parameter switch got undefined

Sent from my iPhone

On Aug 11, 2020, at 2:29 AM, Martin Hochel <notifications@github.com> wrote:

﻿

@Hotell<https://github.com/Hotell> are you sure??, I'm on 9.5.1 and still doesn't work....

What doesn't work? Can you be please more specific? I provided real life example that works 😁🙏

**Comment by bekos** [comment]
@nestorvanz  @mathpaquette I tried to execute both the initial scenario and what @Hotell mentioned and seems to be working fine. Can you please provide any further information or an example repo in order to better understand the cause?
