### ISSUE TITLE
Link to package for gcs cache is dead

### ISSUE THREAD

**Issue by Stanzilla** [nrwl/nx#32835]
### Documentation issue

- [ ] Reporting a typo
- [x] Reporting a documentation bug
- [ ] Documentation improvement
- [ ] Documentation feedback

### Is there a specific documentation page you are reporting?

https://nx.dev/reference/core-api/gcs-cache

### Additional context or description

Provide any additional details here as needed.

Link to GitHub is 404

**Comment by Stanzilla** [comment]
Also where does the code for it live? The npm page points to https://nx.dev/nx-api/gcs-cache but there is no source link and I can't find changelogs either.

**Comment by jaysoo** [comment]
We moved the docs and missed this redirect. It is fixed now.

**Comment by Stanzilla** [comment]
> We moved the docs and missed this redirect. It is fixed now.

Thanks but could you please put a link to the source of the code and maybe release notes there as well? I still don't know what changed in 4.0.0, there are no release notes at all. No changelog.md in the package itself either https://www.npmjs.com/package/@nx/gcs-cache?activeTab=code
