### ISSUE TITLE
Dev server started with @nx/next executor does not correctly escape env variables with '$'

### ISSUE THREAD

**Issue by nanometre** [nrwl/nx#33409]
### Current Behavior

After migrating an Nx monorepo from v17 to v21, an issue was discovered with Next.js environment variable escaping. In projects built with Next.js within the monorepo, environment variables containing a dollar sign (`$`) are not being escaped correctly when dev server is started with `@nx/next` executor. [According to Next.js documentation](https://nextjs.org/docs/14/pages/building-your-application/configuring/environment-variables#referencing-other-variables), a backslash (`\`) should be used to escape the dollar sign (e.g., `\$`). Post-migration, it was observed that all characters following `\$` were being completely removed from the environment variable value.

<img width="1662" height="1844" alt="Image" src="https://github.com/user-attachments/assets/21c3de47-5fe4-4575-8fc6-a3ea6378e13a" />

The last known working version is `@nx/next@18.x` Running the Next.js dev server directly (bypassing the Nx executor, e.g., using next dev inside the app directory) does not exhibit the same escaping problem.

<img width="1662" height="1696" alt="Image" src="https://github.com/user-attachments/assets/dc467217-c980-48d1-89d7-17d6f34c0d6c" />

### Expected Behavior

The `ESCAPED_VARIABLE` environment variable should retain the full, un-truncated value when dev server is started with `@nx/next` executor: `escaped_$value`

### Steps to Reproduce

1. Initialise Nx monorepo with Next.js application
2. In an environment file (e.g., apps/my-app/.env.local), define a variable requiring a literal dollar sign, escaped with a backslash e.g. `SECRET_KEY="abc-123-\$xyz-789"`
3. Attempt to access this variable within the Next.js process (e.g., in a server-side component or next.config.js): `console.log(process.env.SECRET_KEY);`
4. Run the application using the Nx's Next.js executor

### Nx Report

```shell
Node           : 22.17.1
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 10.13.1

nx                     : 21.6.2
@nx/js                 : 21.6.2
@nx/jest               : 21.6.2
@nx/linter             : 18.3.5
@nx/eslint             : 21.6.2
@nx/workspace          : 21.6.2
@nx/cypress            : 21.6.2
@nx/devkit             : 21.6.2
@nx/eslint-plugin      : 21.6.2
@nx/module-federation  : 21.6.2
@nx/next               : 21.6.2
@nx/react              : 21.6.2
@nx/rollup             : 21.6.2
@nx/storybook          : 21.6.2
@nx/vite            Node           : 22.17.1
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 10.13.1

nx                     : 21.6.2
@nx/js                 : 21.6.2
@nx/jest               : 21.6.2
@nx/eslint             : 21.6.2
@nx/workspace          : 21.6.2
@nx/devkit             : 22.0.2
@nx/eslint-plugin      : 21.6.2
@nx/module-federation  : 22.0.2
@nx/next               : 21.6.2
@nx/react              : 22.0.2
@nx/rollup             : 22.0.2
@nx/vite               : 22.0.2
@nx/web                : 22.0.2
@nx/webpack            : 22.0.2
typescript             : 5.9.3
---------------------------------------
Registered Plugins:
@nx/js/typescript
@nx/next/plugin
@nx/jest/plugin
@nx/eslint/plugin
---------------------------------------
Cache Usage: 0.00 B / 46.04 GB
---------------------------------------
The following packages should match the installed version of nx
  - @nx/devkit@22.0.2
  - @nx/module-federation@22.0.2
  - @nx/react@22.0.2
  - @nx/rollup@22.0.2
  - @nx/vite@22.0.2
  - @nx/web@22.0.2
  - @nx/webpack@22.0.2

To fix this, run `nx migrate nx@22.0.2`
```

### Failure Logs

```shell

```

### Operating System

- [x] macOS
- [ ] Linux
- [ ] Windows
- [ ] Other (Please specify)

**Comment by nanometre** [comment]
This issue seems to be caused by the update of `dotenv-expand` dependency from `v10.0.0` to `v11.x`

**Comment by nanometre** [comment]
This issue could be caused by usage of `dotenv-expand` library. 

Same issue was raised in `dotenv-expand` which was fixed in version 11.0.0 (https://github.com/motdotla/dotenv-expand/issues/101) and `nx@21` uses `dotenv-expand@11.x`

**Comment by Coly010** [comment]
This issue appears to be related to the dotenv-expand library's handling of $ characters. The underlying issue was fixed in dotenv-expand v11.0.0 (see motdotla/dotenv-expand#101).

Nx 21+ uses dotenv-expand@11.x which includes this fix. If you're experiencing this issue:

Please ensure you're on the latest version of Nx
If the issue persists on the latest version, please let us know with your nx report output
Closing as this appears to be resolved by the upstream dependency update. Please reopen if you're still experiencing this on the latest Nx version.

**Comment by nanometre** [comment]
I am still facing the same problem. I cannot reopen the issue because it says I do not have permission.

Sharing the nx report output again:
```
Node           : 22.17.1
OS             : darwin-arm64
Native Target  : aarch64-macos
pnpm           : 10.13.1

nx                     : 21.6.2
@nx/js                 : 21.6.2
@nx/jest               : 21.6.2
@nx/eslint             : 21.6.2
@nx/workspace          : 21.6.2
@nx/cypress            : 21.6.2
@nx/devkit             : 21.6.2
@nx/eslint-plugin      : 21.6.2
@nx/module-federation  : 21.6.2
@nx/next               : 21.6.2
@nx/react              : 21.6.2
@nx/rollup             : 21.6.2
@nx/storybook          : 21.6.2
@nx/vite               : 21.6.2
@nx/web                : 21.6.2
@nx/webpack            : 21.6.2
typescript             : 5.2.2
---------------------------------------
Cache Usage: 80.57 KB / 46.04 GB
```

**Comment by nanometre** [comment]
@FrozenPandaz @Coly010 please help to reopen this issue

**Comment by Coly010** [comment]
@nanometre Please use the latest version of Nx and if still encountering the issue provide a minimal repo that reproduces this issue

**Comment by nanometre** [comment]
Sharing the minimal repo [here](https://github.com/nanometre/nx-next-env-minimal-repo). In the minimal repo, I used nx v22. But this issue is present it v19+ onwards

Steps to take:
1. `npm install`
2. `npx nx dev org`
3. Notice in the terminal that the environment variables get truncated.

**Comment by nanometre** [comment]
@Coly010 did you get the chance to check out the minimal repo?

**Comment by nanometre** [comment]
@Coly010 @FrozenPandaz 
are there any updates after i have provided the minimal repo?
