### ISSUE TITLE
Cannot terminate the dev server process with `Ctrl+C` while running `nx serve <app-name>`

### ISSUE THREAD

**Issue by vlodko** [nrwl/nx#3348]
## Steps to Reproduce
1. Start dev server using `nx serve <app-name>` in Zsh or Bash
2. Server starts on port:4200
3. Use *Ctrl+C* to stop the process

## Current Behavior
4. The server is still running on the same port.
When you try to start the dev server again the following error appears:
```
[error] Error: Port 4200 is already in use. Use '--port' to specify a different port.
    at Server.<anonymous> (......./node_modules/@angular-devkit/build-angular/src/angular-cli-files/utilities/check-port.js:27:28)
    at Object.onceWrapper (events.js:417:26)
    at Server.emit (events.js:310:20)
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Note:** using `ng serve <app-name>` works as expected

## Expected Behavior
4. The process is terminated after pressing *Ctrl+C*
When you start a server again the port is available for use

### Environment
OS: macOS
Shell: Zsh, Bash

*nx report:*
```
 @nrwl/angular : 9.5.1
  @nrwl/cli : 9.5.1
  @nrwl/cypress : 9.5.1
  @nrwl/jest : 9.5.1
  @nrwl/tao : 9.5.1
  @nrwl/workspace : 9.5.1
  typescript : 3.8.3
```

**Comment by FrozenPandaz** [comment]
This issue should be fixed with Nx 10 in #3330.

We plan on backporting this fix to `v9.6` as well if you can't update right away.

**Comment by vsavkin** [comment]
@vlodko what version of Node are you using? Also, could you provide a repo with a repro?

**Comment by vlodko** [comment]
thanks @FrozenPandaz @vsavkin 
I'm using node v12.16.3.
Sorry, we haven't migrated to Angular 10 and Nx 10 yet, so I can't verify the fix as of now.

**Comment by vsavkin** [comment]
@vlodko could you provide a repo with a repro using Nx 9.5.1?

**Comment by vsavkin** [comment]
The issue has been fixed in Nx 9.6 and Nx 10.1. I'm sorry it took so long to get this right.

**Comment by vlodko** [comment]
@vsavkin thank you!

**Comment by JKancel** [comment]
Hi,

I'm still encounter this issue in my Nx + Nextjs project with following dependency: `"@nrwl/next": "13.5.2"`

**Comment by nurbashanghai** [comment]
same here

**Comment by cwilliamson226** [comment]
I'm seeing this as well with `13.5.1`, would love to figure out some kind of fix

**Comment by iwarner** [comment]
Still present also in 13.5.2

[ ready ] on http://localhost:4200
error - uncaughtException: Error: listen EADDRINUSE: address already in use :::4200

**Comment by jacobkellas** [comment]
NX 14.7.5 I've run my server on localhost:8080 and now no matter what I do I can't use that port.  It still tries to serve up that application.  I've killed every PID resembling 8080 and they come back.  Shut down my machine and it still tries to serve the app.  Any tips?

**Comment by adam-marshall** [comment]
this has started happening for me since upgrading from `"@nrwl/cli": "14.3.6"` to `"@nrwl/cli": "14.7.8"`. 

It was fine on 14.3.

**Comment by eddsaura** [comment]
Same error here.

**Comment by PluralRocket** [comment]
Noticed the same error.

**Comment by STih07** [comment]
Same thing
```
nx --version
14.8.3

node -v
v14.20.0
```

OS: MacOS Monterey 12.2.1 (Intel based)

Please, reopen

**Comment by goofiw** [comment]
This is happening to us as well on nx version 14.7.6 and node v16.14.0

**Comment by exsesx** [comment]
This also occurs on nx version 15, and the node version doesn't really matter, IG.

**Comment by chicken-suop** [comment]
@vsavkin This is still happening

**Comment by Flip-Liquid** [comment]
@vsavkin @FrozenPandaz 
still happening in nx v 14.7.13 node v 16.10.0

**Comment by turboninh** [comment]
Mine was caused by version mismatching between the monorepos. Try to update all the `nrwl/next` packages to the same version :)

**Comment by goofiw** [comment]
@turboninh I'm not sure what you mean - do you have multiple nx monorepos?

We do not use a globally installed version of nx when running generators and commands. i.e. something like `yarn nx serve api` so it should only be using the locally install version in the package json of `@nrwl/next`

**Comment by julienboulay** [comment]
This bug occurs for me with nx 14.8.3 when upgrading node from 16.17.1 to 16.18.1.
I use [n](https://www.npmjs.com/package/n) to manage node version.
I switched back to 16.17.1 and then 16.18.1, and now, `Ctrl+C` is working as before
