### ISSUE TITLE
create-nx-workspace uses hard @angular/cli version instead of the version defined in https://github.com/nrwl/nx/blob/master/packages/workspace/src/utils/versions.ts

### ISSUE THREAD

**Issue by gkamperis** [nrwl/nx#3835]
## Current Behavior
create-nx-workspace uses exact version 10.0.3 of the @angular/cli - seems to come from the version of it in the repo's package.json.

## Expected Behavior

I'd expect the command to use the @angular/cli version of the schematics defined in
https://github.com/nrwl/nx/blob/master/packages/workspace/src/utils/versions.ts which is a more lenient ~10.0.0.

## Steps to Reproduce
To reproduce not all NPM packages should be available for example an Artifactory repo. 

So version 10.0.0 and 10.0.4 is available but not 10.0.3 and even though I should be ok with the generation of the workspace and the schematics, I have a failure.

### Failure Logs
No failure logs!

And this is quite annoying as 
function createSandbox(packageManager: string) 
calls 
npm install --silent 

in create-nx-workspace 

and when this fails everything on the cache\_npx directory is wiped out.

This also has as a result for npm to not write out any logs which actually contain the meaningful information of what package is missing.

I have to resort to some really tedious process in order to get logs dumped:
pause the create-nx-workspace process.
go to the staging directory and edit create-nx-workspace.js to remove the --silent argument 
and then resume the process!!!

Maybe there is a simpler process that I am not aware of, but --verbose does really nothing and getting meaningful failure logs should not be this difficult

Maybe a feature request but there should be logs for failures like these.

Thanks

### Environment
Windows.
Nx 10+

**Comment by FrozenPandaz** [comment]
I believe this is already fixed in Nx 10.2.1 with this commit https://github.com/nrwl/nx/commit/07ba927ed7f076b80c026be4ab27ba87ba235688 where `@angular/cli` isn't in the sandbox at all.

@gkamperis could you please retry with the latest version?

**Comment by gkamperis** [comment]
@FrozenPandaz 
I can still see this

`const angularCliVersion = 'ANGULAR_CLI_VERSION';`

determineCli() still uses it. How is this populated?

Can it be different to the version defined in
https://github.com/nrwl/nx/blob/master/packages/workspace/src/utils/versions.ts 
?

Or is it just a placeholder value never actually replaced? 

I would also like to stress the issue with the failure logs and the 

` execSync(`${packageManager} install --silent``

Can the --silent be removed? what is the downside for the processing if it is not there?
Its usage wipes and does not create any logs which are actually necessary to troubleshoot missing versions.

**Comment by gkamperis** [comment]
@FrozenPandaz I cannot try it as the required packages are now available and 10.2.1 is not. Can you pls clarify the questions in my previous comment?
