### ISSUE TITLE
Migration to ESlint

### ISSUE THREAD

**Issue by hoisel** [nrwl/nx#4320]
I have a nx workspace already configured with TSlint and I've migrated to nx 11 recently.
How do I migrate to ESLint? [angular-eslint](https://github.com/angular-eslint/angular-eslint#usage-with-nx-monorepos) instruct us to follow nx path in order to migrate properly. Which path would it be? I couldn't find it anywhere.

### Environment
``` Node : 12.14.0
  OS   : linux x64
  npm  : 6.13.4
  
  nx : Not Found
  @nrwl/angular : 11.0.4
  @nrwl/cli : 11.0.4
  @nrwl/cypress : 11.0.4
  @nrwl/devkit : 11.0.4
  @nrwl/eslint-plugin-nx : Not Found
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.4
  @nrwl/linter : 11.0.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.4
  @nrwl/web : Not Found
  @nrwl/workspace : 11.0.4
  typescript : 4.0.5```

**Comment by KingDarBoja** [comment]
There is a good article recently published by @LayZeeDK for migrating to ESLint in the meantime: [The ultimate migration guide to angular-eslint, ESLint and Nx 11](https://dev.to/this-is-angular/the-ultimate-migration-guide-to-angular-eslint-eslint-and-nx-11-1eh2)

**Comment by LayZeeDK** [comment]
@JamesHenry (the author of angular-eslint) is currently working on a migration from TSLint to ESLint+angular-eslint in Nx workspaces. A few days ago, he said that he estimated that he was about 85% done, so follow the semi-automated migration instructions in my guide mentioned by @KingDarBoja or wait until the migration is ready 🙂

**Comment by sameera** [comment]
Hey @LayZeeDK 
I was following your post but, at the point of running the batch script, I started running in to:
```
Unable to resolve @angular-eslint/schematics:convert-tslint-to-eslint.
Cannot find module '@angular-devkit/core'
```
Any ideas on how I can resolve this?

**Comment by LayZeeDK** [comment]
@sameera, based on the error message, I guess you need to `npm install --save-dev @angular-devkit/core` even though I've never had to add that package explicitly. Which version of Nx are you using?

**Comment by sameera** [comment]
Thanks @LayZeeDK 
I'm on NX 11.0.12

However, the problem had been that I had mistakenly uninstalled `codelyzer` prior to running the batch script. This was resolved by installing it. Sorry for the noise.

**Comment by sameera** [comment]
I did get this working thanks to @LayZeeDK 's post.
However, I needed to do few more things:

1. Add `plugin:import/errors`, `plugin:import/typescript` to `extends` in order to get `imports/order` working.
2. Add `"import/no-unresolved": "off",` (as nothing [here ](https://stackoverflow.com/questions/55198502/using-eslint-with-typescript-unable-to-resolve-path-to-module) worked)

However, I had to add the following to each project's `.eslintrc.json` file to get rid of 
` Strings must use singlequote` error.

```
    "quotes": [
        "error",
        "double",
        { "avoidEscape": true, "allowTemplateLiterals": true }
    ]
```

Is this expected? Why isn't adding it in the `.eslintrc.json` at the repo's root work?

**Comment by sameera** [comment]
> Is this expected? Why isn't adding it in the `.eslintrc.json` at the repo's root work?

I realized this is because in each of the derived `.eslintrc.json` we have this part:
```
"extends": [
        "plugin:@nrwl/nx/angular",
        "plugin:@angular-eslint/template/process-inline-templates"
      ]
```
with a `files:["*.ts"]` filter. 

I have resolved this by moving these extends to the root. This allows me to clean up all of the derived configs keeping only the `@angular-eslint/component-selector` and `@angular-eslint/directive-selector` rules in libs where there are actual Angular components.

**Comment by JamesHenry** [comment]
@sameera There is a very good reason why we use overrides, so I would not recommend what you have done.

I would recommend reading my write up on ESLint configs for Angular projects in the angular-eslint project here: https://github.com/angular-eslint/angular-eslint#notes-on-eslint-configuration

Not everything in that README is 100% applicable to Nx workspaces, but the fundamentals of ESLint config structure are the same.

Adding rules to the root .eslintrc.json works just fine, you just need to add it into an appropriate override block for the files you want it to apply to

**Comment by JamesHenry** [comment]
PR #4328 is open which adds the automated migration of TSLint projects to ESLint, it should be merged soon so IMO it is worth holding off on manual efforts for now

**Comment by sameera** [comment]
@JamesHenry very sorry for the confusion: By root, I meant the `eslintrc.json` at the root of the Nx workspace. Not the root of the json object :)

**Comment by JamesHenry** [comment]
Ah ok cool, that's definitely better than what I initially understood 👍 

Nevertheless, there is an important thing to note about applying things in the root config at all as well (and it's the reason we apply angular preset configs on a project level) - Nx by it's nature is multi-framework (and even multi-environment when you consider its OOTB node support etc).

Therefore it is very common for an Nx workspace to contain an Angular project, and a Node project, for example. Even if this is not something you have now, Nx would allow you to trivially add it in future.

However, if you make your root configs more Angular specific, then you will lose some of that flexibility because linting Angular projects is pretty different to React/Node/Express projects, for example.

Hope that makes sense

**Comment by sameera** [comment]
Yup @JamesHenry 
Totally makes sense.

**Comment by sameera** [comment]
So, I guess the right thing to do, would be to write a custom config deriving `@nrwl/nx/angular` and extend that on a per-project level so that we need not repeat the same rules in each Angular project.

**Comment by DuncanFaulkner** [comment]
I upgraded to Angular 11 and followed this guide (see below) to upgrade tslint to eslint all seem to upgrade OK, except when I try and run `nx run-many --target=lint --all` I get the following error:

SyntaxError: Unexpected token } in JSON at position 681
    at JSON.parse (<anonymous>)
    at Object.parseJsonWithComments (/home/duncan.faulkner/development/integra-frontend/node_modules/@nrwl/workspace/src/utils/fileutils.js:44:17)
    at new TargetProjectLocator (/home/duncan.faulkner/development/integra-frontend/node_modules/@nrwl/workspace/src/core/target-project-locator.js:22:46)
    at buildExplicitTypeScriptDependencies (/home/duncan.faulkner/development/integra-frontend/node_modules/@nrwl/workspace/src/core/project-graph/build-dependencies/explicit-project-dependencies.js:8:34)
    at /home/duncan.faulkner/development/integra-frontend/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:60:41
    at Array.forEach (<anonymous>)
    at buildProjectGraph (/home/duncan.faulkner/development/integra-frontend/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:60:26)
    at Object.createProjectGraph (/home/duncan.faulkner/development/integra-frontend/node_modules/@nrwl/workspace/src/core/project-graph/project-graph.js:40:30)
    at Object.<anonymous> (/home/duncan.faulkner/development/integra-frontend/node_modules/@nrwl/workspace/src/command-line/run-many.js:17:46)
    at Generator.next (<anonymous>)


Guide:
https://dev.to/this-is-angular/the-ultimate-migration-guide-to-angular-eslint-eslint-and-nx-11-1eh2#migrating-an-existing-nx-10-angular-workspace-using-tslint

**Comment by LayZeeDK** [comment]
Hi @DuncanFaulkner,

Can you run `nx report` and paste your `workspace.json` or `angular.json` as well as your root `.eslintrc.json`?

Error indicates a syntax error in either your workspace configuration or one of your `.eslintrc.json` configuration files.

**Comment by DuncanFaulkner** [comment]
@LayZeeDK 
>  NX  Report complete - copy this into the issue template

  Node : 14.15.3
  OS   : linux x64
  npm  : 6.14.9
  
  nx : Not Found
  @nrwl/angular : 11.0.18
  @nrwl/cli : 11.0.18
  @nrwl/cypress : 11.0.18
  @nrwl/devkit : 11.0.18
  @nrwl/eslint-plugin-nx : 11.0.18
  @nrwl/express : Not Found
  @nrwl/jest : 11.0.18
  @nrwl/linter : 11.0.18
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.0.18
  @nrwl/web : Not Found
  @nrwl/workspace : 11.0.18
  typescript : 4.0.5


angular json

{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "",
  "projects": {
    "integra-frontend": {
      "projectType": "application",
      "schematics": {
        "@nrwl/workspace:component": {
          "style": "scss"
        }
      },
      "root": "apps/integra-frontend",
      "sourceRoot": "apps/integra-frontend/src",
      "prefix": "integra-frontend",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/apps/integra-frontend",
            "index": "apps/integra-frontend/src/index.html",
            "main": "apps/integra-frontend/src/main.ts",
            "polyfills": "apps/integra-frontend/src/polyfills.ts",
            "tsConfig": "apps/integra-frontend/tsconfig.app.json",
            "aot": true,
            "assets": [
              "apps/integra-frontend/src/favicon.ico",
              "apps/integra-frontend/src/assets"
            ],
            "styles": [
              "node_modules/@angular/material/prebuilt-themes/purple-green.css",
              "apps/integra-frontend/src/styles/main.scss"
            ],
            "stylePreprocessorOptions": {
              "includePaths": [
                "apps/integra-frontend/src/styles/"
              ]
            }
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "apps/integra-frontend/src/environments/environment.ts",
                  "with": "apps/integra-frontend/src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "3mb",
                  "maximumError": "5mb"
                },
                {
                  "type": "anyComponentStyle",
                  "maximumWarning": "20kb"
                }
              ]
            }
          },
          "outputs": [
            "{options.outputPath}"
          ]
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "integra-frontend:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "integra-frontend:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "integra-frontend:build"
          }
        },
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": [
              "apps/integra-frontend/**/*.ts",
              "apps/integra-frontend/**/*.html"
            ]
          }
        },
        "test": {
          "builder": "@nrwl/jest:jest",
          "options": {
            "jestConfig": "apps/integra-frontend/jest.config.js",
            "passWithNoTests": true
          },
          "outputs": [
            "coverage/apps/integra-frontend"
          ]
        }
      }
    },
    "integra-frontend-e2e": {
      "root": "apps/integra-frontend-e2e",
      "sourceRoot": "apps/integra-frontend-e2e/src",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@nrwl/cypress:cypress",
          "options": {
            "cypressConfig": "apps/integra-frontend-e2e/cypress.json",
            "tsConfig": "apps/integra-frontend-e2e/tsconfig.e2e.json",
            "devServerTarget": "integra-frontend:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "integra-frontend:serve:production"
            }
          }
        },
        "lint": {
          "builder": "@nrwl/linter:eslint",
          "options": {
            "lintFilePatterns": [
              "apps/integra-frontend-e2e/**/*.{js,ts}"
            ]
          }
        }
      }
    }
  },
  "cli": {
    "warnings": {
      "typescriptMismatch": false,
      "versionMismatch": false
    },
    "defaultCollection": "@nrwl/angular"
  },
  "schematics": {
    "@nrwl/angular:application": {
      "unitTestRunner": "jest",
      "e2eTestRunner": "cypress"
    },
    "@nrwl/angular:library": {
      "unitTestRunner": "jest"
    }
  },
  "defaultProject": "integra-frontend"
}


.eslinterc
{
  "root": true,
  "ignorePatterns": [
    "**/*"
  ],
  "overrides": [
    {
      "files": [
        "*.ts",
        "*.tsx",
        "*.js",
        "*.jsx"
      ],
      "rules": {
        "@nrwl/nx/enforce-module-boundaries": [
          "error",
          {
            "enforceBuildableLibDependency": true,
            "allow": [],
            "depConstraints": [
              {
                "sourceTag": "*",
                "onlyDependOnLibsWithTags": [
                  "*"
                ]
              }
            ]
          }
        ]
      }
    },
    {
      "files": [
        "*.ts"
      ],
      "parserOptions": {
        "project": "./tsconfig.*?.json"
      },
      "extends": [
        "plugin:@nrwl/nx/typescript"
      ],
      "rules": {
        "@typescript-eslint/consistent-type-definitions": "error",
        "@typescript-eslint/dot-notation": "off",
        "@typescript-eslint/explicit-member-accessibility": [
          "off",
          {
            "accessibility": "explicit"
          }
        ],
        "@typescript-eslint/no-inferrable-types": [
          "off",
          {
            "ignoreParameters": true
          }
        ],
        "id-blacklist": "off",
        "id-match": "off",
        "no-underscore-dangle": "off"
      }
    }
  ],
  "plugins": [
    "@nrwl/nx"
  ]
}

**Comment by LayZeeDK** [comment]
@DuncanFaulkner Try Node.js 12.x.

**Comment by DuncanFaulkner** [comment]
OK will check this I upgraded another project today and that all works, but I might not have upgraded node for that project. I will take a look at this after Christmas.
Is 14.15.3 of Node not supported?

**Comment by LayZeeDK** [comment]
Node.js 14 is not officially supported by Angular or Nx yet as far as I'm aware. I've seen it break some tools.

**Comment by DuncanFaulkner** [comment]
It would appear that my NX project isn't properly configured for NX workspaces, I also rolled back to 12.20.0 just to be on the safe side

**Comment by Lonli-Lokli** [comment]
With the latest upgrade I've got an error with prefer-const rule in ESLint. 
I have it disabled in root eslintrc, seems like rule overrides in libs actually overriding root one instead of merging it.

**Comment by LayZeeDK** [comment]
Hi @Lonli-Lokli,

I've talked to another community member about this happening with ESLint even thought it's supposed to merge the lists of rules and the options for the individual rules.

**Comment by jogelin** [comment]
Hello @Lonli-Lokli, @LayZeeDK 
Same issue here with the latest Nrwl version (11.1.5). We would like to change the `max-len` rule to align with our prettier config but it is not applied. We have to duplicate this rule in each apps/libs...

**Comment by Lonli-Lokli** [comment]
@jogelin max-len from eslint should be disabled actually as line length should be ruled by prettier (and it was before this release).

**Comment by jogelin** [comment]
@Lonli-Lokli I would agree but still have the error
`error  This line has a length of 141. Maximum allowed is 140  max-len`
and I skipped nx cache...

**Comment by Lonli-Lokli** [comment]
@jogelin agree, personally me roll back this upgrade as it took too much time to fix all of this.

**Comment by jogelin** [comment]
@Lonli-Lokli I am creating a common plugin that I include in each apps/lib ;) 

Ex:
```
module.exports = {
  globals: {
    MyGlobal: true,
  },
  rules: {
    'max-len': ['error', { code: 150 }],
    '@typescript-eslint/member-ordering': 'Off',
    '@angular-eslint/no-host-metadata-property': 'Off',
  },
};
```
then in `.eslinrc` of the app/lib
```
...
"extends": ["plugin:@nrwl/nx/angular", "plugin:@angular-eslint/template/process-inline-templates", "../../../tools/eslint"],
...
```

**Comment by Lonli-Lokli** [comment]
@jogelin I still hope it will be fixed by Nx team.

**Comment by bilelmsekni** [comment]
This is really annoying because I can't share typescript rules across my monorepo:
Steps to reproduce:

1- Generate a new workspace with eslint (11.1.5 or below)
2- In the root .eslintrc.json, update the section where we "extends": ["plugin:@nrwl/nx/typescript"],
```
{
      "files": ["*.ts", "*.tsx"],
      "extends": ["plugin:@nrwl/nx/typescript"],
      "parserOptions": { "project": "./tsconfig.*?.json" },
      "rules": {
        "quotes": ["error", "single", { "avoidEscape": true, "allowTemplateLiterals": false }],
        "max-len": [
          "error",
          {
            "code": 155,
            "tabWidth": 2,
            "ignoreUrls": true,
            "ignoreRegExpLiterals": true
          }
        ]
      }
    }
```
        
3- Go to app.component.ts and make the string title loooong (more than 140 but less then 155
```
export class AppComponent {
  title = 'app1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';
}
```

4- lint error is displayed saying you can't go more than 140 characters
6- Go to .eslintrc.json of the app project and remove `"plugin:@nrwl/nx/angular"`
```
    {
      "files": ["*.ts"],
      "extends": ["plugin:@nrwl/nx/angular", "plugin:@angular-eslint/template/process-inline-templates"],
      "parserOptions": { "project": ["apps/app1/tsconfig.*?.json"] },
      "rules": {
        "@angular-eslint/directive-selector": ["error", { "type": "attribute", "prefix": "nx-sample", "style": "camelCase" }],
        "@angular-eslint/component-selector": ["error", { "type": "element", "prefix": "nx-sample", "style": "kebab-case" }]
      }
    },
```
7- Watch the lint error disapear 

I understand that multiple technologies may exist in the monorepo but they all have to respect the same ligne length in my opinion

**Comment by Lonli-Lokli** [comment]
@FrozenPandaz Does Nx team any ETA for the fix? Or we should go with workaround , proposed above?

**Comment by developer239** [comment]
`"import/no-unresolved": "off"` is not a solution...

**Comment by smasala** [comment]
Any update on this @JamesHenry?

I find that if you add a new rule like
```json
{
      "files": ["*.ts", "*.tsx"],
      "parserOptions": {
        "project": ["tsconfig.*?.json"]
      },
      "rules": {
        "@typescript-eslint/explicit-member-accessibility": ["error", {
          "accessibility": "explicit"
        }]
      }
    },
```

Above the default nx generated rules in the eslint config at app level it doesn't work.

```json
{
      "files": ["*.ts"],
      "extends": ["plugin:@nrwl/nx/angular", "plugin:@angular-eslint/template/process-inline-templates"],
      "parserOptions": {
        "project": ["apps/example/tsconfig.*?.json", "apps/example/.storybook/tsconfig.json"]
      },
      "rules": {
        "@angular-eslint/directive-selector": [
          "error",
          {
            "type": "attribute",
            "prefix": "my-app",
            "style": "camelCase"
          }
        ],
        "@angular-eslint/component-selector": [
          "error",
          {
            "type": "element",
            "prefix": "my-app",
            "style": "kebab-case"
          }
        ]
      }
    }
```

However, if I add my new rule after the generated ones, then both are evaluated. This is only true when used on app level. If I place the `explicit-member-accessibility` on the root eslint config it never works regardless of ordering.

**Comment by smasala** [comment]
Doesn't seem quite NX related after all. Upgrading to latest seems to allow adding global lint rules but only if you add the rule to the end.

Or to be more precise... it needs to come after the default nx rules
```json
{
      "files": ["*.ts", "*.tsx"],
      "extends": ["plugin:@nrwl/nx/typescript"],
      "parserOptions": { "project": "./tsconfig.*?.json" },
      "rules": {}
    },
 ```
 
New deps to make it work.
```json
    "@angular-eslint/eslint-plugin": "~1.2.0",
    "@angular-eslint/eslint-plugin-template": "~1.2.0",
    "@angular-eslint/template-parser": "~1.2.0",
    "@typescript-eslint/eslint-plugin": "4.15.2",
    "@typescript-eslint/parser": "4.15.2",

```

**Comment by JamesHenry** [comment]
Folks, just a little more patience on this please, the automated migration generator is almost complete, it’s my main focus on Nx work right now. Many thanks! 🙏

**Comment by ranyehushua** [comment]
💎 ✋

**Comment by JamesHenry** [comment]
The final PR for this is feature complete and available here: #4943

**Comment by Lonli-Lokli** [comment]
@JamesHenry thank for brining this, will be part of Nx11?

**Comment by allout58** [comment]
@Lonli-Lokli it was released in 11.6.0 today 🎉

**Comment by Lonli-Lokli** [comment]
@allout58 Unfortunately, issue with root rules, described in https://github.com/nrwl/nx/issues/4320#issuecomment-760865537, still exists.

**Comment by manandkumaar** [comment]
Thanks @JamesHenry for the great work and @FrozenPandaz for releasing it in v11.6.0.

Looks like with the current release we can migrate one app/lib at a time.

We have 135+ apps/libs in our NX repo. 
So holding the migration for some more time and looking forward to the multi project or run-many support.

Thanks again for the awesome work
👏

**Comment by bopm** [comment]
When I run `nx migrate latest` in 11.5.2 repo, it upgrades to 11.6.0 without offering any migrations. So either I missing something, or it doesn't work at all if you upgraded to 11.5.2 before.

**Comment by beatlang** [comment]
Works like a charm. Bash script to do it on all libs and apps at once:
for project in $(cat angular.json | npx json projects | npx json -M -a key); do ng generate @nrwl/angular:convert-tslint-to-eslint --project=$project --no-interactive; done

**Comment by manandkumaar** [comment]
@beatlang Thanks for the script.
It works like a charm 😂👌

**Comment by EvtK** [comment]
> @allout58 Unfortunately, issue with root rules, described in [#4320 (comment)](https://github.com/nrwl/nx/issues/4320#issuecomment-760865537), still exists.

First off.. great work @JamesHenry. Just managed to migrate a ton of Angular projects to eslint.

But then I stumble upon the max-line error. I thought my configuration for the ignorePattern was incorrect, but then I discovered that the root config is not applied. This seems very weird to me.. I would definitly not want to go for a scenario where I have to apply custom eslint rule settings to each of my (200+!!) projects. Linting should be the same for all our projects.

**Comment by EvtK** [comment]
> ```json
>     "@angular-eslint/eslint-plugin": "~1.2.0",
>     "@angular-eslint/eslint-plugin-template": "~1.2.0",
>     "@angular-eslint/template-parser": "~1.2.0",
>     "@typescript-eslint/eslint-plugin": "4.15.2",
>     "@typescript-eslint/parser": "4.15.2"
> ```

follow up..  I updated all above packages to the latest, and now it seems to be working okay!

**Comment by JamesHenry** [comment]
@bilelmsekni @Lonli-Lokli @EvtK et al, yes I'm afraid when I published v1 of `angular-eslint` a few months ago the files that went up to npm were slightly stale, meaning the shared config that is extended by Nx contained a setting for `max-len` by accident.

All versions of angular-eslint published after v1.0.0 do not have this issue, so upgrading to any later version will resolve the issue for you. I will make sure Nx does this by default from now on too.

Many thanks!

**Comment by bilelmsekni** [comment]
@JamesHenry Thanks for the explanation. I just updated my packages to 2.0.2 but still experiencing the same issue
![image](https://user-images.githubusercontent.com/1716566/113152509-7db78300-9236-11eb-889e-eb16556d2095.png)

Perhaps I'm missing something else. Let me know which Nx version is good to try it please.
Also, it's not just the max-len rule. I have similar issues with     

```
'@typescript-eslint/explicit-member-accessibility': [
      'error',
      {
        accessibility: 'no-public'
      }
    ]
  }```
  which I can't set on a global level

**Comment by JamesHenry** [comment]
@bilelmsekni If you want to continue using the Nx Angular preset config, but have a set of rules that you configure for Angular projects to share (including overriding things within `nx/angular`, you can create a new `.eslintrc.json` (for example in `tools/`) and extend from that _after_ you extend from `nx/angular`.

We will document this pattern more explicitly soon, but ultimately it's just a case of composing ESLint configs so that anything you want to overwrite/customize comes last/deepest

**Comment by bilelmsekni** [comment]
@JamesHenry Already done ;)
![image](https://user-images.githubusercontent.com/1716566/113156817-a17cc800-923a-11eb-865f-b7e35a24116c.png)
```module.exports = {
  globals: {
    MyGlobal: true
  },
  rules: {
    quotes: ['error', 'single', { avoidEscape: true, allowTemplateLiterals: false }],
    'max-len': ['error', { code: 160, tabWidth: 2, ignoreUrls: true, ignoreRegExpLiterals: true }],
    '@typescript-eslint/explicit-member-accessibility': [
      'error',
      {
        accessibility: 'no-public'
      }
    ]
  }
};```

**Comment by Lonli-Lokli** [comment]
@JamesHenry That's basically everyone had before with root config (which does not work now even after update to the latest plugin)

**Comment by JamesHenry** [comment]
@Lonli-Lokli I'll write up some comprehensive docs on this topic but there is an important distinction between how Angular projects originally worked, and how Nx needs to work.

Nx is a multi-project, multi-paradigm monorepo tool. It therefore needs to set things up at the root that can work across lots of different types of projects and tools. ESLint can support this better than TSLint ever could because it was only usable with TypeScript.

Some of these patterns are still evolving and getting it right for all users (whether migrating or not) is not trivial. We're going to keep working on it and discussing it.

**Comment by JamesHenry** [comment]
Important update to this topic is this PR: https://github.com/nrwl/nx/pull/5188

It will make automated conversions smoother and require less manual intervention (depending on how much you use comment based configuration)

**Comment by EvtK** [comment]
@JamesHenry I'm currently in the process of narrowing down eslint linting errors after running the migration from tslint->eslint for all my projects.

Where can I find the default config that is used by NX, when these plugin's are applied?

        "plugin:@nrwl/nx/typescript"
        "plugin:@nrwl/nx/javascript"

I have searched the NX code-base, but could not find a reference to configuring eslint rules for these plugins.

Also, is there a default config applied for @angular-eslint?

**Comment by GeorgeKnap** [comment]
Hi guys.
Does anyone noticed this problem in overriding `"@typescript-eslint/no-non-null-assertion": "off"`  in root `.eslintrc.json` file?  It only works when you set the rule in the library eslintrc file. Standard eslint rules - like `curly` - overrides works.
![map-component](https://user-images.githubusercontent.com/11920691/114271912-122e9c00-9a14-11eb-9087-edffd9c7dd37.gif)

**Comment by EvtK** [comment]
Yeah I'm still in the same boat as well, want to override this one:

@angular-eslint/no-output-native

globally, but it doesn't seems to be picked up. I believe I can't follow on @JamesHenry explanations here... why isn't this working?

**Comment by jogelin** [comment]
@EvtK I had the same reflex at the beginning but Like @JamesHenry explained:
> "Nx is a multi-project, multi-paradigm monorepo tool"

All configurations specific to an app/lib should be located to the app/lib location.

For example, this is not recommended to put `angularCompilerOptions` configurations in the `tsconfig.base.json`. We put this configuration in each Angular project.

For the same reason, this is not recommended to put `@angular-eslint/no-output-native` in the root file because it only belongs to Angular projects.

This is the current solution for applying global rules: https://github.com/nrwl/nx/issues/4320#issuecomment-811372281

**Comment by EvtK** [comment]
hi @jogelin Thanks for the extra bits and nits. Following now.. Wondering though: why can I in fact overrule typescript eslint rules in the root config? Is this because of the pre-consumption that everything is typescript and thus we want to maintain a global style for coding?

**Comment by JamesHenry** [comment]
@EvtK @jogelin Please also take a look at https://github.com/nrwl/nx/issues/5259

There is definitely some extra clarity we can achieve in the next major version

**Comment by JamesHenry** [comment]
I'm going to lock this thread now as the migration to ESLint was added a long time ago. Please either open new issues or new Github Discussions, it's very hard to track comments on closed issues.
