### ISSUE TITLE
Outlet is not activated

### ISSUE THREAD

**Issue by jbeckton** [nrwl/nx#436]
I have had problems with the StoreRouterConnectingModule on multiple angular ngrx apps even outside of NX workspaces. With NX I have seen the error "Outlet is not activated" when lazy loading feature module libraries. The fix was to override the RouterStateSerializer with a custom serializer in all cases.

Generating a simple NX workspace with one app and one routed feature lib is broken out of the box. Maybe consider adding to the generator a custom serializer to prevent this issue.

**Comment by vsavkin** [comment]
If i understand the issue correctly, it should be addressed in NgRx 6 (see here: https://github.com/ngrx/platform/pull/901), which should be released soon. 

Meanwhile, I'll add the serializer to Nx.

**Comment by fateh14** [comment]
still getting this error :/, nx version: 
`"@nrwl/nx": "6.1.1",`

**Comment by davidreher** [comment]
@vsavkin: Is it save to update to NgRx 6? Is it supported with Nx 6?

**Comment by FrozenPandaz** [comment]
It is now safe to update to @ngrx@6 (in fact it's automatically migrated to) so this should no longer be an issue. 👍
