### ISSUE TITLE
Next App - ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by rplotkin** [nrwl/nx#5063]
## Current Behavior

Migrated from 11.4.0 to 11.5.1 When building a NextJS app, a RegeneratorRuntime error is thrown and the app will not build.
This happens even with a clean app.

## Expected Behavior

Regression. Expect NextJS app to build without error.

## Steps to Reproduce

`nx g @nrwl/next:app test-next-app`
`nx build test-next-app`
--> error

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

(replaced identifying path info with `...`)

> nx run test-next-app:build 
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
info  - Using external babel configuration from .../babel.config.json
info  - Using external babel configuration from .../apps/test-next-app/.babelrc
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data  
[=== ] info  - Generating static pages (0/2)
Error occurred prerendering page "/404". Read more: https://err.sh/next.js/prerender-error
ReferenceError: regeneratorRuntime is not defined
    at .../dist/apps/test-next-app/.next/server/pages/_document.js:314:62
    at .../dist/apps/test-next-app/.next/server/pages/_document.js:356:6
    at Object.4D8t (.../dist/apps/test-next-app/.next/server/pages/_document.js:367:2)
    at __webpack_require__ (.../dist/apps/test-next-app/.next/server/pages/_document.js:23:31)
    at Object.sf+I (.../dist/apps/test-next-app/.next/server/pages/_document.js:1189:18)
    at __webpack_require__ (.../dist/apps/test-next-app/.next/server/pages/_document.js:23:31)
    at Module.Y7Z2 (.../dist/apps/test-next-app/.next/server/pages/_document.js:933:71)
    at __webpack_require__ (.../dist/apps/test-next-app/.next/server/pages/_document.js:23:31)
    at Object.1 (.../dist/apps/test-next-app/.next/server/pages/_document.js:99:18)
    at __webpack_require__ (.../dist/apps/test-next-app/.next/server/pages/_document.js:23:31)

Error occurred prerendering page "/". Read more: https://err.sh/next.js/prerender-error
ReferenceError: regeneratorRuntime is not defined
    at .../dist/apps/test-next-app/.next/server/pages/_document.js:314:62
    at .../dist/apps/test-next-app/.next/server/pages/_document.js:356:6
    at Object.4D8t (.../dist/apps/test-next-app/.next/server/pages/_document.js:367:2)
    at __webpack_require__ (.../dist/apps/test-next-app/.next/server/pages/_document.js:23:31)
    at Object.sf+I (.../dist/apps/test-next-app/.next/server/pages/_document.js:1189:18)
    at __webpack_require__ (.../dist/apps/test-next-app/.next/server/pages/_document.js:23:31)
    at Module.Y7Z2 (.../dist/apps/test-next-app/.next/server/pages/_document.js:933:71)
    at __webpack_require__ (.../dist/apps/test-next-app/.next/server/pages/_document.js:23:31)
    at Object.1 (.../dist/apps/test-next-app/.next/server/pages/_document.js:99:18)
    at __webpack_require__ (.../dist/apps/test-next-app/.next/server/pages/_document.js:23:31)
Export encountered errors on following paths:
        /
        /404
[    ] info  - Generating static pages (0/2)%   

### Environment

>  NX  Report complete - copy this into the issue template

  Node : 14.15.5
  OS   : darwin x64
  npm  : 6.14.11
  
  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 11.5.1
  @nrwl/cypress : 11.5.1
  @nrwl/devkit : 11.5.1
  @nrwl/eslint-plugin-nx : 11.5.1
  @nrwl/express : 11.5.1
  @nrwl/jest : 11.5.1
  @nrwl/linter : 11.5.1
  @nrwl/nest : Not Found
  @nrwl/next : 11.5.1
  @nrwl/node : 11.5.1
  @nrwl/react : 11.5.1
  @nrwl/schematics : Not Found
  @nrwl/tao : 11.5.1
  @nrwl/web : 11.5.1
  @nrwl/workspace : 11.5.1
  @nrwl/storybook : 11.5.1
  @nrwl/gatsby : Not Found
  typescript : 4.0.6

**Comment by rplotkin** [comment]
Note: this can be fixed by adding
`import 'regenerator-runtime/runtime';`
as the first import of the NextJS app's `_document.tsx` file

I will see if I can open a PR here to update the generator

**Comment by tl5675387** [comment]
I got a similar error when migrated my project to 11.5.1. @rplotkin's trick did fixed the error. @rplotkin do you know why it happened?

**Comment by cyrus-za** [comment]
I got the same error when upgrading to 11.5.1 (#5032), but @rplotkin's trick did **not** fix it for me.

I waited for 11.5.2 to release and then upgraded to it from master (11.4.0) and ran all migrations. It did the smae .babel changes and changed the tsconfig for my one next app (but not the other which had it already removed I guess). 

At first I got an error of `Syntax error: Support for the experimental syntax 'flow' isn't currently enabled` which was actually typescript code. I got node libs that dont contain any babelrc files. Adding the `@nrwl/web/babel` to them fixed that issue, but then I get `Error: ENOENT: no such file or directory, lstat '/root/events'` (root being the root of the repo)
I am not sure why that error is happening. Everything still works fine in 11.4.0

**Comment by evanlk** [comment]
Set NODE_ENV = 'test' and removed a few ES2020 features fixed this issue for me.  Looking at the `@nrwl/web/babel` file reviewed that `corejs` was only implemented when the environment was `test'

**Comment by evanlk** [comment]
Monorepo is completely broke because of this issue.  Tried the solution offered by @rplotkin, however it doesn't work.  It did work before, but for whatever reason, this is no longer the case.

**Comment by rplotkin** [comment]
@evanlk @cyrus-za (and whoever else):   babel.config.json, add `"plugins": ["@babel/plugin-transform-runtime"]`

**Comment by cyrus-za** [comment]
@rplotkin I get
```sh
Error during bundle: Error: You have declared using "bundled" babelHelpers, but transforming /libs/ui/index.ts resulted in "runtime". Please check your configuration.
```

**Comment by shinnoki** [comment]
I faced the same issue and update Next.js to 10.0.9 solved it.

Peer deps was changed to `^10.0.9` for now.
https://github.com/nrwl/nx/commit/0822d00e0cb49091ae0921e1896148f6cf2a29ba

**Comment by kirjai** [comment]
We've had issues with babel in versions `11.5.0` and `11.5.1`. We have recently released `11.5.2` which should hopefully resolve those issues. So please try migrating to the new version, running the migrations, and report back if the issue persists

**Comment by tl5675387** [comment]
hi @kirjai
I tried to migrate to `11.5.2` today but with no success. I stuck at the step 3. Here is the log:
```
$ npx nx migrate --run-migrations=migrations.json

>  NX  Running 'yarn' to make sure necessary packages are installed

yarn install v1.18.0
[1/4] Resolving packages...
success Already up-to-date.
Done in 2.44s.

>  NX  Running migrations from 'migrations.json'

Running migration always-use-project-level-tsconfigs-with-eslint
Successfully finished always-use-project-level-tsconfigs-with-eslint
---------------------------------------------------------
Running migration update-babel-config-11.5.0
Successfully finished update-babel-config-11.5.0
---------------------------------------------------------
Running migration remove-tsconfig-app-11.5.0
Successfully finished remove-tsconfig-app-11.5.0
---------------------------------------------------------
Running migration update-root-babel-config-11-5-2
Successfully finished update-root-babel-config-11-5-2
---------------------------------------------------------
Running migration create-babelrc-for-workspace-libs-11-5-2
Maximum call stack size exceeded
Command failed: /tmp/tmp-184477lJnZ9naqwQ8r/node_modules/.bin/tao migrate --run-migrations=migrations.json
```

**Comment by kirjai** [comment]
@tl5675387 thanks for giving that a try. 
Could you paste what you currently have in the babel config file at the root of your workspace, and babel config at the root of your next app?

If you haven't changed either of those over the course of your app development, you should have:
```json
{
  "babelrcRoots": ["*"]
}
```
in the root `babel.config.js`, and 
```json
{
  "presets": ["@nrwl/next/babel"],
  "plugins": []
}
```
at the root of your app, in `.babelrc`

**Comment by tl5675387** [comment]
@kirjai Sorry I just reverted my project back to `11.4.0`.
I will try it again over the weekend and update you the result.

**Comment by kirjai** [comment]
@tl5675387 sure thing, report back once you do.

I've marked it as "repro needed" for now, as the original steps to reproduce don't produce any errors on `11.5.2`

**Comment by evanlk** [comment]
I have just tested and still receiving the "regeneratorRuntime is not defined" error.  This is even after migrating to `11.5.2`, running the migrations, and reinstalling node_modules.

`
{
  "presets": [],
  "babelrcRoots": ["*"]
}
`
My babel.config.json file


`
{
  "presets": ["@nrwl/next/babel"],
  "plugins": []
}
`
My .babelrc file for my next application


`{
  "presets": ["@nrwl/web/babel"]
}
`
My .babelrc file for a library I have included.  The library seems to be the culprit that is triggering the error.

**Comment by kirjai** [comment]
@evanlk thanks for more info.
hm.. replicating those specific babel configs locally, in a fresh workspace doesn't trigger any errors for me, I'm afraid 😕

could you try and replicate the issue in a repo that I can pull to look into this more?

**Comment by evanlk** [comment]
Yeah I will see if I can reproduce on a fresh install

**Comment by evanlk** [comment]
I was able to reproduce the issue with a barebone version of my repo.  Use `https://github.com/evanlk/nxtest` to reproduce.  Also double checked to make sure the necessary `.babelrc` and `babel.config.js` files are in place.  Let me know if you need anything else.

**Comment by kirjai** [comment]
@evanlk appreciate you creating a repo, that helps a lot.

What fixes it in your case is changing the preset in the lib's `.babelrc` to `"@nrwl/next/babel"` *instead of* `"@nrwl/web/babel"`:

```json
// libs/shared/util-session/.babelrc
{
  "presets": ["@nrwl/next/babel"]
}
```

but i'm guessing that code you have in that lib is meant to be used both within a next.js app, as well as outside of it?

**Comment by evanlk** [comment]
Adding `@nrwl/next/babel`  to the lib's `.babelrc` file fixes that specific test case, but did not fix my real repo.  

However, I did some more digging comparing the differences between the test repo and the real one.  This lead me to discover that the root cause of my problem is from the use of the `process` object within the library.  Removing `process` fixed my issues with the real repo.

My rule of thumb will be to not use `process` in a library that is intended for both frontend and backend use.

**Comment by tl5675387** [comment]
> @evanlk appreciate you creating a repo, that helps a lot.
> 
> What fixes it in your case is changing the preset in the lib's `.babelrc` to `"@nrwl/next/babel"` _instead of_ `"@nrwl/web/babel"`:
> 
> ```json
> // libs/shared/util-session/.babelrc
> {
>   "presets": ["@nrwl/next/babel"]
> }
> ```
> 
> but i'm guessing that code you have in that lib is meant to be used both within a next.js app, as well as outside of it?

@kirjai True, I have some libraries that are used both in nextjs app and non-nextjs apps. I think it makes more sense to keep `"@nrwl/web/babel"` preset instead of changing it to `"@nrwl/next/babel"` in my case.

**Comment by kirjai** [comment]
should be fixed in the next release. using a lib that uses the `@nrwl/web/babel` preset should now work

if the issue still persists - please provide a new repro, so we can look into it for you

**Comment by pitops** [comment]
@kirjai is it part of v11.6.1? if it is, then it's not working for me. Also, I am not using any libs - get the issue in the nextjs app.

**Comment by kirjai** [comment]
@pitops the libs `@nrwl/web/babel` fix is part of `11.6.1`, yes

Can you provide a repro repo where this occurs, i can take a look at?

**Comment by pitops** [comment]
i can give you access as its private repo if you want to provide me with an email

**Comment by HarryBrand** [comment]
Ran into the same issue and isolated it down to async calls, fixed by including `@babel/plugin-transform-runtime` plugin in my **Next application** `.babelrc`

```
{
  "presets": ["@nrwl/next/babel"],
  "plugins": ["@babel/plugin-transform-runtime"]
}
```

For more information see [Babel Issue 9849](https://github.com/babel/babel/issues/9849)

**Comment by cyrus-za** [comment]
I'm still experiencing this in 11.6.1. In fact, I got a bunch of other issues with babel-loader not able to read typescript in some of my ui libs, but not all of them. Their config is exactly the same (babelrc, tsconfig etc). 

I tried switching from "@nrwl/react/babel" to next or web and both give the same result.

**Comment by pitops** [comment]
@cyrus-za current workaround is what @HarryBrand described.

**Comment by kirjai** [comment]
haven't had a chance to look into the repro quite yet, but a new major version of Nx 12 has been released with a fix that seems relevant. #5257

thought I'd mention it if anyone feels like giving that a try until we can look into the repro properly

**Comment by HarryBrand** [comment]
@kirjai I've just tried upgrading & migrating to the new major release Nx 12 and unfortunately the issue remains

**Comment by Javibu5** [comment]
Try to delete the folder dist from your project.  It worked for me.

**Comment by kirjai** [comment]
that's a good point, actually. along with that, it's worth clearing `node_modules/.cache` as well. 

@Javibu5 so it's fixed for you on version 12?

**Comment by Javibu5** [comment]
@kirjai Yes, if you don't update to the version 12, doesn't work. Migrating the project, and deleting the dist folder fixed the problem, because I did a build previously. 

I didn't clear the node_modules/.cache but could be also a solution fo the problem.

**Comment by EugeneGohh** [comment]
> Note: this can be fixed in the raw test app by adding `import 'regenerator-runtime/runtime';` as the first import of the NextJS app's `_document.tsx` file
> 
> However, it doesn't fix a larger app that imports libs. To fix that app, I needed to add that line to the top of all NextJS pages in use, as well as `index.tsx` and `_app.tsx`

thank you

**Comment by Kyu** [comment]
> Note: this can be fixed in the raw test app by adding `import 'regenerator-runtime/runtime';` as the first import of the NextJS app's `_document.tsx` file
> 
> However, it doesn't fix a larger app that imports libs. To fix that app, I needed to add that line to the top of all NextJS pages in use, as well as `index.tsx` and `_app.tsx`

Worked in 2023, thank you @ rplotkin
