### ISSUE TITLE
enforce-module-boundaries erroring for alias paths

### ISSUE THREAD

**Issue by nzacca** [nrwl/nx#5621]
## Current Behavior

After upgrading to nx `12.2.0`, linting fails for the `enforce-module-boundaries` rule due to aliased paths not satisfying a `relativePath` of the new `allowCircularSelfDependency` check. 

## Expected Behavior

Allow `allowCircularSelfDependency` to be overridable in the `enforce-module-boundaries` rule or support alias paths by default. Receiving an error when attempting to override this property: 

```
Configuration for rule "@nrwl/nx/enforce-module-boundaries" is invalid:
...
should NOT have additional properties
```

## Steps to Reproduce

```ts
// This should not raise the `noSelfCircularDependencies` error
import { foo } from "~apps/my-path/my-file.ts";
```

```
// eslint config rule
"@nrwl/nx/enforce-module-boundaries": [
	"error",
	{
		enforceBuildableLibDependency: true,
		allow: [],
		depConstraints: [],
		allowCircularSelfDependency: true,
	},
],
```

### Failure Logs

`3:1  error  Only relative imports are allowed within the project. Absolute import found: <filepath> @nrwl/nx/enforce-module-boundaries`

### Environment

```bash
>  NX  Report complete - copy this into the issue template

  Node : 12.19.0
  OS   : linux x64
  npm  : 6.14.8

  nx : Not Found
  @nrwl/angular : 12.2.0
  @nrwl/cli : 12.2.0
  @nrwl/cypress : 12.2.0
  @nrwl/devkit : 12.2.0
  @nrwl/eslint-plugin-nx : 12.2.0
  @nrwl/express : Not Found
  @nrwl/jest : 12.2.0
  @nrwl/linter : 12.2.0
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.2.0
  @nrwl/web : Not Found
  @nrwl/workspace : 12.2.0
  @nrwl/storybook : 12.2.0
  @nrwl/gatsby : Not Found
  typescript : 4.1.5
```

### Other Notes:

Appears to have been introduced here: https://github.com/nrwl/nx/commit/f28097e26409f6411ccde9ae670da90346dfa4c6#diff-e8f2f44806e7a6dcf0094865947f3e26b0b4aa67754936fb869d3678efbecae2

May need to add the `allowCircularSelfDependency` property to the schema to allow overriding if this is intended to be overridable: https://github.com/nrwl/nx/blob/f28097e26409f6411ccde9ae670da90346dfa4c6/packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts#L65

**Comment by puku0x** [comment]
This will be solved by https://github.com/nrwl/nx/pull/5613 in next release.

**Comment by FrozenPandaz** [comment]
@meeroslav is this issue resolved by https://github.com/nrwl/nx/pull/5613?

**Comment by meeroslav** [comment]
Yes, it's solved by #5613 alread.

**Comment by angelnikolov** [comment]
@meeroslav Is this resolved for absolute but aliased imports?
I still get the error on NX 12.3.4 below for imports like `import { GenericEventsWidgetModule } from '@app/shared/components/widgets/generic-events/generic-events.module';`.
I am still using `tslint` and there wasn't an issue with this before the A12 migration.

```
ERROR: 21:1  nx-enforce-module-boundaries  Only relative imports are allowed within the project. Absolute import found: @app/shared/components/widgets/generic-events/generic-events.module
```

**Comment by meeroslav** [comment]
Hi @angelnikolov, the rule is related to both absolute and aliased imports (as it's just an alias to the absolute path).

You can switch off this rule by setting the rule flag `allowCircularSelfDependency` to true, but our suggestion would be to use relative imports when importing files within the same project.

**Comment by angelnikolov** [comment]
Yeah came to the same conclusion. Tried the circular dep settings too but that will also prevent us from catching modules importing themselves. Well I guess that means I am gonna have to rename several hundred imports :D thanks for your answer anyway
