### ISSUE TITLE
Running storybook failed : Could not get angular cli webpack config

### ISSUE THREAD

**Issue by BenLune** [nrwl/nx#5657]
## Current Behavior
I want to generate the Storybook Version of my app. It worked fine, it doesn't work anymore.

## Expected Behavior
Successful Storybook generation

## Steps to Reproduce
I have this when running this command : nx run my-app:storybook
Sorry it's not very detailed, I hope the error I have will be more meaningful for you than it is for me :-)

### Failure Logs
ERR! => Could not get angular cli webpack config
Cannot read property 'minify' of undefined

### Environment
Node : 12.16.1
  OS   : darwin x64
  yarn : 1.22.4
  
  nx : Not Found
  @nrwl/angular : 12.3.1
  @nrwl/cli : 12.3.1
  @nrwl/cypress : 12.3.1
  @nrwl/devkit : 12.3.1
  @nrwl/eslint-plugin-nx : 12.3.1
  @nrwl/express : Not Found
  @nrwl/jest : 12.3.1
  @nrwl/linter : 12.3.1
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.3.1
  @nrwl/web : Not Found
  @nrwl/workspace : 12.3.1
  @nrwl/storybook : 12.3.1
  @nrwl/gatsby : Not Found
  typescript : 4.2.4

**Comment by BenLune** [comment]
I updated storybook with this command :
`npx sb upgrade --prerelease`
I removed node_modules, and yarn, I still have the problem.

**Comment by juristr** [comment]
This is an issue with the current version of Storybook: https://github.com/storybookjs/storybook/issues/14260

In your `angular.json` config change the `optimization: true` to 

```
"optimization": {
  "styles": {
    "minify": true
  }
},
```

That should solve it :)

**Comment by IMalaniak** [comment]
Still exist here, on angular workspace.
ERR! => Could not get angular cli webpack config
ERR! TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

**Comment by goodnewsforyoubaby** [comment]
Added tsConfig path to architect.build.builder.options

<img width="691" alt="129202111-4f7bde79-3afd-4160-b5c6-5f8ff326319c" src="https://user-images.githubusercontent.com/25374303/129202259-3c692b1d-9e9e-49c5-8950-07323563b119.png">
