### ISSUE TITLE
Storybook Configuration: Shared Global Assets

### ISSUE THREAD

**Issue by KerickHowlett** [nrwl/nx#5833]
I'm having incredible difficulty trying to get my static images to load in Storybook for my Angular-focused project.

**The Details for what I'm trying to accomplish are as follows:**
- I have a Storybook library serving as a central hub in serving all the other user stories. That part I have working fine.
- I want it to utilize my global styles. Again, I managed to get this working fine via main.js and `webpackFinal`.
- I want it to utilize my global static assets (mainly images) that I can serve from my global assets library.

What is NOT working is that the background images that are established as CSS rules are not being loaded. 

From what I can tell is that it's dumping the assets into the root of wherever Storybook is being served and in the directory output it's being built. The problem stems from the fact that in my CSS rules, and because of how the glob input/output configuration works with `targets.build.assets` in workspace.json (what I'm suing) or angular.json, it's looking for `/assets/image.png`; however, it's storing them as just `/image.png`.

Or at least I'm pretty sure that's the case based on the terminal output that's fed back to me during compilation:

![image](https://user-images.githubusercontent.com/8661181/120074746-54677780-c06c-11eb-822b-0c605770dc6a.png)

## Description
It would be helpful if there was a way to establish static assets for Storybook in very much the same way that you can with assets for normal builds.

Something akin to this (apologies for the wacky formatting, as my VSCode screws with indention whenever I attempt to copy & paste snippets):

```javascript
"storybook": {
      "executor": "@nrwl/storybook:storybook",
      "options": {
          "uiFramework": "@storybook/angular",
          "port": 4400,
          "config": { "configFolder": "libs/client/storybook/.storybook" },
          "staticDir": [
               {
                    "input": "libs/client/shared/utils/assets/src/lib/favicons",
                    "glob": "**/*.png",
                    "output": "./assets"
                }
           ]
    },
    "configurations": { "ci": { "quiet": true } }
 }
```

## Motivation
I just feel the configuration should be relatively simple to allow for shared global styles and assets from the workspace.json/angular.json file alone. Or even some Nx Console generator to do it for you; that way we can purely focus on coding and not setup.

## Alternate Implementations
The Nx Console generator like I mentioned could also work or just a command to at least a sort of mask or proxy for the assets. Where if Storybook detects the story's trying to pull a resource that matches a certain pattern -- say `/assets/**/* .png` for example -- it would know to instead look for it in wherever you would have that file stored in your project.

But I'm open to any other kind of alternative; I just feel that the configuration for what I feel to be an obligatory feature to be near effortless (or at least well documented).

(Speaking of documentation, I have checked both NRWL's and Storybook's official documentation and could find no answers to the problem I'm introducing.)

**Comment by mandarini** [comment]
@KerickHowlett @Swimburger 

Lately (since Storybook v6.4) [Storybook uses `staticDirs` in `.storybook/main.js`] (https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag) instead of the `staticDir` flag. This means that since Nx uses one global `.storybook/main.js` which gets imported in all the storybook instances, maybe you can add your assets and static directories paths in that array, and it should work? Do you want to give that a try and let me know if this covers your issue? See [this documentation](https://storybook.js.org/docs/react/configure/images-and-assets#serving-static-files-via-storybook-configuration), I think it may be helpful.

**Comment by KerickHowlett** [comment]
I haven't touched the project this thread was concerning in a long time. Admittedly, I should be better with "GitHub Issues Etiquette" and should have said something beforehand. Sorry, I don't file too many issue tickets in GitHub. Nevertheless, I'll remember to give this solution a try as soon as I'm able.

**Comment by mandarini** [comment]
Hi @KerickHowlett ! No worries, your "GitHub Issues Etiquette" is perfect! :) 

Sure, try it out and let me know. I do think that the `staticDirs` array in the root `.storybook/main.js` should do the trick.

**Comment by Swimburger** [comment]
I changed jobs, so I'm not working on/don't have access to the projects that use Nrwl or Storybook anymore. I hope someone else can verify, otherwise I can try to put a sample together.

**Comment by mandarini** [comment]
So, I really believe that this is resolved with the `staticDirs` in the shared `main.js`. So I will be closing this for now. If it comes up again, let's reopen it! :)

**Comment by KerickHowlett** [comment]
Apologies for not being able to revisit this much sooner; I've just been incredibly busy these past few months (or rather this past year). I might still have the repo this issue entailed, so I'll make it a point to try the suggestion out in the near future.

**Comment by mandarini** [comment]
Hi @KerickHowlett , no worries at all! :) :) I closed this issue because I think it works now. If at any point the issue comes up again, write here, and I will see it and re-open! :)

**Comment by WidgetsBurritos** [comment]
Just to follow up, I was experiencing this issue on 13.8. I updated to v14 last night and it appears to be working now so I can confirm this is, in fact, working as expected.

**Comment by mandarini** [comment]
That's so good to hear!! :)
