### ISSUE TITLE
generator cant find project.json when standaloneConfig is true

### ISSUE THREAD

**Issue by SvenBudak** [nrwl/nx#6425]
I have a simple generator script that generates a lib and a component:

```js
import { formatFiles, installPackagesTask, Tree } from '@nrwl/devkit';
import { libraryGenerator } from '@nrwl/angular/generators';
import { wrapAngularDevkitSchematic } from '@nrwl/devkit/ngcli-adapter';

function generateLibrary(tree: Tree, schema: any) {
  return libraryGenerator(tree, {
    name: schema.name,
    directory: 'features',
    lazy: true,
    prefix: schema.name,
    routing: true,
    simpleModuleName: true,
    // standaloneConfig: true <<< Script works not with this option...
  });
}

function generateComponent(tree: Tree, schema: any, name: string, path?: string) {
  const baseOptions = {
    style: 'scss',
    changeDetection: 'OnPush',
    displayBlock: true,
    export: true,
    skipTests: true
  }
  
  const libraryGenerator: any = wrapAngularDevkitSchematic('@schematics/angular', 'component');

  return libraryGenerator(tree, {
    ...baseOptions,
    name: name,
    project: `features-${schema.name}`,
    path
  });
}

export default async function (tree: Tree, schema: any) {
  await generateLibrary(tree, schema);
  await generateComponent(tree, schema, 'sign-in', `libs/features/${schema.name}/src/lib/components`);
  await generateComponent(tree, schema, 'sign-out', `libs/features/${schema.name}/src/lib/components`);
  await generateComponent(tree, schema, 'sign-up', `libs/features/${schema.name}/src/lib/components`);
  await generateComponent(tree, schema, 'layout' );
  await generateComponent(tree, schema, 'sign-in', `libs/features/${schema.name}/src/lib/views`);
  await generateComponent(tree, schema, 'sign-out', `libs/features/${schema.name}/src/lib/views`);
  await generateComponent(tree, schema, 'sign-up', `libs/features/${schema.name}/src/lib/views`);
  await formatFiles(tree);
  return () => {
    installPackagesTask(tree);
  };
}
```

The problem is that the script dont find the `project.json`. when i disable `standaloneConfig` it works fine. So i think its a bug. please correct me if i am wrong.

**Comment by AgentEnder** [comment]
@SvenBudak What is the output of `nx report` in this repo? I think this should be fixed in latest.

**Comment by SvenBudak** [comment]
@AgentEnder Nice! It seems that you guys made it! it works now. But i still have the strange paths in Windows 10 in my workspace.json after run the script:

```json
{
  "version": 2,
  "projects": {
    "features-auth": "libs/features/auth",
    "features-auth5": "libs\\features\\auth5",
  },
  ..
}
```

Its fine when the project is only running on windows machines, but when my friend pull with his mac, then he get errors because his machine cant resolve the path.

**Comment by AgentEnder** [comment]
I'm going to close this issue, the path separator work will fall under #6411.
