### ISSUE TITLE
Error: (0 , _identifier.getUndoPath) is not a function

### ISSUE THREAD

**Issue by muuvmuuv** [nrwl/nx#6612]
## Current Behavior

I am trying to build my Angular Ionic application and followed this guide here: https://ionicframework.com/blog/ionic-angular-monorepos-with-nx/

Unfortunately I am getting the below error when running `nx build`:

```
styles.5c56ab7b989b0bb258f7.css - Error: (0 , _identifier.getUndoPath) is not a function
```

## Steps to Reproduce

Follow this guide:

https://ionicframework.com/blog/ionic-angular-monorepos-with-nx/

### Failure Logs

```
; nx build

> nx run entergon:build:production
✔ Browser application bundle generation complete.

styles.5c56ab7b989b0bb258f7.css - Error: (0 , _identifier.getUndoPath) is not a function



———————————————————————————————————————————————

>  NX   ERROR  Running target "entergon:build" failed

  Failed tasks:

  - entergon:build:production

  Hint: run the command with --verbose for more details.
```

### Environment

 nx : 12.6.4
  @nrwl/angular : 12.6.4
  @nrwl/cli : 12.6.4
  @nrwl/cypress : 12.6.4
  @nrwl/devkit : 12.6.4
  @nrwl/eslint-plugin-nx : 12.6.4
  @nrwl/express : Not Found
  @nrwl/jest : 12.6.4
  @nrwl/linter : 12.6.4
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.6.4
  @nrwl/web : Not Found
  @nrwl/workspace : 12.6.4
  @nrwl/storybook : 12.6.4
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

**Comment by gilian-schreuders** [comment]
I got the same exact problem. I've generated a new nx workspace with angular and this error occurs. What seems to "work" is to remove the `"styles"` attribute from the `angular.json` file. This is no option however, because we need global styles :) .

**Comment by eggp** [comment]
I also have the error...
Test flow:
- create new workspace(ver: 12.6.4).
- add material with custom theme
- build project and error ... :(

**Comment by eggp** [comment]
@muuvmuuv my hotfix:
add your package.json devDependencies: "mini-css-extract-plugin": "2.2.0" and work build

**Comment by ShinRai1090** [comment]
> mini-css-extract-plugin

this works! ... waiting for a proper fix though :)

**Comment by FrozenPandaz** [comment]
Hi all, sorry for the inconvenience. We are looking into this.

Meanwhile, I found the following to work after creating a new workspace.

1. `rm -rf node_modules package-lock.json` // Delete `package-lock.json` and `node_modules`
2. `npm i` // Install again

**Comment by eggp** [comment]
> Hi all, sorry for the inconvenience. We are looking into this.
> 
> Meanwhile, I found the following to work after creating a new workspace.
> 
> 1. `rm -rf node_modules package-lock.json` // Delete `package-lock.json` and `node_modules`
> 2. `npm i` // Install again
> 
> Things should work again. If not, please post the results of `npm ls webpack`

i tried,
the error still existsÉ

npm ls webpack
![image](https://user-images.githubusercontent.com/1015211/128385155-c9171c9b-d327-4864-8784-5cf8418515d9.png)

**Comment by FrozenPandaz** [comment]
We just published `12.6.5` with a fix. Please use that version :smile:

**Comment by eggp** [comment]
thanks

**Comment by Hakhenaton** [comment]
I migrated to `12.6.5` and ran `npm install`.

I still get the same error, unfortunetaly.

**Comment by dhanush-tydy** [comment]
> I managed to fix an already created Angular project by manually updating `package.json`.
> 
> I simply changed `"@angular-devkit/build-angular": "^12.1.0"` to `"@angular-devkit/build-angular": "~12.1.0"`, then ran `npm install`.
> 
> Now build is working.

This works

**Comment by eggp** [comment]
yes, in the case of a new installation, it also helped me to upgrade the angular package versions to a smaller version

however, for an existing project, the update solved the problem

**Comment by memo18j** [comment]
> Logré arreglar un proyecto Angular ya creado actualizándolo manualmente `package.json`.
> 
> Simplemente me cambié `"@angular-devkit/build-angular": "^12.1.0"`a `"@angular-devkit/build-angular": "~12.1.0"`, luego corrí `npm install`.
> 
> Ahora la compilación está funcionando.

Esta me funciono tambien

**Comment by ph55** [comment]
> We just published `12.6.5` with a fix. Please use that version 😄

@FrozenPandaz  Issue still exists in 12.6.5 and probably not related to NX.

> I managed to fix an already created Angular project by manually updating `package.json`.
> 
> I simply changed `"@angular-devkit/build-angular": "^12.1.0"` to `"@angular-devkit/build-angular": "~12.1.0"`, then ran `npm install`.
> 
> Now build is working.

Downgrading `@angular-devkit/build-angular` to 12.1.0 worked for me. 
Thanks @Hakhenaton

**Comment by SerkanSipahi** [comment]
thanks @Hakhenaton :) It helped me as well.

**Comment by statyan** [comment]
Installing of "mini-css-extract-plugin": "2.2.0" worked for me. I used the current latest 12.7.2 version of nx. Thanks @eggp a lot!

**Comment by fuerst** [comment]
Just a note: Using Nrwl 12.9.0 and Angular 12.2.5 it works now without any workaround.

**Comment by 31piy** [comment]
I saw this again today with Nrwl v12.9.0 and Angular 12.2.7. Downgrading Angular to 12.2.5 didn't work either. Installing "mini-css-extract-plugin" solved the problem.
