### ISSUE TITLE
"generatePackageJson" does not include dependencies from `libs/*`

### ISSUE THREAD

**Issue by j** [nrwl/nx#6840]
## Current Behavior
I'm trying to create a production Nest.js build with a minimal dependency tree.  "generatePackageJson" does not include dependencies from a library within my own workspace.

Scenario:
`apps/graphql` imports `libs/config`.  `libs/config` imports `dotenv` (3rd party).  `dotenv` is not included in the `package.json` of `apps/graphql` generated file.

## Expected Behavior
I expect `dotenv` to be listed in `package.json`.

## Steps to Reproduce
1. Create nest.js app
2. Create `config` nest.js Library with `import { config } from 'dotenv';`
4. Import `config` library
5. Add `"generatePackageJson": true` option to app build target.
6. Build
7. Notice that `dotenv` does not exist in `package.json`

### Failure Logs
```
Error: Cannot find module 'dotenv'
```

### Environment

```bash
>  NX  Report complete - copy this into the issue template

  Node : 16.3.0
  OS   : darwin x64
  npm  : 7.15.1

  nx : Not Found
  @nrwl/angular : Not Found
  @nrwl/cli : 12.7.2
  @nrwl/cypress : Not Found
  @nrwl/devkit : 12.7.2
  @nrwl/eslint-plugin-nx : 12.7.2
  @nrwl/express : Not Found
  @nrwl/jest : 12.7.2
  @nrwl/linter : 12.7.2
  @nrwl/nest : 12.7.2
  @nrwl/next : Not Found
  @nrwl/node : 12.7.2
  @nrwl/nx-cloud : Not Found
  @nrwl/react : Not Found
  @nrwl/schematics : Not Found
  @nrwl/tao : 12.7.2
  @nrwl/web : Not Found
  @nrwl/workspace : 12.7.2
  @nrwl/storybook : Not Found
  @nrwl/gatsby : Not Found
  typescript : 4.3.5
```

### Extra Credit
Generated package.json should also either lock to exact package numbers or create a package.lock file.  It's probably easier to just pin down exact package numbers: `"some-pkg": "1.2.3"` instead of `"some-pkg": "^1.2.0"`

**Comment by hiepxanh** [comment]
I guess you can try to wrap it by something then import it?

**Comment by j** [comment]
@hiepxanh I'm not understanding.  The package.json should include all possible dependencies needed for the app.

**Comment by edcs** [comment]
I'm having the same issue - I have a Node.js based app which uses a lib that imports `@apollo/federation`. When I build the app with `generatePackageJson` set to `true`, the `package.json` file looks like this:

```json
{
  "name": "services-subgraphs-people",
  "version": "0.0.1",
  "dependencies": {
    "type-graphql": "^1.1.1",
    "graphql": "^15.5.1",
    "@typegoose/typegoose": "^8.2.0",
    "mongoose": "^5.13.8",
    "mongoose-lean-id": "^0.2.0",
    "tslog": "^3.2.1",
    "reflect-metadata": "^0.1.13",
    "aws-sdk": "^2.977.0",
    "apollo-server": "^3.3.0"
  },
  "main": "main.js"
}
```

Meaning that when I run it, I get an error message stating that `@apollo/federation` is missing. (There are other dependencies missing which are imported by my lib too).

**Comment by DeadEye0112** [comment]
I am having the exact same problem with the `dotenv` package missing from the generated `package.json` file when using the option `generatePackageJson`.

**Comment by nartc** [comment]
Duplicate of [https://github.com/nrwl/nx/issues/5820](https://github.com/nrwl/nx/issues/5820)

**Comment by Ion-manden** [comment]
```
        "externalDependencies": "none",
        "generatePackageJson": true
```
adding `"externalDependencies": "none"` seems to have worked for me

**Comment by HackPoint** [comment]
@vsavkin @jeffbcross 'generatePackageJson' is not found in schema in latest would you have a solution to this? Seems like it's not documented in anywhere.

**Comment by nartc** [comment]
@HackPoint can you provide a simple reproduce?

**Comment by HackPoint** [comment]
> @HackPoint can you provide a simple reproduce?

It was a simple yarn create nx-workspace pure angular project which is not created a simple workspace.json file even.

**Comment by nartc** [comment]
@HackPoint oh you're talking about initializing a new workspace with the Angular preset would yield this error?

**Comment by HackPoint** [comment]
> @HackPoint oh you're talking about initializing a new workspace with the Angular preset would yield this error?

Actually tried it on an Empty project: added angular app and a single library and it's gives me the same error.

**Comment by nartc** [comment]
@HackPoint Thank you. What is the command that triggers the error? A build command? or a run command?

**Comment by HackPoint** [comment]
> @HackPoint Thank you. What is the command that triggers the error? A build command? or a run command?

![image](https://user-images.githubusercontent.com/6758579/155399182-36b18a7c-d8ed-4bf2-bcbe-a06f6bc51481.png)

**Comment by nartc** [comment]
`sandbox` is an Angular project? `generatePackageJson` isn't in Angular's build executor schema. Why do you need `generatePackageJson` with an Angular project?

**Comment by deeeed** [comment]
> @vsavkin @jeffbcross 'generatePackageJson' is not found in schema in latest would you have a solution to this? Seems like it's not documented in anywhere.

+1, can't find any doc and facing the same issue

**Comment by trevordilley** [comment]
I ran into this issue and it turns out **I had a dependency listed in both `devDependencies` and `dependencies` in my `package.json`**, I must have pasted them there by accident, or inadvertently add a `-D` or something. 

However, once I removed them from the `devDependencies` section my generated `package.json` had everything it was supposed to!

**Comment by 31i0t** [comment]
You can find the source for `generatePackageJson` [here](https://github.com/nrwl/nx/blob/master/packages/workspace/src/utilities/create-package-json.ts).

You might be surprised to find it's just an `executor` so you can write your own if this is something you really care about. For me, I wrote something that recursively imported packages from `libs/*` along with dependencies/peerDependencies because I wanted to deploy projects installing as little deps as possible from the root package.json, but you can adapt it for your use-case. Here's the code (mind you it's not battle-tested but works for me):

```ts
import chalk from "chalk";
import { execSync } from 'child_process';
import { readJsonFile, readCachedProjectGraph, readJson } from "@nrwl/devkit";
import rJSON from "relaxed-json";
import { flow, forEach, map, filter, replace, flatMap, uniq, isNil, keys, join, toPairs, find } from "lodash/fp";

import type { ExecutorContext, ProjectGraphDependency } from "@nrwl/devkit"

interface Schema {
	preInstallPackages: string[]
}
interface FetchedPeerDependencies {
	[key: string]: string;
}

const initialPackageMatchers: (RegExp | string)[] = [
	/^@nrwl.*/,
	"nx",
	"chalk",
	"relaxed-json",
	"lodash"
]

const getLibDependencies = (
	projectName: string,
	dependencies: Record<string, ProjectGraphDependency[]>,
	libDependencies = []
) => {
	const projectDeps = dependencies[projectName];
	const libDependenciesOfProject = filter(({ target }) => !target.startsWith("npm"), projectDeps);

	forEach(({ target }) => {
		getLibDependencies(target, dependencies, libDependencies);
	}, libDependenciesOfProject)

	libDependencies.push(filter(({ target }) => target.startsWith("npm"), projectDeps))
	return flow(
		flatMap((deps: ProjectGraphDependency[]) => map(({ target }) => target, deps)),
		uniq,
	)(libDependencies)
}

const fetchPeerDependencies = (targetPackage: string): FetchedPeerDependencies => {
	const peerDependencies = execSync(`npm info ${targetPackage} peerDependencies`, { encoding: 'utf-8' });
	
	return peerDependencies === ""
		? {}
		: rJSON.parse(peerDependencies)
}

const getPeerDependencies = (packageName: string, peerDependencies = []) => {
	if (find(packageName, keys(peerDependencies))) {
		return;
	}

	const fetchedPeerDependencies = fetchPeerDependencies(packageName);
	forEach((peerDep) => {
		getPeerDependencies(peerDep);
	}, keys(fetchedPeerDependencies))

	peerDependencies.push(fetchedPeerDependencies);
	return flow(
		map((peerDeps) => keys(peerDeps)),
		flatMap((deps) => deps),
		uniq
	)(peerDependencies)
}

const installPackages = async (
	{ preInstallPackages = [] }: Schema,
	{ projectName, root }: ExecutorContext
) => {
	const {
		dependencies: rootDependencies,
		devDependencies: rootDevDependencies
	} = readJsonFile(`${root}/package.json`);
	
	const initialPackages = flow(
		keys,
		(matchers) => [...matchers, ...preInstallPackages],
		filter((dep) => Boolean(
			find((matcher) => typeof matcher === "string"
					? matcher === dep
					: matcher.test(dep)
			, initialPackageMatchers
		)))	
	)({ ...rootDevDependencies, ...rootDependencies });

	console.log(chalk.bold.green(`Identified the following initial packages:\n`))
	forEach((dep) => {
		console.log(`  ${chalk.bold(dep)}\n`)
	}, initialPackages)
	execSync(`npm install ${join(' ', initialPackages)} --no-save`);

	const { dependencies } = readCachedProjectGraph();
	const withLibDeps = getLibDependencies(projectName, dependencies)
	const withoutDevDependencies = flow(
		map((dep: string) => replace('npm:', '', dep)),
		filter((dep) => dep in rootDependencies)
	)(withLibDeps);
	const withPeerDependencies = flow(
		map((dep: string) => getPeerDependencies(dep)),
		flatMap((deps) => deps),
		(deps) => [...deps, ...withoutDevDependencies],
		uniq,
		filter((dep) => !isNil(dep)),
		filter((dep) => dep in rootDependencies)
	)(withoutDevDependencies);

	console.log(chalk.bold.green(`Identified the following dependencies:\n`))
	forEach((dep) => {
		console.log(`  ${chalk.bold(dep)}\n`)
	}, withPeerDependencies)


	
	execSync(`npm install ${join(" ", withPeerDependencies)} --no-save`)

	return { success: true }
}

export default installPackages;
```

**Comment by Gabriellji** [comment]
> 

Has anyone found any solutions for that?

**Comment by Gabriellji** [comment]
> @vsavkin @jeffbcross 'generatePackageJson' is not found in schema in latest would you have a solution to this? Seems like it's not documented in anywhere.

Has anyone found any solutions for that?

**Comment by jensbodal** [comment]
Make sure you updated to the current version of the executor(s).  

For example `@nrwl/node:build executor` is replaced with `@nrwl/node:webpack` and [supports `generatePackageJson` option](https://nx.dev/packages/node/executors/webpack#generatepackagejson) ([source code for schema](https://github.com/nrwl/nx/blob/master/packages/node/src/executors/webpack/schema.json#L130)).

A few of them were renamed here: https://github.com/nrwl/nx/pull/9086


That said, I still have the issue outlined in the initial issue, and even with some packages that are not part of my code base they aren’t being picked up in a nest project despite being directly imported in non-unit test code paths.

**Comment by 31i0t** [comment]
I needed this functionality as well and accomplished it by writing my own executor. Within an executor you can do:
```tsx
import { readCachedProjectGraph } from "@nrwl/devkit";
const { dependencies } = readCachedProjectGraph();
```
and the `dependencies` variable will have everything you need to populate dependencies from `libs/*`. To see the bulk of logic for how `generatePackageJson` works you can refer to [this](https://github.com/nrwl/nx/blob/master/packages/workspace/src/utilities/create-package-json.ts) file. I would submit a PR but I don't have the time, but I needed the same thing and accomplished it this way.

**Comment by jensbodal** [comment]
So I took a look at that, at least one of my issues seems to stem from the project graph, so looking more into that. Looking at the dependencies that are output is missing one of my imports entirely.  

We have n+1 nx monorepos.  We use a commons one to publish the majority of shared code and then a mono repo for each full-stack application (api+web+cdk).  There are other packages published by the commons package that show up just fine, but for whatever reason one of them is missing despite it being in dependencies section of root package json.

**Comment by jensbodal** [comment]
Alright fixed one of my problems with 

```
NX_CACHE_PROJECT_GRAPH=false nx build api --clear-cache
```

So hopefully now can go the route you suggested to pick up the missing lib dependencies

**Comment by vietkute02** [comment]
I face same issue. Anyone has solution for this issue?. so for now, I must copy root package.json for each project to handle missing modules

**Comment by yasinntza** [comment]
I face the same issue.

**Comment by Keith-Hon** [comment]
It happened to me and I found out that the missing module is not added to the root package.json. I cleaned the node_modules and reinstall all the dependencies and it's working now.

**Comment by npwork** [comment]
In my case there were 2 problem:

1. I had my `peerDependencies` so I moved them to `dependency` and it worked like charm


2. One of my dependencies itself had `peerDependencies`

Example:
My `package.json` 
<img width="444" alt="Screen Shot 2022-06-13 at 8 23 05 AM" src="https://user-images.githubusercontent.com/1792720/173285308-b7ad6620-4190-4de7-8b79-7c7490414ee1.png">

`@celo-tools/celo-ethers-wrapper`'s package.json

<img width="325" alt="Screen Shot 2022-06-13 at 8 23 18 AM" src="https://user-images.githubusercontent.com/1792720/173285326-908a6f9b-70cb-48f5-a562-caea522f0244.png">


Solution:
Explicitly import peerDependency
<img width="700" alt="Screen Shot 2022-06-13 at 8 23 48 AM" src="https://user-images.githubusercontent.com/1792720/173285515-02eef73b-524d-4496-9d73-2bc785cd83d7.png">

**Comment by nartc** [comment]
Hi all, the original scenario (about `dotenv`) seems to have been solved already (I can't reproduce it with the issue author's reproduce step). 

- Create a new workspace
- Generate a NestJS application with `nrwl/nest:app`
- Generate a library with `nrwl/nest:lib`
- Use a dependency in the library (eg: `dotenv`)
- Use the library in the app
- Run `npx nx build app` with `generatePackageJson: true`
- `dist/apps/app/package.json` does have `dotenv` as one of the dependencies.

<img width="858" alt="image" src="https://user-images.githubusercontent.com/25516557/175756676-2331de38-4676-4b1c-aa64-db4d0889082d.png">
`LibModule` uses `date-fns`

<img width="727" alt="image" src="https://user-images.githubusercontent.com/25516557/175756679-4b55d80d-2cc4-4696-9414-7fe319bdba52.png">
`BuildableLibModule` uses `dotenv`

<img width="1047" alt="image" src="https://user-images.githubusercontent.com/25516557/175756684-3682528a-0d47-465b-8fbc-5ae9b1b13ace.png">
Both are imported in `AppModule`

<img width="574" alt="image" src="https://user-images.githubusercontent.com/25516557/175756685-5b91893b-609b-4960-b411-8e6cbb4397b3.png">
Both dependencies show up in `dist/apps/api/package.json`

If anyone runs into a similar issue, please share your reproduce steps.

**Comment by yasinntza** [comment]
any updates?

**Comment by nartc** [comment]
@yasinntza I asked for a new reproduce to investigate further as the original issue seems to have been solved already. Check my previous message. Can you share a reproduce?

**Comment by j** [comment]
@nartc sorry; I haven't been actively developing a NX project lately and since have switched to Vite and Turborepo, however, may consider converting back to Nx as Turborepo docker builds are insanely slow when "pruning" dependencies.  My NX project I have in production uses webpack plugins to create pruned package.json files, so it's great to see that this may work out of the box now.

**Comment by dan-cooke** [comment]
@nartc  I can still reproduce this issue with OP's reproduction steps.

1. `npx create-nx-workspace --preset=nest`
<img width="891" alt="image" src="https://user-images.githubusercontent.com/22816887/181917640-de940fa2-383a-4412-a0d6-67c58290a2ee.png">

2. ` nx g @nrwl/nest:lib env`

<img width="891" alt="image" src="https://user-images.githubusercontent.com/22816887/181917750-32d510e0-99c3-4817-b2c7-5d54af29f2b3.png">

3. `npm i dotenv`
4. Add the following to `libs/env/src/index.ts`
```
import { config } from 'dotenv';

config();

```
<img width="891" alt="image" src="https://user-images.githubusercontent.com/22816887/181917832-dd7aab75-ec09-4343-9b18-6a78602580e9.png">

5. Add the following line to the nest application
```
import '@nx-bug-generate-package/env'
```

6. Add `generatePackageJson` to the webpack options
<img width="891" alt="image" src="https://user-images.githubusercontent.com/22816887/181917890-472f7576-b3a2-4de9-a1c9-8b08767e21d3.png">

7. Run `nx build api`

<img width="891" alt="image" src="https://user-images.githubusercontent.com/22816887/181917906-ccb1d36a-ba08-438b-bfe2-14cb9c007ab2.png">

**The output does not include `dotenv`**
<img width="891" alt="image" src="https://user-images.githubusercontent.com/22816887/181917937-6e812a27-f70a-4959-b207-f20445a712ee.png">

**Comment by nartc** [comment]
@dan-cooke Thank you for the steps. However, your reproduction is against 13.10.6 which is an old version. Can you try the steps again with the latest 14.5.x? If it's still an issue with 14.5.x, then I'll remove the retry-with-latest label.

**Comment by dan-cooke** [comment]
@nartc  As for OP's issue - I cannot actually reproduce, however ther are some things to note:

1. OPs issue still exists if you do not actually `export` from the lib, ie.
```
import '@repo/env'
```

2. My reproduction was actually a red herring, and thte issue is part of an underlying issue with how `nx` integrates with `tsconfig` `paths` and `baseUrl` I have opened another issue askig for some guidance here https://github.com/nrwl/nx/issues/11374

I _believe_  this current issue can be closed however, as with OP's steps (As long as you import a named export) it cannot be reproduced

**Comment by nartc** [comment]
Thanks for the clarifications.

1. I feel like Nx can (and should) make this case work but it can be a different issue.
2. For sure, please do open a new issue (feel free to tag me) for the case you're talking about here and we'll be on it

As for this issue, I'll leave it open for a bit longer to see if anything comes up. Thanks again for your time

**Comment by oncet** [comment]
I'm facing a similar issue. I generated a publishable lib that uses a MUI component but the generated `package.json` does not include the required dependencies.

Here is a repo with the minimal setup:

* https://github.com/oncet/nx-playground

What I'm missing?

**Comment by svaterlaus** [comment]
In case it helps anyone else, my solution to this issue was a bit different.

The build executor is `@nrwl/webpack:webpack` for me and `@nrwl/webpack` was missing from my devDeps in package.json. Somehow it was still building to dist/, but without the correct deps.

**Comment by Rafarel** [comment]
Thanks @svaterlaus that worked for me!
@nwrl/webpack was in node_modules because it was a dependency of another module (I guess), but installing it explicitly resolves my issue. I had none of my nest project dependencies in the generated package.json file and now it's OK!
👍
