### ISSUE TITLE
Rule 'enforce-module-boundaries' should not error 'noSelfCircularDependencies' for angular libs with secondary entrypoints

### ISSUE THREAD

**Issue by morrisjdev** [nrwl/nx#8059]
## Current Behavior
When using angular libraries with secondary entrypoints and importing things from another secondary entrypoint of the same library, the eslint rule 'enforce-module-boundaries' errors with the violation 'noSelfCircularDependencies'.

## Expected Behavior
The rule 'enforce-module-boundaries' should not get violated by a secondary entrypoint importing another entrypoints exports, because those are complete independant modules, in theory.

## Steps to Reproduce
See PR [in https://github.com/nrwl/nx-examples.](https://github.com/nrwl/nx-examples/pull/179)

Basic steps for reproduction:
1. Generate angular library (Note that it has to generate a package.json and allow secondary entrypoints)
nx generate @nrwl/angular:library --name=example-lib --importPath=@example/lib --publishable

2. Generate two secondary entrypoints for library (models/abstract and models/implementations)
nx generate @nrwl/angular:library-secondary-entry-point --name=models/abstract --library=example-lib --skipModule
nx generate @nrwl/angular:library-secondary-entry-point --name=models/implementations --library=example-lib --skipModule

3. Create some exported file in first entrypoint. Example example-model.ts:

```typescript
export interface ExampleModel {
  someField: string;
}
```

4. Use exported file in second entrypoint:

```typescript
import {ExampleModel as IExampleModel} from '@example/lib/models/abstract';

export class ExampleModel implements IExampleModel {
  someField!: string;
}
```

5. Second file in secondary entrypoint should get a linting error

### Failure Logs
ESLint: Projects should use relative imports to import from other files within the same project. Use &quot;./path/to/file&quot; instead of import from &quot;@example/lib/models/abstract&quot; (@nrwl/nx/enforce-module-boundaries)

![image](https://user-images.githubusercontent.com/20016673/145242075-c8c738c7-eb7d-44c9-a487-41e5eb8a3891.png)

### Environment
```

>  NX  Report complete - copy this into the issue template

  Node : 14.17.6
  OS   : win32 x64
  yarn : 1.22.15

  nx : 13.2.0-rc.4
  @nrwl/angular : 13.2.0-rc.4
  @nrwl/cli : 13.2.0-rc.4
  @nrwl/cypress : 13.2.0-rc.4
  @nrwl/devkit : 13.2.0-rc.4
  @nrwl/eslint-plugin-nx : 13.2.0-rc.4
  @nrwl/express : undefined
  @nrwl/jest : 13.2.0-rc.4
  @nrwl/linter : 13.2.0-rc.4
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : 12.5.4
  @nrwl/react : 13.2.0-rc.4
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.2.0-rc.4
  @nrwl/web : 13.2.0-rc.4
  @nrwl/workspace : 13.2.0-rc.4
  @nrwl/storybook : 13.2.0-rc.4
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 6.5.5
  ---------------------------------------
  Community plugins:
         @angular/animations: 13.0.2
         @angular/common: 13.0.2
         @angular/compiler: 13.0.2
         @angular/core: 13.0.2
         @angular/forms: 13.0.2
         @angular/platform-browser: 13.0.2
         @angular/platform-browser-dynamic: 13.0.2
         @angular/router: 13.0.2
         @ngrx/component-store: 13.0.1
         @ngrx/effects: 13.0.1
         @ngrx/entity: 13.0.1
         @ngrx/router-store: 13.0.1
         @ngrx/store: 13.0.1
         @angular-devkit/build-angular: 13.0.3
         @angular/cli: 13.0.3
         @angular/compiler-cli: 13.0.2
         @angular/language-service: 13.0.2
         @ngrx/store-devtools: 13.0.1
```

**Comment by Coly010** [comment]
I cannot reproduce. 
Can you try again with latest?

**Comment by morrisjdev** [comment]
The issue still persists.

Also no changes in rule code were made since reporting the issue:
https://github.com/nrwl/nx/commits/13.4.5/packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts

This piece of code (excerpt of https://github.com/nrwl/nx/blob/13.4.5/packages/eslint-plugin-nx/src/rules/enforce-module-boundaries.ts) is not sufficient to test, if an absolute import from the same project but different sub-module were made:

```ts
      // same project => allow
      if (sourceProject === targetProject) {
        // we only allow relative paths within the same project
        if (!allowCircularSelfDependency && !isRelativePath(imp)) {
          context.report({
            node,
            messageId: 'noSelfCircularDependencies',
            data: {
              imp,
            },
          });
        }
        return;
      }
```

**Comment by Coly010** [comment]
Is there a repo using the latest version of Nx that contains a reproduction of this issue that I can use?

**Comment by morrisjdev** [comment]
I updated the PR in nx-examples.

https://github.com/nrwl/nx-examples/pull/179/

**Comment by FabienDehopre** [comment]
I'm sorry but the issue is still not solved. I've just tried with the example application from @morrisjdev with the latest version of Nx and it still produce the same error.
I looked at the code of the rule and I don't understand why the call to `isAngularSecondaryEntrypoint` is made with the source file (the one that does the import) instead of the target (the import location).

**Comment by meeroslav** [comment]
You are absolutely right, @FabienDehopre. The `isSecondaryEntrypoint` should check the target file, not the source file.
I will create a fix right away. Thanks for reporting this.

**Comment by nevin-mk** [comment]
https://stackoverflow.com/a/74733579/2849695
Maybe this answer can help
