### ISSUE TITLE
Nx Micro Frontend installation fails out of the box 2

### ISSUE THREAD

**Issue by DonTomato** [nrwl/nx#8137]
Tried to setup a Micro Frontend with Angular and Nx according to the [Nx guide](https://nx.dev/l/a/guides/setup-mfe-with-angular). Second attempt after #7905.

When I execute `nx run login:serve` it displays the following error in console:
![image](https://user-images.githubusercontent.com/1098084/145816935-0e900dd9-c387-42b5-99a0-d35097453504.png)
Nevertheless it seems it works, but I can make this error to be disappeared by adding `scriptType: 'text/javascript'` to the webpack config:
```js
module.exports = {
  output: {
    uniqueName: 'login',
    publicPath: 'auto',
    scriptType: 'text/javascript'
  },
``` 

Still when I run `nx run dashboard:serve-mfe`  it started to be reloading constantly with the following error:
![image](https://user-images.githubusercontent.com/1098084/145817538-1741360d-6f5a-4ece-a8b9-2a8ae8067924.png)

I noticed that dashboard's webpack.config contains the following remote address:
```js
plugins: [
    new ModuleFederationPlugin({
      remotes: {
        login: 'http://localhost:4201/remoteEntry.js',
      },
```

If I change it to the `login@http://localhost:4201/remoteEntry.js`, reloading stops, but I get the following error in the console:
```js
plugins: [
    new ModuleFederationPlugin({
      remotes: {
        login: 'login@http://localhost:4201/remoteEntry.js',
      },
```
Error:
![image](https://user-images.githubusercontent.com/1098084/145818060-10851ac5-c3eb-4583-9f06-5ecf0f92c9c1.png)

### Environment
```
λ nx report

>  NX  Report complete - copy this into the issue template

  Node : 16.13.0
  OS   : win32 x64
  yarn : 1.22.15

  nx : 13.3.1
  @nrwl/angular : 13.3.1
  @nrwl/cli : 13.3.1
  @nrwl/cypress : 13.3.1
  @nrwl/devkit : 13.3.1
  @nrwl/eslint-plugin-nx : 13.3.1
  @nrwl/express : undefined
  @nrwl/jest : 13.3.1
  @nrwl/linter : 13.3.1
  @nrwl/nest : undefined
  @nrwl/next : undefined
  @nrwl/node : undefined
  @nrwl/nx-cloud : undefined
  @nrwl/react : undefined
  @nrwl/react-native : undefined
  @nrwl/schematics : undefined
  @nrwl/tao : 13.3.1
  @nrwl/web : undefined
  @nrwl/workspace : 13.3.1
  @nrwl/storybook : 13.3.1
  @nrwl/gatsby : undefined
  typescript : 4.4.4
  rxjs : 7.4.0
  ---------------------------------------
  Community plugins:
         @angular-architects/module-federation: 13.0.1
         @angular/animations: 13.1.0
         @angular/common: 13.1.0
         @angular/compiler: 13.1.0
         @angular/core: 13.1.0
         @angular/forms: 13.1.0
         @angular/platform-browser: 13.1.0
         @angular/platform-browser-dynamic: 13.1.0
         @angular/router: 13.1.0
         @angular-devkit/build-angular: 13.0.4
         @angular/cli: 13.0.4
         @angular/compiler-cli: 13.1.0
         @angular/language-service: 13.1.0

(node:19520) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at C:\Projects\Waste\ng-mfe2\node_modules\tslib\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by IamRKG** [comment]
is this fixed?

**Comment by IamRKG** [comment]
![image](https://user-images.githubusercontent.com/21280947/145988092-2ae20349-1b96-4b84-9501-c43a6ca189fc.png)

getting import.meta error too

**Comment by Coly010** [comment]
I will investigate now. I believe the Nx Guide on MFEs needs to be updated. I will do so now too.

It would be very helpful to see a repo so I can identify any specific errors.

The error with `styles.js` is _ok_. It's an error output but it does not affect your CSS. Also, when you build your app for production, there is no `styles.js` file as it gets compiled to a CSS file, so the error does not propagate to production.

The error around the remoteEntry is an error, but it will be due to a misconfigured Webpack config.

**Comment by IamRKG** [comment]
Thanks @Coly010 . I am waiting for your update to create new MFE application.

**Comment by DonTomato** [comment]
@Coly010 repo with example: [Repo](https://github.com/DonTomato/ng-mfe2)

**Comment by Coly010** [comment]
@DonTomato looking at your repo, the two webpack configs appear have conflicting properties set.

you have both `scriptType` set as well as `library: { type: “module” }`.

can you remove `library: { type: “module” }` from both of the webpack configs and try again?

**Comment by DonTomato** [comment]
@Coly010 done.
Now both app display an error `Uncaught SyntaxError: Cannot use 'import.meta' outside a module`
And shell app `dashboard` is constantly reloading with error:
![image](https://user-images.githubusercontent.com/1098084/146017508-26de631a-75c8-497f-9666-e26af9affd47.png)

**Comment by Coly010** [comment]
@DonTomato It looks like you removed too much when you made your changes.

I've created a PR on your repo that showcases the correct config. Tested locally and it works: https://github.com/DonTomato/ng-mfe2/pull/1

I've copied the config to here for one of the files: 
```ts
module.exports = {
  output: {
    uniqueName: 'login',
    publicPath: 'auto',
    scriptType: 'text/javascript',
  },
  optimization: {
    runtimeChunk: false,
    minimize: false,
  },
  experiments: {
    outputModule: true,
  },
  resolve: {
    alias: {
      ...sharedMappings.getAliases(),
    },
  },
  plugins: [
    new ModuleFederationPlugin({
      name: 'login',
      filename: 'remoteEntry.js',
      exposes: {
        './Module': 'apps/login/src/app/remote-entry/entry.module.ts',
      },
      shared: {
        '@angular/core': { singleton: true, strictVersion: true },
        '@angular/common': { singleton: true, strictVersion: true },
        '@angular/common/http': { singleton: true, strictVersion: true },
        '@angular/router': { singleton: true, strictVersion: true },
        ...sharedMappings.getDescriptors(),
      },
    }),
    sharedMappings.getPlugin(),
  ],
};
```

Notice 2 things. 
1. We have kept `scriptType="text/javascript"`
2. We have removed
```ts
library: {
  type: "module"
}
```

**Comment by Coly010** [comment]
The guide does need updated, but there is one further issue that needs addressed for the out of box experience.
We need to ensure that webpack version 5.64.4 is installed.

**Comment by DonTomato** [comment]
@Coly010 thanks a lot! Strange, it seems to me I did it exactly as you with no luck. Probably I forgot to restart servers (missed that webpack config changes aren't applied with hot reloading). Btw, I added `scriptType="text/javascript"` manually. Probably it should be included into autogenerated webpack config.

**Comment by Coly010** [comment]
@DonTomato You can read more here: https://github.com/angular-architects/module-federation-plugin/blob/main/migration-guide.md

`scriptType: text/javascript` is a workaround for a different issue. We thought we had the other issue fixed for out-of-box experience, but I missed something, so I'll be creating a PR soon to patch that up.

**Comment by Coly010** [comment]
The out-of-the-box MFE experience should be fixed and available now in Nx 13.3.6.

Closing this, if you need any additional help, reply back here :)

**Comment by DonTomato** [comment]
@Coly010 thanks, now everything works.
but I still have the error in console `Uncaught SyntaxError: Cannot use 'import.meta' outside a module`. What is the reason?

**Comment by Coly010** [comment]
When serving MFEs in dev mode locally, there'll be an error output to the console, import.meta cannot be used outside of a module, and the script that is coming from is styles.js. It's a known error output, but it doesn't actually cause any breakages from as far as our testing has shown. It's because Angular compiler attaches the styles.js file to the index.html in a script tag with defer. 
It needs to be attached with type=module, but Angular won't make the change because it breaks HMR. They also provide no way of hooking into that process for us to patch it ourselves.

The good news is that the error doesn't propagate to production, because styles are compiled to a CSS file , so there's no erroneous JS the log an error. 

It's worth stressing that there's been no actual errors or breakages noted from our tests.

**Comment by DonTomato** [comment]
Thanks for explanation!

**Comment by shiza-khaliq** [comment]
When I added this ScriptType in Host webConfig I got Build error external "http://localhost:4200/remoteEntry.js" - Error: Invalid request "http://localhost:4200/remoteEntry.js" Please Help me out I have tried all ways
