### ISSUE TITLE
Bug(testing): unsupported .js extension

### ISSUE THREAD

**Issue by sandangel** [nrwl/nx#82]
I had checked the new angular 5 with nx workspace. When I run ng test, the following error has occurred:

```bash
ERROR in error TS6054: File '.../Angular/mdb-admin/test.js' has unsupported extension. The only supported extensions are '.ts', '.tsx', '.d.ts'.
```
Any fix on this?

**Comment by Silthus** [comment]
Did you find a fix? I have the same problem.

**Comment by sandangel** [comment]
I guess we have to write this test file in typescript. ^^

**Comment by sean-perkins** [comment]
@Silthus 

In the root of your project, rename `test.js` to `test.ts`. 

Here's the updated TypeScript version for that file and NX:
```
// This file is required by karma.conf.js and loads recursively all the .spec and framework files
import 'zone.js/dist/long-stack-trace-zone';
import 'zone.js/dist/proxy.js';
import 'zone.js/dist/sync-test';
import 'zone.js/dist/jasmine-patch';
import 'zone.js/dist/async-test';
import 'zone.js/dist/fake-async-test';
import { getTestBed } from '@angular/core/testing';
import {
    BrowserDynamicTestingModule,
    platformBrowserDynamicTesting
} from '@angular/platform-browser-dynamic/testing';

// Unfortunately there's no typing for the `__karma__` variable. Just declare it as any.
declare const __karma__: any;
declare const require: any;

// Prevent Karma from running prematurely.
__karma__.loaded = function () { };

// First, initialize the Angular testing environment.
getTestBed().initTestEnvironment(
    BrowserDynamicTestingModule,
    platformBrowserDynamicTesting()
);
// Then we find all the tests.
const context = require.context('./apps', true, /\.spec\.ts$ /);
// And load the modules.
context.keys().map(context);

const contextLibs = require.context('./libs', true, /\.spec\.ts$/);
// And load the modules.
contextLibs.keys().map(contextLibs);
// Finally, start Karma to run the tests.
__karma__.start();

```

Update `tsconfig.spec.json` so that the `files` section references `test.ts` instead of `test.js`.

Lastly, update your `.angular-cli.json` so that all references of:
```
"test": "../../../test.js",
```

are updated to:
```
"test": "../../../test.ts",
```

**Comment by Silthus** [comment]
@sean-perkins thanks for the `test.ts` file.
Do you also have the problem that tests inside the apps folder are not run? When I run ng test only tests inside the libs folder are run. The same goes for ng test --app=myapp.

**Comment by vsavkin** [comment]
The issue has been fixed in 0.1.1. Could you provide a repro using 0.1.1?

**Comment by sandangel** [comment]
I will give it a shot with 0.2

**Comment by sandangel** [comment]
no, this is not fixed in 0.2
<img width="745" alt="screen shot 2017-11-18 at 12 19 04" src="https://user-images.githubusercontent.com/22189661/32976511-bf5f5756-cc5a-11e7-9764-7f7e8a9d6630.png">

as well as in 0.1.1:

<img width="432" alt="screen shot 2017-11-18 at 12 20 33" src="https://user-images.githubusercontent.com/22189661/32976519-e77116bc-cc5a-11e7-9576-bf049eb4f457.png">

**Comment by vsavkin** [comment]
@sandangel could you provide a repro of a project created with 0.2.0?

**Comment by sandangel** [comment]
@vsavkin sorry but did you that I'm only use command
`ng new pro -c=@ngrl/schematics --skip-install` and the test.js file appear in generated file list?
Do I have to generate a new project and upload to github? This is just about file generate and I don't know how to provide a better repro steps than screenshot.

**Comment by sandangel** [comment]
<img width="383" alt="screen shot 2017-11-27 at 7 41 43" src="https://user-images.githubusercontent.com/22189661/33245098-77bec204-d346-11e7-9350-02e7ac764176.png">
This is a screenshot with nrwl 0.2.1

**Comment by dereklin** [comment]
@sean-perkins Your test.ts has an extra white space in:
```
const context = require.context('./apps', true, /\.spec\.ts$ /);
```
It should be:
```
const context = require.context('./apps', true, /\.spec\.ts$/);
```
Furthermore, in my project, I had to put in the app path in order for the tests go to through:
```
const context = require.context('./apps/app1', true, /\.spec\.ts$/);
```
Without appending /app1, the modules were not loaded properly in the tests.  Is there another way to address this?

**Comment by vsavkin** [comment]
Some context:
When switching from Angular 4 to Angular 5, we hit the same issue you are seeing now. We had to tweak the tsconfig.spec.json file to work properly. This is how it should look right now:
```
{
  "extends": "./tsconfig.json",
  "compilerOptions": {
    "outDir": "./out-tsc/spec",
    "module": "commonjs",
    "target": "es5",
    "types": [
      "jasmine",
      "node"
    ],
    "baseUrl": ".",
    "paths": {
      "@myprojectname/*": [
        "libs/*"
      ]
    }
  },
  "include": [
    "**/*.ts"
  ],
  "exclude": [
    "node_modules",
    "tmp"
  ]
}
``` 

SO I think the issue is with the fact that you have another version of schematics installed globally. To see if this is the case you can use this script to create a project (https://nrwl.io/nx/guide-getting-started). If the created project works fine, then you have an old version of schematics installed globally. If it doesn't, then it's something else. In this case, could you upload the project to github, so I can take a look at it?

Finally, we added support for migrations, so we can automatically modify your config files, so you won't have such issues in the future.

**Comment by sandangel** [comment]
@vsavkin Here is my global @nrwl/nx version
![image](https://user-images.githubusercontent.com/22189661/33531421-2b5bf3fc-d8d0-11e7-9ceb-73db98e558d6.png)

Here is the generated new project
https://github.com/sandangel/nx-bug-test

**Comment by vsavkin** [comment]
Both the repos work for me. I think the issue you are seeing is due to this has been fixed here:
 https://github.com/nrwl/nx/commit/a7f06edf5914212bcefbafb1198d262e9692cfdb

**Comment by sandangel** [comment]
@vsavkin Sorry for misunderstood. I thought the generated file should be test.ts, not test.js, and the issue is nx/schematics should generate test.ts like angular/cli. Then when I create a new project and test.js still appears, I thought the issue was not solved.

**Comment by Nxt3** [comment]
This issue is still present. When generating new apps, it generates `test.js` instead of `test.ts`. Manually fixing this is a pain.

**Comment by vsavkin** [comment]
- It should generate test.js, not test.ts. The tests are set up a bit differently in a workspace, comparing to  the standard CLI project.   
- are you using create-nx-workspace to create your project? 
- could you zip up your project with its node modules and upload it somewhere?

**Comment by Nxt3** [comment]
@vsavkin I know it is supposed to. But why not do test.ts? It's what Angular CLI uses by default now so I'd expect nrwl do the same.

**Comment by vsavkin** [comment]
>> However, we're using test.ts. If I change the name to test.js so that I don't have to change the .angular-cli.json every time--you get an error:

If you are moving your existing project into the workspace, by making it an app, you should do without `test.ts` because it is shared between all the apps. So your existing project and the workspace won't have the same test.ts. 

>> I strongly believe nrwl should be generating and referencing test.ts since that's what @angular/cli does by default now.

Agree. We generate test.js because of we had an issue with an older version of the CLI. The issue might be fixed right now. If you submit a PR changing the application schematic to generate test.ts, I'll merge it.

**Comment by vsavkin** [comment]
Closing this issue because we intentionally generate `test.js` file instead of `test.ts`. 

If someone opens a PR changing to test.ts, I'll merge it :)
