### ISSUE TITLE
Storybook: Cannot render the background image in CSS correctly

### ISSUE THREAD

**Issue by dawangraoming** [nrwl/nx#8300]
## Current Behavior

When using image file in `module.scss`, the background image cannot be displayed correctly in the storybook,

and the image file actually generated are damaged.

## Expected Behavior

Can use the background image in module.css and show it.

### Create a project
```bash
# 1.  create project
npx create-nx-workspace project-name --preset=next --style=scss --appName=app-name

# 2. generate libray, named `uikit`
nx generate @nrwl/react:library --name=uikit --style=scss --linter=eslint --unitTestRunner=jest --pascalCaseFiles --publishable --buildable --component --strict --no-interactive

# 3. add storybook to project
yarn add --dev @nrwl/storybook
nx g @nrwl/react:storybook-configuration uikit

```

### Add some code and file

1. add a image file into `libs/uikit/src/lib` folder, like `libs/uikit/src/lib/demo.png`

2. modify `libs/uikit/src/lib/Uikit.module.scss` file, like:
```scss
.background {
  background: url('demo.png'); // add image to here
  background-size: 100%;
  width: 100px;
  height: 100px;
}
```

3. modify `libs/uikit/src/lib/Uikit.tsx` file, like:
```typescript
import s from  './Uikit.module.scss'; // modified
import { FC } from 'react';

export interface UikitProps {
  name: string;
}

export const Uikit: FC<UikitProps> = ({ name }) => {
  return (
    <div className={s.background}> // modified
      <h1>Welcome to Uikit! {name}</h1>
    </div>
  );
};

export default Uikit;

```

And finally execute the command to launch the StoryBook service

```bash
nx run uikit:storybook
```

### Failure Logs
None

### Environment
- Node.js: 14.18.2
- @nrwl/cli: 13.1.2
- @nrwl/storybook: 13.4.1
- @storybook/builder-webpack5: 6.3.12

**Comment by kaspar-naaber** [comment]
I ran into the same problem and it seems that this image url is converted to some hash url that returns a broken base64 image.

**Comment by mandarini** [comment]
Hm @kaspar-naaber @dawangraoming  I would think that this is an issue with Storybook or even React, and not Nx. I will try and see if the same issue exists in pure React/Storybook setups.

**Comment by mandarini** [comment]
@kaspar-naaber @dawangraoming I was wrong, it's a Nx-only thing, image renders correctly in pure React/Storybook setups.

@kaspar-naaber the image URL is properly converted, this is not what's causing the issue (same thing happens in pure React/Storybook setups and image renders correctly). What troubles me is that the image is not added in the build, so it's not served. I'm looking into it.

**Comment by kaspar-naaber** [comment]
Thank you for the quick fix. PNG-s seems to work now. But there seems to be the same problem with the SVG format. For example if you use it like this:

```css
background: url('demo.svg');
```

**Comment by mandarini** [comment]
@kaspar-naaber can you verify if this happens when you serve the React app (`nx serve my-react-app`), or if it's only on the Storybook side?

**Comment by kaspar-naaber** [comment]
It also appears to be happening in both - the Storybook and the react app as well.

It links to a SVG that is not rendering correctly:
**Storybook:**
<img width="421" alt="Screen Shot 2022-02-04 at 12 40 13" src="https://user-images.githubusercontent.com/3191867/152515280-7fa75295-7652-42b8-bfba-3029b7cf6c1b.png">

<img width="727" alt="Screen Shot 2022-02-04 at 12 36 41" src="https://user-images.githubusercontent.com/3191867/152515326-4610a795-99b6-4152-a439-2534e2c9b4c7.png">

**React app (Next.JS)**
<img width="560" alt="Screen Shot 2022-02-04 at 12 40 28" src="https://user-images.githubusercontent.com/3191867/152515404-f606b970-8be8-45fa-a7af-29176f4e0ac0.png">

<img width="698" alt="Screen Shot 2022-02-04 at 12 38 49" src="https://user-images.githubusercontent.com/3191867/152515435-b0528678-ec5f-416e-a005-e3493d78fce3.png">

**Comment by mandarini** [comment]
Hm weird, this has been fixed in the latest versions. Can you please share a reproduction repository?

**Comment by kaspar-naaber** [comment]
Still happens to me with the latest version of NX also. Are you sure that the SVG usage is also fixed? Because as far as I know you fixed using the PNG-s.

**Comment by mandarini** [comment]
@jaysoo pinging you in case you have any input for this! :)

**Comment by bawdeveloppement** [comment]
The issue for svg file still happening in the latest version at this date
