### ISSUE TITLE
Failed to load plugin '@nrwl/nx' declared in 'apps/project/.eslintrc.json » ../../../.eslintrc.js#overrides[1]': Cannot find module '@swc/core-linux-x64-gnu'

### ISSUE THREAD

**Issue by jogelin** [nrwl/nx#8969]
## Current Behavior

Since the upgrade the Nrwl 13+, when I run the affected lint target on the CI (azure devops), I got this error on all projects:

```
Failed to load plugin '@nrwl/nx' declared in 'apps/shared-ui-e2e/.eslintrc.json » ../../../.eslintrc.js#overrides[1]': Cannot find module '@swc/core-linux-x64-gnu'
Require stack:
- /var/vsts/temporary-agent-grizzly-l4j54/1/s/node_modules/@swc/core/binding.js
- /var/vsts/temporary-agent-grizzly-l4j54/1/s/node_modules/@swc/core/index.js
- /var/vsts/temporary-agent-grizzly-l4j54/1/s/node_modules/@swc-node/core/lib/index.js
- /var/vsts/temporary-agent-grizzly-l4j54/1/s/node_modules/@swc-node/register/lib/register.js
- /var/vsts/temporary-agent-grizzly-l4j54/1/s/node_modules/@nrwl/eslint-plugin-nx/src/resolve-workspace-rules.js
- /var/vsts/temporary-agent-grizzly-l4j54/1/s/node_modules/@nrwl/eslint-plugin-nx/src/index.js
- /var/vsts/temporary-agent-grizzly-l4j54/1/s/node_modules/@eslint/eslintrc/dist/eslintrc.cjs
Referenced from: /var/vsts/temporary-agent-grizzly-l4j54/1/s/.eslintrc.js
```

I already put a comment on this closed issue: #8735.
@meeroslav also made a PR #8831 that should fix the issue on 13.7.3  but I am still having it.

For the moment I have to install the library each time I run a lint command on the CI:
```
 yarn add @swc/core-linux-x64-gnu --dev
```
But this is increasing a lot of the time to the CI process

## Expected Behavior
To not have this error

## Steps to Reproduce
`yarn affected:lint`

### Environment
```
   Node : 16.13.1
   OS   : darwin x64
   yarn : 1.22.17

   nx : 13.8.1
   @nrwl/angular : 13.8.1
   @nrwl/cli : 13.8.1
   @nrwl/cypress : 13.8.1
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.1
   @nrwl/eslint-plugin-nx : 13.8.1
   @nrwl/express : undefined
   @nrwl/jest : 13.8.1
   @nrwl/js : 13.8.1
   @nrwl/linter : 13.8.1
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : 13.8.1
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.1
   @nrwl/tao : 13.8.1
   @nrwl/web : 13.8.1
   @nrwl/workspace : 13.8.1
   typescript : 4.5.5
   rxjs : 7.5.4
   ---------------------------------------
   Community plugins:
   	 @angular/animations: 13.2.2
   	 @angular/cdk: 13.2.2
   	 @angular/common: 13.2.2
   	 @angular/compiler: 13.2.2
   	 @angular/core: 13.2.2
   	 @angular/forms: 13.2.2
   	 @angular/material: 13.2.2
   	 @angular/platform-browser: 13.2.2
   	 @angular/platform-browser-dynamic: 13.2.2
   	 @angular/router: 13.2.2
   	 @auth0/auth0-angular: 1.7.0
   	 @ngneat/edit-in-place: 1.6.1
   	 @ngneat/transloco: 3.1.3
   	 @ngrx/component: 13.0.2
   	 @ngrx/component-store: 13.0.2
   	 ng2-charts: 3.0.8
   	 single-spa-angular: 6.0.1
   	 @angular-builders/custom-webpack: 13.1.0
   	 @angular-devkit/architect: 0.1302.3
   	 @angular-devkit/build-angular: 13.2.3
   	 @angular/cli: 13.2.3
   	 @angular/compiler-cli: 13.2.2
   	 @angular/language-service: 13.2.2
   	 @compodoc/compodoc: 1.1.18
   	 @ngneat/spectator: 10.0.0
   	 @storybook/angular: 6.4.19
   	 @twittwer/compodoc: 1.6.6
```

**Comment by JosefBredereck** [comment]
Same goes for win with `@swc/core-win32-x64-msvc`

```
Error: Failed to load plugin '@nrwl/nx' declared in '.eslintrc.json#overrides[1]': Cannot find module '@swc/core-win32-x64-msvc'
```

**Comment by meeroslav** [comment]
Hi @jogelin, thank you for reporting the issue.

You should definitely not install `@swc/core-linux-x64-gnu` on CI during your pipeline. It should already be set in your lock file as an optional dependency. Can you please check for it in the `package-lock.json` or `yarn.lock`? If not there, you might need to delete the node_modules and your lock file and run install (`npm install` or `yarn`) to regenerate them again. 
All the `@swc/core-linux-*` should be added as an optional dependency, so your CI machine would pick them up on the install phase. Please have in mind that if you cache `node_modules` on CI, you would have to invalidate the CI cache as well.

Let me know if this helped.

**Comment by meeroslav** [comment]
@JosefBredereck Thank you for reporting. I will have a look at the windows issue soon. 

In the meantime can you check this thread, since the issue lies within @swc-project https://github.com/swc-project/swc/issues/1351

**Comment by bubblegumsoldier** [comment]
Hi, I am having the same issue, but not with yarn but with npm. I have checked the package-lock.json where I find the "@swc/core-linux-x64-gnu" as an "optionalDependency" in "node_modules/@swc/core" and "node_modules/@nrwl/eslint-plugin-nx" and and as "requires" in "@nrwl/eslint-plugin-nx" and "@swc/core". I am using the `npm ci` command which takes care of not caching the node_modules folder. Thus neither one could really be the problem. Any ideas or recommendations?

**Comment by kasparsuvi1** [comment]
Hi, I am having kind of the same issue. Updated nx to latest and deleted node_modules/package-lock.
Linting in project is working, but VSCode Eslint output channel is showing me same errors: 
`UnhandledPromiseRejectionWarning: Error: Failed to load plugin '@nrwl/nx' declared in '.eslintrc.json': Cannot find module '@swc/core-win32-x64-msvc'`
Using Windows and npm

And I assume this is the problem why vscode cant underline eslint errors. Tho when running `nx affected:lint --all` all the errors and warning are provided.

**Comment by severinkl** [comment]
Same error here. The error appears only when using the no optional parameter `npm install --no-optional` since my package-lock.json evaluates the missing module as an optional dependency.

`npm install` works perfectly fine.

**Comment by meeroslav** [comment]
@kasparsuvi1, the workspace rules are separated from the standard linter.

Can you tell me on which file you see these errors? Did you try restarting the ESLint server in VSCode?

![Screenshot 2022-02-18 at 11 37 33](https://user-images.githubusercontent.com/881612/154666818-a0f00ac2-0d93-4bf7-a766-04bcf5cd5277.png)

Check if you have following folder `node_modules\@swc\core-wind32-x64-msvc`. If not check if it exists in the `package-lock`. You might need to reset your npm cache and restart the whole process (deleting files, running the install again, restarting ESLint Server) if it's missing. 

```
npm cache clean --force
```

**Comment by kasparsuvi1** [comment]
@meeroslav , Thanks for suggestions.

I get the error on every file eslint is trying to lint.
I don't have `node_modules\@swc\core-wind32-x64-msvc`, but only `node_modules\@swc\core-win32-ia32-msvc`. In package lock  `@swc/core-win32-x64-msvc` is present as:
 
`
    "@swc/core-win32-x64-msvc": {
      "version": "1.2.140",
      "resolved": "https://registry.npmjs.org/@swc/core-win32-x64-msvc/-/core-win32-x64-msvc-1.2.140.tgz",
      "integrity": "sha512-OtRarHcQ30WrkmIUXB96K1h1bsY830POJ0kb02VxTn/U9366BWs42fIoURa+637jPCZLfAceln10jxjfII1Iyg==",
      "dev": true,
      "optional": true
    },
`

Its not getting installed after cleaning cache as well.
(Seems like my local issue?)

**Comment by kasparsuvi1** [comment]
@meeroslav , thanks for suggestions.

Cleaning cache doesn't help. But i don't see `node_modules\@swc\core-wind32-x64-msvc` getting installed, only `node_modules\@swc\core-win32-ia32-msvc`  .

But inside package-lock it is as optional dependencie:
`
    "@swc/core-win32-x64-msvc": {
      "version": "1.2.140",
      "resolved": "https://registry.npmjs.org/@swc/core-win32-x64-msvc/-/core-win32-x64-msvc-1.2.140.tgz",
      "integrity": "sha512-OtRarHcQ30WrkmIUXB96K1h1bsY830POJ0kb02VxTn/U9366BWs42fIoURa+637jPCZLfAceln10jxjfII1Iyg==",
      "dev": true,
      "optional": true
    },
`
It seems to be problem that what OS arch u have. Mine is: {"os":"win32","arch":"ia32"} not {"os":"win32","arch":"x64"} . Im looking into it.

**Comment by kasparsuvi1** [comment]
@meeroslav , thanks for recommendations. 

I dont get `node_modules\@swc\core-wind32-x64-msvc` installed not even after cache clean and new install. Only `node_modules\@swc\core-wind32-ia32-msvc` is installed.
Under package-lock there is `core-wind32-x64-msvc`, but as optional.  I think i have wrong architecture of windows for that? When i try to change it to required dependencie i get error:
`Unsupported platform for @swc/core-win32-x64-msvc@1.2.140: wanted {"os":"win32","arch":"x64"} (current: {"os":"win32","arch":"ia32"})`

Should i change my os architecture?

**Comment by meeroslav** [comment]
It should be marked as optional. That is intentional. What that means is that if the underlying architecture doesn't support it, it will not break the `npm install`.

Based on your error, it seems that you have the correct one installed already (`{"os":"win32","arch":"ia32"}` and `@swc\core-wind32-ia32-msvc` installed). If linter is looking for `@swc/core-win32-x64-msvc`, that might be an error in the `@swc-node/register` implementation.

Perhaps @Brooooooklyn has some insights?

**Comment by Brooooooklyn** [comment]
One possible scenario is that the 32-bit version of Node.js is installed and the 64-bit version of VSCode is installed. That is why `@swc\core-wind32-ia32-msvc` installed but `eslint vscode plugin` want to load `@swc\core-wind32-x64-msvc`

**Comment by meeroslav** [comment]
Thank you @Brooooooklyn, I didn't consider that angle.

@kasparsuvi1 are you running lint from the terminal or using the plugin from the IDE?

**Comment by kasparsuvi1** [comment]
From the terminal linting works, plugin from the IDE does not. Maybe I have messed up versions of node/vscode, trying to fix reinstalling those in 64-bit versions. Thanks for the help!

**Comment by zoechi** [comment]
@meeroslav but it's now not optional anymore https://github.com/nrwl/nx/pull/9142/files or did I misinterpret something

**Comment by meeroslav** [comment]
@zoechi if you look at `"@swc/core"` dependencies in the lock file you will notice that it has all those dependencies, marked as optional: https://github.com/nrwl/nx/blob/master/yarn.lock#L5663-L5680

`@swc-node/register` depends on `@swc-node/core` which depends on `@swc/core`.
I explicitly added optional dependencies the first time while trying to solve this issue, due to misleading information on related issues, but the problem turned out to be in the stale node_modules/lock combo.

**Comment by ubergeoff** [comment]
Had this same issue in my CI

Used to have:

`npm ci --no-optional`

Changed to: 

`npm ci` 

Working again...

**Comment by meeroslav** [comment]
Yeah `no-optional` will definitely break it

**Comment by pobutp** [comment]
In my case problem was fixed by `npm i @swc/core`.

**Comment by shaharkazaz** [comment]
@meeroslav I've tried all of the above but I'm still having the issue.
[Here](https://github.com/ngneat/transloco/runs/5660959145?check_suite_focus=true) is the CI run that fails. 
I've searched my `package-lock.json` and found the optional dependencies.
Any idea?

**Comment by meeroslav** [comment]
Hey, @shaharkazaz I'm sorry for your trouble.
The issue is here: https://github.com/ngneat/transloco/blob/master/package-lock.json#L23459-L23482
You can see that although all the `@swc/core-...` packages are marked as optional in `@swc/core` your lock file only added explicitly the one for macOS. Looking at the lock file there seems to be some other information missing such as integrity hashes and direct paths to resolved versions. Not sure how your lock file was generated, but it's obviously malformed.

I created a PR that solve it: https://github.com/ngneat/transloco/pull/552

**Comment by meeroslav** [comment]
You should also update the node version to v16 on your CI runs, since this is the LTE now.

**Comment by shaharkazaz** [comment]
@meeroslav I appreciate the PR!
I re-created the lock locally on my computer, nothing special (I'm using macOS).
npm version: 8.4.0
node version: 14.8.2

**Comment by meeroslav** [comment]
Perhaps you should consider updating to node v16. Not sure if that's the issue.

Btw, your CI was running `npm i` instead of `npm ci` so it was overriding the lock file every time.

**Comment by StephenStrickland** [comment]
I'm also randomly seeing this issue in my CI environment (ADO, ubuntu-latest), it seems to fix itself after doing several iterations of: clearing nx cache, deleting `node_modules`, deleting `package-lock.json`, `npm i` to rebuild the lockfile. Any suggestions? I didn't start having these issues until I did a recent nx migration from `13.2.0` to latest `13.9.6`. Is this is some kind of regression between `13.2` to `13.9`? I've seen several other tickets logged with similar behavior over the last several months.

**Comment by meeroslav** [comment]
@StephenStrickland we recently switched from using `ts-node` to `swc/node` for the transpilation of linter rules. This made reaching large performance increases for workspace-lint possible. 

Unfortunately, the downside is that `npm` depending on the node version can mess up the packages with automated updates and most likely requires a clean reinstall to untangle itself. With yarn and pnpm we didn't notice those issues.

**Comment by StephenStrickland** [comment]
@meeroslav thanks for the reply, implemented `pnpm` on a few other projects, this will probably lead me to do the same to reduce/eliminate this issue.

**Comment by marcintokarski** [comment]
This is probably problem related to npm and package-lock.json. I had the same problem on CI (docker), when package-lock.json was generated on windows by npm@8.3.1. I upgraded npm to 8.5.1 and regenerate package-lock.json (still on windows), and everything start works locally and on CI :)

**Comment by wobo-nate** [comment]
When this happened to me with github actions failing to install the optionalDependencies, I was able to fix it by ensuring that my project had a direct `devDependency` on `nx`. It was insufficient to have a devDependency on `@nrwl/cli`. 🤷 
```
devDependencies: {
  "nx": "13.9.5",
  // ...
}
```
This is surprising to me because the [official nx example repo](https://github.com/nrwl/nx-examples/blob/master/package.json#L60) does not have this direct dependency.

**Comment by meeroslav** [comment]
@nrwl/cli is replaced by nx, so you don't actually need them both. You just need the Nx. And Nx-examples repo actually has it as a dependency: https://github.com/nrwl/nx-examples/blob/ff6a4856d3d5337205362d264b681fe849dbf7a0/package.json#L101
