### ISSUE TITLE
Next app build failing due to eslint error - Plugin "react-hooks" was conflicted (Post update to 13.9.5 versions)

### ISSUE THREAD

**Issue by writam-roy** [nrwl/nx#9617]
## Current Behavior

Whenver I run build of my next app it fails giving this error - 
Plugin "react-hooks" was conflicted between "apps\app-shell-ssr\.eslintrc.json » eslint-config-next/core-web-vitals » C:\Sprint-8.6\idp-app-seed-ui-template\node_modules\eslint-config-next\index.js » plugin:react-hooks/recommended" and "apps\app-shell-ssr\.eslintrc.json » ../../.eslintrc.json".
## Expected Behavior

Next app builds should be fine after updating from 13.5.3 versions to 13.9.3(I used nx migrate)
## Steps to Reproduce

here is my eslintrc.json 
{
  "extends": [
    "plugin:@nrwl/nx/react-typescript",
    "../../.eslintrc.json",
    "next",
    "next/core-web-vitals"
  ],
  "ignorePatterns": [
    "!**/*"
  ],
  "overrides": [
    {
      "files": [
        "*.ts",
        "*.tsx",
        "*.js",
        "*.jsx"
      ],
      "parserOptions": {
        "project": [
          "apps/app-shell-ssr/tsconfig(.*)?.json"
        ]
      },
      "rules": {
        "@next/next/no-html-link-for-pages": ["error", "apps/app-shell-ssr/pages"]
      }
    },
    {
      "files": [
        "*.ts",
        "*.tsx"
      ],
      "rules": {}
    },
    {
      "files": [
        "*.js",
        "*.jsx"
      ],
      "rules": {}
    }
  ]
}
and lint config within project.json
  "lint": {
      "executor": "@nrwl/linter:eslint",
      "outputs": ["{options.outputFile}"],
      "options": {
        "lintFilePatterns": [
          "apps/app-shell-ssr/**/*.{ts,tsx,js,jsx}"
        ]
      }
    },

Cannot share PR links,as it is for a private repo

This issue may not be prioritized if details are not provided to help us reproduce the issue.

### Failure Logs

![image](https://user-images.githubusercontent.com/84510770/160902869-36cd3de3-51d0-4098-9c7e-43a2ba6c5b38.png)

### Environment

  Node : 16.14.2
   OS   : win32 x64
   yarn : 1.21.1

   nx : 13.9.5
   @nrwl/angular : Not Found
   @nrwl/cypress : 13.9.5
   @nrwl/detox : Not Found
   @nrwl/devkit : 13.9.5
   @nrwl/eslint-plugin-nx : 13.9.5
   @nrwl/express : 13.9.5
   @nrwl/jest : 13.9.5
   @nrwl/js : 13.9.5
   @nrwl/linter : 13.9.5
   @nrwl/nest : 13.9.5
   @nrwl/next : 13.9.5
   @nrwl/node : 13.9.5
   @nrwl/nx-cloud : Not Found
   @nrwl/nx-plugin : Not Found
   @nrwl/react : 13.9.5
   @nrwl/react-native : Not Found
   @nrwl/schematics : Not Found
   @nrwl/storybook : 13.5.3
   @nrwl/web : 13.9.5
   @nrwl/workspace : 13.9.5
   typescript : 4.3.5
   rxjs : 6.6.7

**Comment by AgentEnder** [comment]
Its possibly unrelated, but it looks like storybook is a bit behind in your repo. Can you try running `nx migrate @nrwl/storybook@13.9.5`

**Comment by vinicius5581** [comment]
Any updates to this? I'm dealing with a similar issue:

```
error - ESLint: Plugin "@next/next" was conflicted between ".eslintrc.json » eslint-config-next/core-web-vitals » plugin:@next/next/core-web-vitals" and "../../../.eslintrc.json » eslint-config-next/core-web-vitals » plugin:@next/next/core-web-vitals".
```

**Comment by Vanals** [comment]
I am having the same issues with an `npx create-next-app@latest` app

**Comment by g035653** [comment]
ERROR in Plugin "react" was conflicted between "package.e_modules\eslint-config-react-app\base.js" and "BaseConft-app\base.js".
how can i fix it??

**Comment by ndcunningham** [comment]
@writam-roy Have you tried using the latest Nx and Nextjs?

You could also remove `plugin:@nrwl/nx/react-typescript` which should resolve the conflicts.

**Comment by jdecastroc** [comment]
I can reproduce on latest NX 14 version as well

Node: 16.14.2
OS: MacOS Monterey 12.3.1
yarn: 1.22.17

nx: 14.3.2
typescript: 4.7.2

@amacavei14 downgrading the following dependencies fixed it for me:
"eslint-config-next": "12.1.6" -> "12.1.5"
"eslint-plugin-react": "7.30.0" -> "7.29.4"
"eslint-plugin-react-hooks": "4.5.0" -> "4.3.0"

**Comment by jamiter** [comment]
This is still an issue, so commenting to prevent automatic closure.

**Comment by thecoleorton** [comment]
> I can reproduce on latest NX 14 version as well. Removing plugin:@nrwl/nx/react-typescript from it didn't work for me either.
> 
> Node: 16.14.2 OS: MacOS Monterey 12.3.1 yarn: 1.22.17
> 
> nx: 14.3.2 typescript: 4.7.2
> 
> @amacavei14 downgrading the following dependencies fixed it for me: "eslint-config-next": "12.1.6" -> "12.1.5" "eslint-plugin-react": "7.30.0" -> "7.29.4" "eslint-plugin-react-hooks": "4.5.0" -> "4.3.0"

This fixed my issue.

**Comment by ThuVuThiBich** [comment]
I tried, but it could not solve that error :(
If anyone knows any solutions, please reply to help me.
Thanks a lot.

**Comment by TVermaas** [comment]
This is still an issue, so commenting to prevent automatic closure.

**Comment by yeasinjabed2** [comment]
Any idea how can i solve that ?
```
error - ESLint: Plugin "@next/next" was conflicted between ".eslintrc.json" and ".eslintrc.json » eslint-config-next/core-web-vitals » plugin:@next/next/core-web-vitals".
```

**Comment by HaNdTriX** [comment]
Yes!

This error often happens if you have an conflicting `.eslintrc` file up your directory tree. 

## Example

```
| - some-dir/.eslintrc <- conflicting config
| - some-dir/somepath/your-project/.eslintrc
```

## Solutions

### A. Resolve Conflict

Find the conflicting `.eslintrc` [configuration file](https://eslint.org/docs/latest/user-guide/configuring/configuration-files#configuration-file-formats) and resolve the conflict.

### B. Make your `.eslintrc` a root config

**File:** `.eslintrc.json`

```diff
{
+ "root": true
  "extends": "next/core-web-vitals"
}
```

[More info](https://eslint.org/docs/latest/user-guide/configuring/configuration-files)

**Comment by williamisnotdefined** [comment]
Same here.

**Comment by TVermaas** [comment]
Same here

**Comment by hyalen** [comment]
Same to me here. I'm currently using `eslint-config-next: 13.1.3`
