### ISSUE TITLE
Bamboo CI - NX in version 13.8.6 hanging node process

### ISSUE THREAD

**Issue by dewiktor2** [nrwl/nx#9895]
## Current Behavior
Recently I upgraded NX from 13.8.1 to latest, but it was building for ages in my bamboo CI environment. 
After this failure, I was upgrading release after release from 13.8.1 to 13.8.6. In version 13.8.6 build started to be very long (3h).
I notice that node.js process still doing his job after builds, after killing it  bamboo discover that script should be ended and build last 15 minutes.

![image](https://user-images.githubusercontent.com/10833264/164212292-e126257c-8c03-4d10-a962-11e4bb6b6d2b.png)

After build succeeded there is freeze for 3 hour and then bamboo probably detect slow build and kill process.

## Expected Behavior
Working CI BUILD ;(

### Failure Logs
There are no failure logs because build is successful after 3h. 

### Environment

   Node : 14.17.5
   OS   : win32 x64
   npm  : 6.14.14

   nx : undefined
   @nrwl/angular : 13.8.6
   @nrwl/cli : 13.8.6
   @nrwl/cypress : 13.8.6
   @nrwl/detox : undefined
   @nrwl/devkit : 13.8.6
   @nrwl/eslint-plugin-nx : 13.8.6
   @nrwl/express : undefined
   @nrwl/jest : 13.8.6
   @nrwl/js : undefined
   @nrwl/linter : 13.8.6
   @nrwl/nest : undefined
   @nrwl/next : undefined
   @nrwl/node : undefined
   @nrwl/nx-cloud : undefined
   @nrwl/react : undefined
   @nrwl/react-native : undefined
   @nrwl/schematics : undefined
   @nrwl/storybook : 13.8.6
   @nrwl/tao : 13.8.6
   @nrwl/web : undefined
   @nrwl/workspace : 13.8.6
   typescript : 4.5.5
   rxjs : 7.5.5
   ---------------------------------------
   Community plugins:
         @angular/animations: 13.3.1
         @angular/cdk: 13.3.2
         @angular/common: 13.3.1
         @angular/compiler: 13.3.1
         @angular/core: 13.3.1
         @angular/forms: 13.3.1
         @angular/localize: 13.3.1
         @angular/material: 13.3.2
         @angular/platform-browser: 13.3.1
         @angular/platform-browser-dynamic: 13.3.1
         @angular/router: 13.3.1
         @angular/service-worker: 13.3.1
         @ng-bootstrap/ng-bootstrap: 12.0.1
         devextreme-angular: 21.2.5
         ngx-bootstrap: 8.0.0
         @angular-devkit/architect: 0.1303.1
         @angular-devkit/build-angular: 13.3.1
         @angular-eslint/builder: 13.2.0
         @angular-eslint/schematics: 13.2.0
         @angular/cli: 13.3.1
         @angular/compiler-cli: 13.3.1
         @angular/language-service: 13.3.1
         @compodoc/compodoc: 1.1.19
         @storybook/angular: 6.4.20

**Comment by AgentEnder** [comment]
Hey! you mentioned trying w/ latest, can you confirm the version number you had tried at the time?

**Comment by dewiktor2** [comment]
In team, we were trying 13.9.5 and 13.9.6, I also tried today 13.10.3 with same effect ;(

**Comment by matt-ganz** [comment]
Bump. I just migrated from 13.1 to 14.0 and Bamboo is hanging. My 8 minutes builds are now taking 40 minutes. And yes, they fail or hang after a successful build.

**Comment by AgentEnder** [comment]
I'm coming back to this after vacation.... The 3 hour mark is suspiciously when we would shut the daemon down automatically. Can you check if adding `nx reset` at the end would eliminate the hanging? If so, we can update some checks regarding the daemon that may resolve this.

**Comment by AgentEnder** [comment]
Actually, a better check for this would be if you could add an env variable `CI=true` for your CI agents. If that works, then it confirms my suspicions

**Comment by matt-ganz** [comment]
Adding CI=true environment variable to my Bamboo build plan definitely did the trick. As soon as the build completes it continues to the next step and doesn't hang.

**Comment by AgentEnder** [comment]
I'll post a PR for this soon then, our CI detection for bamboo is a bit off

**Comment by dewiktor2** [comment]
> 
did you post PR?

**Comment by FrozenPandaz** [comment]
This should be fixed with 2899b3abfb4162c38bda3ec245bee0e59a59095e

Can you try again with the latest version of Nx?

**Comment by blackram** [comment]
Issue remains in 14.1.9. I added CI=true to Bamboo task to resolve.

Additionally I found issue with @nrwl/js not being pinned to 14.1.9. This caused npm install to block the task exit where it was the only step (no build). Locally, build had no problems or warnings

**Comment by AgentEnder** [comment]
The commit linked above is from 12 days ago, 14.1.9 was released 9 months ago. The root cause for this should be fixed now in the latest version of Nx though.

**Comment by blackram** [comment]
I see 14.8.6 was recently published, hopefully it is in that package.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by blackram** [comment]
Thanks, I'm looking at the https://nx.dev/packages/angular/documents/angular-nx-version-matrix. I'll try nx 15.7 seeing that the highest nx 14 was published 5 months ago.
